### ISSUE TITLE
ImportError: cannot import name drsuapi

### ISSUE THREAD

**Issue by shimmy21** [byt3bl33d3r/CrackMapExec#1]
Have the following problem in kalii linux 2.0 

~/CrackMapExec# python crackmapexec.py --help
Traceback (most recent call last):
  File "crackmapexec.py", line 15, in <module>
    from impacket.dcerpc.v5 import transport, scmr, samr, drsuapi, rrp, tsch, srvs, wkst
ImportError: cannot import name drsuapi

**Comment by byt3bl33d3r** [comment]
@shimmy21 upgrade your impacket installation using the github version

**Comment by shimmy21** [comment]
Thank you)

**Comment by byt3bl33d3r** [comment]
@shimmy21 np ;)

**Comment by DanMcInerney** [comment]
For the record or for anyone this might help, when I ran `pip install --upgrade -r requirements` I got:

Downloading/unpacking git+git://github.com/CoreSecurity/impacket (from -r requirements.txt (line 1))
  Cloning git://github.com/CoreSecurity/impacket to /tmp/pip-l38mIP-build
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection refused

I changed requirements.txt from:
  git+git://github.com/CoreSecurity/impacket.git
to:
  git+https://github.com/CoreSecurity/impacket

And all was well solving the original error in this issue.
