### ISSUE TITLE
Add file content searching support

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#10]
Hello again,

It would also be cool to have a **native file search** command in CrackMapExec, going further than just listing dirs (which is already cool btw).
You could be inspired by the `Invoke-FileFinder` function from [PowerView](https://github.com/PowerShellEmpire/PowerTools/tree/master/PowerView) module :)

Cheers.

**Comment by byt3bl33d3r** [comment]
@maaaaz Hi, do you mean share spidering ? if so it's already supported , take a look at the usage.

If you mean searching file *contents* on the other hand, I definitely agree it would be an awesome feature, I'm currently trying to find the best way of implementing it

**Comment by maaaaz** [comment]
Yes, I meant inside files :)

**Comment by byt3bl33d3r** [comment]
@maaaaz just fyi, Invoke-FileFinder does not search file contents , it spiders shares just like crackmapexec currently supports. Still looking for a efficient way of implementing this

**Comment by byt3bl33d3r** [comment]
@maaaaz added this in commit 39887088bfc236d1a253cff86a3d5626288cb16f

**Comment by maaaaz** [comment]
Well that is good news, I'm looking forward to test it.
I made some comments on your search_content` function, let me know if it is relevant :)

Cheers.

**Comment by byt3bl33d3r** [comment]
@maaaaz there are no memory leaks if we don't call close() since we are just calling some WinAPI's to open a handle to a remote file. Take a look at https://github.com/byt3bl33d3r/CrackMapExec/blob/master/crackmapexec.py#L465 to see how the RemoteFile class is implemented.
