### ISSUE TITLE
Support for normal MSSQL auth

### ISSUE THREAD

**Issue by fdiskyou** [byt3bl33d3r/CrackMapExec#107]
Not sure if this is bug... but I noticed that with MSSQL I can't authenticate with the sa account, only with Windows Authentication. Is this by design?

Here's the reply I get (tested with Win2003 SQLServer Express 2005 and Win2008 SQLServer Express 2008 R2).

04-24-2016 21:11:58 CME          192.168.88.162:1433 WIN-AI08CTL03FO [-] ERROR(WIN-AI08CTL03FO\SQLEXPRESS): Line 1: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.

**Comment by byt3bl33d3r** [comment]
This is by design, I'll see if there's a simple way to implement normal MSSQL auth.

**Comment by asolino** [comment]
Hey mate @byt3bl33d3r !

I'm sure you know, but just in case, [impacket](https://github.com/CoreSecurity/impacket) supports MSSQL authentication, just set `useWindowsAuth` to `False` when calling the [tds.login()](https://github.com/CoreSecurity/impacket/blob/master/impacket/tds.py#L837) method.

**Comment by byt3bl33d3r** [comment]
Added in v4.0
