### ISSUE TITLE
Pupy launcher support

### ISSUE THREAD

**Issue by byt3bl33d3r** [byt3bl33d3r/CrackMapExec#118]

**Comment by n00py** [comment]
At this point it may be better to do EmPyre/Empire 2.0 instead.  Pupy is cool but I think Empire is better now.

**Comment by byt3bl33d3r** [comment]
I'm inclined to agree, CME does currently have support for executing Empire 1.0 launchers via it's RESTful API (although there seems to be an auth bug which I'm hoping they will fix in 2.0)
