### ISSUE TITLE
Default thread number

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#12]
Hello @byt3bl33d3r,

I think that it would be cool if a default thread number was set, to avoid the frustration of forgetting the `-t` option :)

**Comment by byt3bl33d3r** [comment]
I'll have to think about this, the reasoning behind not having a default thread number is so you would have to  choose everytime how much 'noise' you want to make on the network

**Comment by DanMcInerney** [comment]
Just throwing my $.02 but I agree with maaaz. I always liked scripts that set sane defaults so the basic command is easier to remember but have the options clearly laid out in the readme.

**Comment by byt3bl33d3r** [comment]
@maaaaz @DanMcInerney  peer pressure aahhhhhhhh
