### ISSUE TITLE
Please add partial search in cmedb

### ISSUE THREAD

**Issue by jaredbarez** [byt3bl33d3r/CrackMapExec#130]
Please consider adding a feature in cmedb cli for partial search e.g.:
cmedb > hosts 10.80.0.
Above would list all IP addresses containing "10.80.0." (ID would differ not having a dot ".")
or 
cmedb > creds SuperUser
Above would list all creds with username containing "SuperUser"

Thanks!

**Comment by byt3bl33d3r** [comment]
This has been implemented in the newest version which will be released Friday.
Cheers

**Comment by byt3bl33d3r** [comment]
Closing, changes were just pushed to master.
