### ISSUE TITLE
Is it a bug on args parser?

### ISSUE THREAD

**Issue by CaledoniaProject** [byt3bl33d3r/CrackMapExec#131]
The following command is not parsed correctly,

```
crackmapexec --verbose -d corp.xx.com -u Administrator -p xxx 172.16.177.130 --user
```

But moving targets to the end works,

```
crackmapexec --verbose -d corp.xx.com -u Administrator -p xxx --users 172.16.177.130
```

Was it a bug?

**Comment by byt3bl33d3r** [comment]
Nope, this is expected. the ```-p``` flag can accept multiple arguments so by specifying the IP after will make CME parse it as such.

**Comment by CaledoniaProject** [comment]
I get it. Thanks
