### ISSUE TITLE
Powershell Obfuscation

### ISSUE THREAD

**Issue by c0d3xpl0it** [byt3bl33d3r/CrackMapExec#134]
Hello,

Whenever we use the crackmapexec in corporate environment with --mimikatz option, we dont receive any output. Mostly because AV flags mimikatz and stop execution. Is it possible to obfuscation the mimikatz powershell script can be obfuscated and then sent to target ? I saw one project for powershell obfuscation (https://github.com/danielbohannon/Invoke-Obfuscation). 

Do guide, if i am missing on something.

**Comment by c0d3xpl0it** [comment]
Any plans to release this feature in upcoming v4.0 ?

**Comment by byt3bl33d3r** [comment]
@c0d3xpl0it yup! I'm planning on integrating PS obfuscation in v4.0 using Invoke-Obfuscation. There is currently an issue with PowerShell v2.0 compatibility with the obfuscated scripts, I'm currently working with the author to resolve this issue https://github.com/danielbohannon/Invoke-Obfuscation/issues/10

**Comment by byt3bl33d3r** [comment]
Update on this, the code to support obfuscation through Invoke-Obfuscation is done (https://github.com/byt3bl33d3r/CrackMapExec/blob/master/cme/helpers/powershell.py), Im still currently waiting for that issue to be resolved.

**Comment by byt3bl33d3r** [comment]
implemented in 7149b24524cbd8b9b2ad6c42f7a1f6214c4137d9
