### ISSUE TITLE
Updating Latest Mimikatz Support

### ISSUE THREAD

**Issue by c0d3xpl0it** [byt3bl33d3r/CrackMapExec#138]
Hello,

Is there a roadmap for upgrading the Mimikatz to latest version by @gentilkiwi which supports Windows 10 Anniversary update & Windows Server 2016 (1607 - build 14393) ?

**Comment by byt3bl33d3r** [comment]
@c0d3xpl0it will be realising v4.0 hopefully by the end of the month and it will include the latest mimikatz version.
Cheers

**Comment by c0d3xpl0it** [comment]
Is this issue addressed in v4 release ?

**Comment by mpgn** [comment]
CME v4 and v5 are using Invoke-Mimikatz.ps1 script from Powersploit repo to dump lsass. To get latest version of Invoke-Mimikatz.ps1 use latest binary from cme (check action panel)
