### ISSUE TITLE
Desktop screenshot module

### ISSUE THREAD

**Issue by unl1k3ly** [byt3bl33d3r/CrackMapExec#139]
Hi, would be possible to screenshot a user desktop on a given /24 with cme? This would be so much handy! Cheers

**Comment by byt3bl33d3r** [comment]
Awesome idea, don't know why I didn't think of this
Thanks!

**Comment by unl1k3ly** [comment]
Thanks mate ! You rock !

**Comment by byt3bl33d3r** [comment]
@unl1k3ly done in 3cb0e7704306758865f21e6fae7777645fcd1496 :) check it out and let me know how it works!
