### ISSUE TITLE
--darrel flag naming scheme issue

### ISSUE THREAD

**Issue by vpnguy** [byt3bl33d3r/CrackMapExec#140]
The --darrel flag should be --darrell to match the name of the requesting party and to meet Darrell 2016 compliance.

Please fix this?!

**Comment by byt3bl33d3r** [comment]
Darrell 2016 compliance achieved.

https://github.com/byt3bl33d3r/CrackMapExec/blob/v4.0/cme/cli.py#L41

**Comment by vpnguy** [comment]
I approve this fix. Please open user contributions for the data file

**Comment by byt3bl33d3r** [comment]
I'm expecting the data file to have the most user contributions.
