### ISSUE TITLE
Scan gets stuck

### ISSUE THREAD

**Issue by Lexus89** [byt3bl33d3r/CrackMapExec#142]
Had a couple of times when doing a range scan for mimikatz/sam dump that it gets stuck after a couple of hosts (perhaps depending on the amount of threads) and does not move on to other systems. Unfortunately i don't have the logs anymore.. but wanted to let you know anyway.

**Comment by byt3bl33d3r** [comment]
Don't think I'll be able to do anything without the logs or some more info. 
Thanks for the heads up though.
