### ISSUE TITLE
Encrypted channels feature request

### ISSUE THREAD

**Issue by Lexus89** [byt3bl33d3r/CrackMapExec#15]
Is it possible to have encrypt channels such HTTPS for using the Mass Mimikatz which now uses HTTP?

**Comment by byt3bl33d3r** [comment]
I don't see why not! will take a stab at this today!

**Comment by byt3bl33d3r** [comment]
@Lexus89 done as of commit 7d2ba3c63a533df4a9a4501da3d72313d07ff4d7
