### ISSUE TITLE
Add error handling when using incorrect module options

### ISSUE THREAD

**Issue by c0d3xpl0it** [byt3bl33d3r/CrackMapExec#152]
## Steps to reproduce

Hello,
We encountered below error while running Powerview sub module.

root@kali:~# cme 10.0.1.6 -u ITService -p abcd@12345 -M powerview -o Get-ComputerDetails
Traceback (most recent call last):
  File "/usr/local/bin/cme", line 11, in <module>
    load_entry_point('crackmapexec==3.1.5.dev0', 'console_scripts', 'cme')()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/crackmapexec.py", line 219, in main
    module, context, server = loader.init_module(modules[m]['path'])
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/moduleloader.py", line 79, in init_module
    key, value = option.split('=', 1)
ValueError: need more than 1 value to unpack

## OS
Kali 2016

## Target OS
Windows 2008 R2

Please guide, if I am missing on something.

**Comment by byt3bl33d3r** [comment]
The command should be : 
```cme 10.0.1.6 -u ITService -p abcd@12345 -M powerview -o COMMAND=Get-ComputerDetails```

You can view the modules options by running:
```cme -M powerview --show-options```

However, this brought to light some error handling issues. Will keep this open as a reminder.

**Comment by byt3bl33d3r** [comment]
An error message should now appear when invalid options are specified.
Thanks!
