### ISSUE TITLE
Unable to run the script

### ISSUE THREAD

**Issue by AresS31** [byt3bl33d3r/CrackMapExec#153]
## Steps to reproduce

1. Install the script as detailed in the README
2. Run the command

## Command string used
ares@phlegethon:~/Tools/CrackMapExec/cme$ python crackmapexec.py

## CME verbose output (using the --verbose flag)
Traceback (most recent call last):
  File "crackmapexec.py", line 10, in <module>
    from cme.connection import Connection
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/connection.py", line 10, in <module>
    from impacket import tds
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/impacket/tds.py", line 36, in <module>
    import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.exceptions import InternalError
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cryptography/exceptions.py", line 7, in <module>
    from enum import Enum
ImportError: cannot import name Enum

## OS
Linux phlegethon 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

## Detailed issue explanation
I cannot run the script no matter if I install it via pip or via the github reposiotory as detailed in the README.

**Comment by byt3bl33d3r** [comment]
- Are you using a virtualenv?
- You're not supposed to be running the script directly as it's now packaged. Try running ```cme``` and see if that works.
- Output of ```pip freeze``` would be appreciated.

**Comment by AresS31** [comment]
1. I am not using virtualenv.
2. I installed the script via pip.
3. pip freeze output:
```
3to2==1.1.1
adns-python==1.2.1
AdvancedHTTPServer==2.0.5
alembic==0.8.8.dev0
anyjson==0.3.3
argcomplete==1.8.1
argh==0.26.2
attrs==16.3.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
basemap==1.0.7
BBQSQL==1.0
BeautifulSoup==3.2.1
beautifulsoup4==4.5.3
BlindElephant==1.0
blinker==1.3
boltons==16.4.1
brotlipy==0.6.0
capstone==3.0.4
cement==2.6.2
certifi==2016.2.28
chardet==2.3.0
Cheetah==2.4.4
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20170124
click==6.6
cluster==1.3.3
CME==1.0
colorama==0.3.7
ConfigArgParse==0.11.0
configobj==5.0.6
configparser==3.3.0.post2
constantly==15.1.0
construct==2.5.2
CouchDB==1.0
couchdbkit==0.6.5
creepy==1.2
crypto==1.4.1
cryptography==1.7.1
cssutils==1.0
cycler==0.10.0
dap==2.2.6.7
darts.util.lru==0.5
decorator==4.0.11
dicttoxml==1.7.4
dissy==9
distorm3==3.3.4
Django==1.8
dnslib==0.9.4
dnspython==1.15.0
docutils==0.13.1
dominate==2.1.5
-e git+https://github.com/droope/droopescan@409f9ba3f101fa2e84caecaa1ddf6f693e52399c#egg=droopescan
easygui==0.96
Elixir==0.7.1
enum34==1.1.6
esmre==0.3.1
feedparser==5.1.3
file-magic==0.3.0
Flask==0.12
flickrapi==2.1.2
FormEncode==1.3.0
functools32==3.2.3.post2
fuse-python==0.2.1
future==0.15.2
futures==3.0.5
GeoIP==1.3.2
geoip2==2.4.2
geojson==1.3.1
gevent==1.2.1
gitdb2==2.0.0
GitPython==2.1.0
google-api-python-client==1.5.5
greenlet==0.4.11
guess-language-spirit==0.5.2
h2==2.4.1
halberd==0.2.4
hpack==2.3.0
html2text==2016.9.19
html5lib==0.999999999
http-parser==0.8.3
httplib2==0.9
httpretty==0.8.14
hyperframe==4.0.1
icalendar==3.8
idna==2.2
impacket==0.9.15
incremental==16.10.1
ipaddress==1.0.17
ipcalc==1.1.3
IPy==0.83
ipython==5.1.0
ipython-genutils==0.1.0
itsdangerous==0.24
jdcal==1.0
Jinja2==2.8
jsbeautifier==1.6.4
jsonpickle==0.9.3
jsonrpclib==0.1.3
jwt==0.3.2
keepnote==0.7.8
keyring==10.1
keyrings.alt==1.3
killerbee==1.0
lxml==3.7.1
M2Crypto==0.24.0
Mako==1.0.6
Markdown==2.6.8
MarkupSafe==0.23
matplotlib==2.0.0
maxminddb==1.2.3
mechanize==0.2.5
mercurial==4.0
metaconfig==0.1.4a1
mitmproxy==0.18.2
mockito==0.5.2
msgpack-python==0.4.8
mysqlclient==1.3.7
Naked==0.1.31
nassl==0.12
ndg-httpsclient==0.4.2
netaddr==0.7.18
NetfilterQueue==0.6
NfSpy==1.0
nltk==3.2.1
NoSQLMap==0.7
numpy==1.12.0
oauth2client==3.0.0
oauthlib==2.0.1
olefile==0.42.1
openpyxl==2.3.0
PAM==0.4.2
paramiko==2.0.0
passlib==1.7.0.post20161128115349
Paste==2.0.3
PasteDeploy==1.5.2
PasteScript==1.7.5
pathlib2==2.1.0
pathtools==0.1.2
pbkdf2==1.3
pcapy==0.10.8
pdfminer==20140328
pefile==2016.3.28
pexpect==4.2.1
phply==1.0.0
pickleshare==0.7.4
Pillow==4.0.0
pluginbase==0.4
ply==3.9
prettytable==0.7.2
progressbar==2.3
prompt-toolkit==1.0.9
psutil==3.2.1
psycopg2==2.6.2
ptyprocess==0.5.1
py==1.4.32
pyasn1==0.1.9
pyasn1-modules==0.0.7
pybloomfiltermmap==0.3.15
pyClamd==0.3.17
pycrypto==2.6.1
pycurl==7.43.0
pydns==2.3.6
pyenchant==1.6.7
PyGithub==1.23.0
Pygments==2.2.0
pygobject==3.22.0
pyinotify==0.9.6
pyip==0.7
PyJWT==1.4.2
pylibemu==0.3.3
pymongo==2.7.2
pymssql==1.0.2
pyOpenSSL==0.15
pyotp==2.2.1
pyparsing==2.1.10
PyPDF2==1.26.0
pyperclip==1.5.27
pyrit==0.5.1
pyscard==1.9.4
pyserial==3.2.1
pysmb==1.1.19
pysnmp==4.3.2
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.6.5
pysqlite==2.7.0
pystache==0.5.4
pytest==3.0.6
python-apt==1.4.0b2
python-dateutil==2.5.3
python-debian==0.1.30
python-debianbts==2.6.1
python-editor==0.4
python-instagram==1.3.2
python-Levenshtein==0.12.0
python-ntlm==1.1.0
python-openid==2.2.5
python-pam==1.8.2
pytz==2016.7
pyusb==1.0.0b2
PyX==0.12.1
pyxdg==0.25
PyYAML==3.12
qrcode==5.3
reportbug==6.6.6
reportlab==3.3.0
requests==2.13.0
requests-oauthlib==0.7.0
requests-toolbelt==0.7.0
restkit==4.2.2
rfidiot==1.0
roman==2.0.0
rsa==3.4.2
ruamel.ordereddict==0.4.9
scapy===unknown.version
scgi==1.13
scipy==0.18.1
SecretStorage==2.3.1
service-identity==16.0.0
shellescape==3.4.1
simplegeneric==0.8.1
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.10.0
slowaes==0.1a1
smmap2==2.0.1
smoke-zephyr==1.0.2
socketpool==0.5.3
SQLAlchemy==1.0.15
subprocess32==3.2.7
tblib==1.3.0
tcpwatch==1.3.1
Tempita==0.5.2
termcolor==1.1.0
tornado==4.1
traitlets==4.3.1
tweepy==3.5.0
Twisted==16.6.0
typing==3.5.2.2
tzlocal==1.3
ua-parser==0.3.6
uritemplate==0.6
urllib3==1.19.1
urwid==1.3.1
user-agents==0.3.2
uTidylib==0.3
vinetto==0.7b0
volatility==2.6
vulndb==0.0.19
wafw00f==0.9.3
wapiti==2.3.0
watchdog==0.8.3
wcwidth==0.1.7
webencodings==0.5
webunit==1.3.10
Werkzeug==0.11.15
wfuzz==0.0.0
Whoosh==2.7.0
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xdot==0.5
xhtml2pdf==0.0.6
XlsxWriter==0.9.6
xmlbuilder==1.0
Yapsy==1.11.223
yara-python==3.5.0
zenmap==7.40
zim==0.65
zope.interface==4.3.2
```

**Comment by byt3bl33d3r** [comment]
Seems like it wasn't installed correctly (which is somewhat expected if you're not using a virtualenv).
Try installing it using the instructions here https://github.com/byt3bl33d3r/CrackMapExec/wiki/Installation

**Comment by AresS31** [comment]
Thanks for your answer @byt3bl33d3r it now seems to work!

I would appreciate more details on the purpose of the python virtualenv though. 

My first guess would be to solve requirement issues, like for the pyOpenSSL library which seemed to be the root cause of the issue I encountered.

Please tell me if I am wrong.

Many thanks,
AresS31

**Comment by byt3bl33d3r** [comment]
There is a ton of documentation out there about virtualenvs, this is a good place to start https://virtualenv.pypa.io/en/stable/
Cheers
