### ISSUE TITLE
Password Spraying with Username list

### ISSUE THREAD

**Issue by vysec** [byt3bl33d3r/CrackMapExec#155]
## Steps to reproduce

cme -u USERSLIST.txt -p Password1234 -d DOMAIN <TARGET>

If users list is more than 367, it stops at 367th user and doesn't seem to continue.

**Comment by vysec** [comment]
Same with password lists.

**Comment by its0x08** [comment]
it happen to me too 
plus unicode chars in this tool doesn't work at all and thats super bad !!!!

**Comment by byt3bl33d3r** [comment]
````
#~ cat users.txt | wc -l
499
#~ cme 192.168.122.42 -u users.txt -p Password1234
CME          192.168.122.42:445 WIN7            [*] Windows 6.1 Build 7601 (name:WIN7) (domain:LAB)
CME          192.168.122.42:445 WIN7            [-] LAB\user1:Password1234 STATUS_LOGON_FAILURE 
CME          192.168.122.42:445 WIN7            [-] LAB\user2:Password1234 STATUS_LOGON_FAILURE 
CME          192.168.122.42:445 WIN7            [-] LAB\user3:Password1234 STATUS_LOGON_FAILURE 
CME          192.168.122.42:445 WIN7            [-] LAB\user4:Password1234 STATUS_LOGON_FAILURE 
CME          192.168.122.42:445 WIN7            [-] LAB\user5:Password1234 STATUS_LOGON_FAILURE 
CME          192.168.122.42:445 WIN7            [-] LAB\user6:Password1234 STATUS_LOGON_FAILURE 
CME          192.168.122.42:445 WIN7            [-] LAB\user7:Password1234 STATUS_LOGON_FAILURE 

--- SNIP ---

CME          192.168.122.42:445 WIN7            [-] LAB\user496:Password1234 STATUS_LOGON_FAILURE 
CME          192.168.122.42:445 WIN7            [-] LAB\user497:Password1234 STATUS_LOGON_FAILURE 
CME          192.168.122.42:445 WIN7            [-] LAB\user498:Password1234 STATUS_LOGON_FAILURE 
CME          192.168.122.42:445 WIN7            [-] LAB\user499:Password1234 STATUS_LOGON_FAILURE 
[*] KTHXBYE!
```
Seems to work on my end.

What I'm guessing is happening is the threads are timing out before it manages to complete the user and/or password list.

Try setting the ```--timeout``` flag to a higher value (by default its 20 seconds):
```cme TARGET -u USERSLIST.txt -p Password1234 -d DOMAIN --timeout 120```

Let me know if that solves the issue

**Comment by vysec** [comment]
I'll get back to you ASAP.

**Comment by byt3bl33d3r** [comment]
Closing this for now since I'm pretty sure that was the issue. In any case in v4.0 (just pushed it to master) you don't need to specify that flag ;)

**Comment by intrd** [comment]
This same issue are happening to me w/ Version: 4.0.1dev
``
(CrackMapExec-aStMLsRy) intrd@p4f:~/appz/CrackMapExec$ cme smb 192.168.56.102 -u testte administrator tesste test2 test4 -p password mytest asdasd ma1ph123 test1
SMB         192.168.56.102  445    IE8WIN7          [*] Windows 7 Enterprise 7601 Service Pack 1 x32 (name:IE8WIN7) (domain:IE8WIN7) (signing:False) (SMBv1:True)
SMB         192.168.56.102  445    IE8WIN7          [-] IE8WIN7\testte:password STATUS_LOGON_FAILURE 
SMB         192.168.56.102  445    IE8WIN7          [-] IE8WIN7\testte:meuovo STATUS_LOGON_FAILURE 
SMB         192.168.56.102  445    IE8WIN7          [-] IE8WIN7\testte:asdasd STATUS_LOGON_FAILURE 
SMB         192.168.56.102  445    IE8WIN7          [-] IE8WIN7\testte:ma1ph123 STATUS_LOGON_FAILURE 
SMB         192.168.56.102  445    IE8WIN7          [-] IE8WIN7\testte:test1 STATUS_LOGON_FAILURE 
SMB         192.168.56.102  445    IE8WIN7          [-] IE8WIN7\administrator:password STATUS_LOGON_FAILURE 
SMB         192.168.56.102  445    IE8WIN7          [+] IE8WIN7\administrator:mytest (Pwn3d!)
(CrackMapExec-aStMLsRy) intrd@p4f:~/appz/CrackMapExec$ 



``
