### ISSUE TITLE
CME Help Option

### ISSUE THREAD

**Issue by c0d3xpl0it** [byt3bl33d3r/CrackMapExec#164]
Dear byt3bl33d3r, 

Thank you for awesome tool, but the current version is missing the proper Help options. Can guide me over this or I am missing on something ?

Also below old commands throw error now
cme -M powerview --show-options

**Comment by byt3bl33d3r** [comment]
I'll be updating the wiki accordingly. 
In essence the functionality is now divided up in 'protocols' now.
To access all of the help options for the AD functionality:
```
cme smb --help
```
