### ISSUE TITLE
4.0 Doesn't run by defualt

### ISSUE THREAD

**Issue by vysec** [byt3bl33d3r/CrackMapExec#166]
python setup.py install

then run>
```
┌─[root@zeroP]─[/opt/CrackMapExec]
└──╼ #cme
Traceback (most recent call last):
  File "/usr/local/bin/cme", line 11, in <module>
    load_entry_point('crackmapexec==4.0.0.dev0', 'console_scripts', 'cme')()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/crackmapexec.py", line 35, in main
    args = gen_cli_args()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/cli.py", line 67, in gen_cli_args
    protocol_object = p_loader.load_protocol(protocols[protocol]['path'])
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/loaders/protocol_loader.py", line 12, in load_protocol
    protocol = imp.load_source('protocol', protocol_path)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/protocols/smb.py", line 9, in <module>
    from impacket.examples.secretsdump import RemoteOperations, SAMHashes, LSASecrets, NTDSHashes
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.2.1-py2.7-linux-x86_64.egg/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named secretsdump
```

**Comment by byt3bl33d3r** [comment]
@vysec did you run:
```
git submodule init && git submodule update --recursive
```
Before ```python setup.py install```?

**Comment by byt3bl33d3r** [comment]
Also can you give me the OS you're running? thanks

**Comment by its0x08** [comment]
in version 4.0 I dont even understand how this tool works!
not just weird but ugly :-1: 
I add a target ang -t flag and the protocol and still nothing hapens rather than errors!

**Comment by byt3bl33d3r** [comment]
@its0x08 details on the errors you are getting would be appreciated. As for 'not understanding how the tool works', i sincerely doubt its that hard to understand.
In any case whenever I get the time I'll be updating the documentation accordingly and maybe publish a blog post

**Comment by its0x08** [comment]
@byt3bl33d3r well until then I cant post any error because maybe it's my fault for wrong usage!
thanks.

**Comment by byt3bl33d3r** [comment]
@vysec ping, any update on this?

**Comment by vysec** [comment]
Got nothing to bruteforce

**Comment by byt3bl33d3r** [comment]
think you might be confusing this issue with #155 ?

**Comment by vysec** [comment]
Ah, I'll check soon!!! I haven't been able to fix it yet

**Comment by byt3bl33d3r** [comment]
No rush :), thanks!

**Comment by vysec** [comment]
Ran it but still get same "no module called secretsdump" :/

**Comment by vysec** [comment]
Did another python setup.py install after it

**Comment by byt3bl33d3r** [comment]
@vysec I've updated the wiki regarding the most 'noticeable' changes in 4.0 https://github.com/byt3bl33d3r/CrackMapExec/wiki. 

Thanks!

**Comment by vysec** [comment]
Been getting this though:

ConfigParser.NoSectionError: No section: 'CME'

When running `cme smb`

**Comment by vysec** [comment]
Nvm just reinstalled :D

**Comment by Open-Sec** [comment]
Just in case, deleted ~/.cme and ConfigParser.NoSectionError: No section: 'CME' dissapear.  An old cme.conf...

**Comment by Clorth0** [comment]
Tried to reinstall, but to no avail. Running 'cme' only produces a command not found while 'crackmapexec' produces the same types of errors as the OP.
