### ISSUE TITLE
Issue running crackmapexec

### ISSUE THREAD

**Issue by xforjustice** [byt3bl33d3r/CrackMapExec#174]
Hi,
I keep getting this error running cme v4:

root@HPJL23453:/opt# cme smb 192.168.1.72 -u employee1  -p 'Password!' -d corp
Traceback (most recent call last):
  File "/usr/local/bin/cme", line 11, in <module>
    load_entry_point('crackmapexec==4.0.0.dev0', 'console_scripts', 'cme')()
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.0.dev0-py2.7.egg/cme/crackmapexec.py", line 50, in main
    current_workspace = config.get('CME', 'workspace')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'CME'

Thank you,

**Comment by simon--taylor** [comment]
The [CME] section is missing from your cme.conf. Add
```
[CME]
workspace=default
last_used_db=
```
The configuration file generated by v3 is missing that section.

**Comment by byt3bl33d3r** [comment]
or just delete ~/.cme/cme.conf, when you run CME again it will copy it.

**Comment by byt3bl33d3r** [comment]
I'll add some error handling to this since this seems to be an issue when upgrading to the new version.

**Comment by xforjustice** [comment]
It worked. Thank you.
