### ISSUE TITLE
Feature Request: Optional flag to use 3.1.5 way of doing command execution

### ISSUE THREAD

**Issue by okiwoki** [byt3bl33d3r/CrackMapExec#178]
## Detailed issue explanation

Pentesting from a restrictive environment sometimes doesn't allow ingress on port 445 on the attack machine. The 4.0 version of CME seems to throw an SMB server up for each exec method (wmiexec, smbexec, etc.) which I'm failing to get an output from commands due to CME waiting to get information back through 445.

I noticed in the debug output of 3.1.5 that it doesn't throw an SMB server up. Is it possible for you to add a flag like "--old-exec" to use the 3.1.5 method of executing commands?

**Comment by p1sc3s** [comment]
I would second this request!

**Comment by byt3bl33d3r** [comment]
I need to implement this for debugging purposes anyway, this is definitely on my priority list

**Comment by mpgn** [comment]
Fixed on v5 https://github.com/byt3bl33d3r/CrackMapExec/issues/260#issuecomment-617828318
