### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by aarislarsen** [byt3bl33d3r/CrackMapExec#183]
## Steps to reproduce

1.  cme smb targetfilewith400lines -u biglistusernames -p Password123 --fail-limit 2

## CME verbose output (using the --verbose flag)
Not possible, this was experienced in a customer environment

## OS
cme being run from Ubuntu 14.04 LTS

## Target OS
Primarily Windows 2012 and 2008, but a few UNIX-boxes in the mix as well

## Detailed issue explanation
When running cme against a large scope, after a few hundred hosts it intermittently reports "unable to open database file". It seems to start in smb/database.py cur.execute.

Sorry I can't post more details, but this was during an active pentest, just wondering if the issue was known or experienced by others.

**Comment by byt3bl33d3r** [comment]
@aarislarsen I haven't run into this. Can you give me the specs of the Ubuntu box you were running on?

**Comment by aarislarsen** [comment]
Turns out it was a permissions issue, sorry about that.
Not sure if it's related, but when running Mimikatz, the actual credentials
are never added to the database, but simply printed on screen. If
subsequently used, the credentials are then added to the database, but only
if they're found to be valid. Is that as intended?

2017-06-23 19:59 GMT+02:00 byt3bl33d3r <notifications@github.com>:

**Comment by byt3bl33d3r** [comment]
@aarislarsen sorry for the late response, this does sound very much like a permission issue. I'd recommend chowing everything under your username. Alternatively running CME as root should take care of everything i think (It needs it anyway to start up the servers).
Cheers
