### ISSUE TITLE
Brute force

### ISSUE THREAD

**Issue by bucky67gto** [byt3bl33d3r/CrackMapExec#184]
## Steps to reproduce

1. brute forcing with a large dictionary

## Command string used

crackmapexe 10.10.10.10 -u dude -p /home/passfile.txt

## CME verbose output (using the --verbose flag)

TEST\dude:dexter STATUS_LOGIN_FAILURE (The attempted logon is invalid.  This is either due to a bad username or authentication information.)

## OS

Kali

## Target OS

Windows (any flavor - tried 7 and 2003)

## Detailed issue explanation

Is there a limit to how many passwords it will use in brute force mode?  Seems to never finish the password file and even stops in different spots.  I have changed the threads and that seems to have no impact.

**Comment by byt3bl33d3r** [comment]
There is no limit. It worked last time i checked will take a look asap.

**Comment by bucky67gto** [comment]
Just did another check.  I have updated to the latest code and still seems to crap out short of the entire dictionary.  Just using the default dictionary that cain uses.  also tried a custom dictionary and the old faithful rockyou.txt.  most don't make it past a few hundred attempts.

**Comment by bucky67gto** [comment]
Is anyone else running into this with a large dictionary file?

**Comment by bucky67gto** [comment]
another attempt - anyone try this?

**Comment by scorpius** [comment]
It seems to stop at around 300 attempts for me.

**Comment by bucky67gto** [comment]
Thanks.  I'll give it a shot

**Comment by bucky67gto** [comment]
The latest version has indeed fixed this issue......thanks all
