### ISSUE TITLE
can't execute code on windows server 2016

### ISSUE THREAD

**Issue by theoneandonly-vector** [byt3bl33d3r/CrackMapExec#186]
## Steps to reproduce

run the following:

## Command string used
cme --verbose smb 192.168.0.34 -u Administrator -p PASSWORD -X 'whoami'

## CME verbose output (using the --verbose flag)
SMB         192.168.0.34    445    WINSERVER        [*] Windows Server 2016 Standard 14393 x64 (name:WINSERVER) (domain:WINSERVER) (signing:False) (SMBv1:True)
DEBUG Your pycrypto doesn't support AES.MODE_CCM. Currently only pycrypto experimental supports this mode.
Download it from https://www.dlitz.net/software/pycrypto
DEBUG add_credential(credtype=plaintext, domain=WINSERVER, username=Administrator, password=PASSWORD, groupid=None, pillaged_from=None) => None
SMB         192.168.0.34    445    WINSERVER        [+] WINSERVER\Administrator:PASSWORD
DEBUG Calling ps_execute()

## OS
arch linux

## Target OS
Server 2016

## Detailed issue explanation
I don't get any output of my command.

also tested and not working:
mimikatz_enum_chrome
--sam
enum_avproducts

**Comment by theoneandonly-vector** [comment]
installing the pycrypto mentioned in the error only removes the error -> still no output.

**Comment by byt3bl33d3r** [comment]
@theoneandonly-vector I'll take a look as soon as i have some time. Pretty swamped atm.
That being said, I have yet to run into a Server 2016 box in a client environment lol

**Comment by byt3bl33d3r** [comment]
What CME version are you using ? This could be related to #260

**Comment by abid28june** [comment]
its work perfectly on server 2016 i have invoked the mimikatz module it is working.

**Comment by theoneandonly-vector** [comment]
this is a arch-only issue
