### ISSUE TITLE
Make a default method for dumping DC (make it dcsync)

### ISSUE THREAD

**Issue by DanMcInerney** [byt3bl33d3r/CrackMapExec#191]
--ntds drsuapi    is not very intuitive. Maybe make --ntds without an argument just default to DCSYNC. or make an intuitive flag like --dumpdc or something.

**Comment by byt3bl33d3r** [comment]
Colomboscope?

**Comment by byt3bl33d3r** [comment]
Done in https://github.com/byt3bl33d3r/CrackMapExec/commit/0b936def2306047afb7277ad77f8bb8df59d9dfe
