### ISSUE TITLE
Error enumerating shares: 'ascii' codec can't encode characters in position 0-7

### ISSUE THREAD

**Issue by Sab0tag3d** [byt3bl33d3r/CrackMapExec#194]
## Steps to reproduce

1. Try enumerate shares on host, with Russian words in share's name.

## Command string used
crackmapexec --verbose smb -u user -p user --shares --users --lsa --local-auth --local-groups --loggedon-users 192.168.1.100
## CME verbose output (using the --verbose flag)
[-] Error enumerating shares: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
## OS
ubuntu 16.04
## Target OS
Windows Server 2003 3790 Service Pack 2 x32
Windows 8.1 Pro 9600 x64
## Detailed issue explanation
It's work perfect in ver  3.1.5dev, but now is broken.

**Comment by mpgn** [comment]
Hello @Sab0tag3d can you test on cme v5, without news on this one I will close.

**Comment by mpgn** [comment]
Closing since no update
