### ISSUE TITLE
Cannot launch it in Kali 2.0 64-bit

### ISSUE THREAD

**Issue by jaredbarez** [byt3bl33d3r/CrackMapExec#2]
![untitled](https://cloud.githubusercontent.com/assets/13761356/9368585/696f7bb4-46c4-11e5-9ea3-688085f506a8.png)

**Comment by byt3bl33d3r** [comment]
@jaredbarez duplicate of #1

**Comment by jaredbarez** [comment]
eh. my fault. sorry
