### ISSUE TITLE
Add a timeout parameter for failed connections

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#20]
Hello @byt3bl33d3r,

As the script accepts a CIDR which might have some several hosts not exposing a SMB share, and so inducing a failed connection on port 445, could it be possible to have a max timeout parameter (in seconds) ?

Cheers.

**Comment by byt3bl33d3r** [comment]
@maaaaz Already thought about it. This needs to get patched into the Impacket library, if I have time tomorrow will submit a PR.

**Comment by byt3bl33d3r** [comment]
@maaaaz this was implemented in cd103f5cb66537740b0e7ac7e759571470d48826 with the ```--timeout``` option

**Comment by maaaaz** [comment]
Cool! Glad that CME development resumed
