### ISSUE TITLE
Use the local account can not login

### ISSUE THREAD

**Issue by socmap** [byt3bl33d3r/CrackMapExec#206]
Use the local account: password can not login, as if the user name in front of the domain name

**Comment by vipzen** [comment]
If you are trying to login as a local user and not as a domain user, try specify a dot as the domain name via -d option. Example:

`cme smb -u user -p pass -d . 192.168.1.10`

**Comment by byt3bl33d3r** [comment]
there's a flag for this: ```--local-auth```
