### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by ArnCo** [byt3bl33d3r/CrackMapExec#207]
Hi mate,

As a french user, I get loads of encoding errors on my assessments, like the following:
`[-] Error enumerating shares: 'ascii' codec can't encode character u'\xe0' in position 15: ordinal not in range(128)`

Would it be possible to check all the input / outputs and make sure that the encoding is handled properly ? This occurs when listin users, shares, disks, executing commands, and so on... (i'm using 4.0.0dev version, available on blackarch).

Thank you for your time,

ArnCo

**Comment by martindube** [comment]
Hi ArnCo, Check this issue for a temporary fix: #181

**Comment by mpgn** [comment]
Should be fixed in v5. If you still have the error, feel free to re-open :)
