### ISSUE TITLE
SMB transport for payload delivery

### ISSUE THREAD

**Issue by byt3bl33d3r** [byt3bl33d3r/CrackMapExec#21]
So we can import scripts using an IEX cradle over HTTP, HTTPS and SMB \o/

**Comment by byt3bl33d3r** [comment]
This has been implemented, there currently seems to be a big in the impacket library when trying to download PS scripts over SMB. Will close when bug is fixed

**Comment by byt3bl33d3r** [comment]
Done, gave up on SMB transport as it would over-complicate things code wise

**Comment by byt3bl33d3r** [comment]
Re-opening so I remember to take another crack at this. I really want to see this happen

**Comment by asolino** [comment]
What problem in SMB Transport are you seeing?

**Comment by byt3bl33d3r** [comment]
Quite frankly I forgot, IIRC tho it had something to do with SMB Dialect negotiation on Win 10. I'll probably get to this today and will let you know if i run into the same issue

**Comment by asolino** [comment]
Great.. let me know if you can repro the issue.. I have some flight time to use ;)

**Comment by byt3bl33d3r** [comment]
This has been partially implemented in some of the modules in v4.0. Seems to work like a charm now!
