### ISSUE TITLE
'ascii' codec can't encode characters in position

### ISSUE THREAD

**Issue by vipzen** [byt3bl33d3r/CrackMapExec#211]
## Command string used
root@kali:~# cme --verbose smb 192.168.1.42 -u Administrador -p SuperPass --shares
## CME verbose output (using the --verbose flag)
DEBUG Passed args:
{'clear_obfscripts': False,
 'content': False,
 'cred_id': [],
 'darrell': False,
 'depth': None,
 'disks': False,
 'domain': None,
 'exclude_dirs': '',
 'exec_method': None,
 'execute': None,
 'fail_limit': None,
 'force_ps32': False,
 'gen_relay_list': None,
 'gfail_limit': None,
 'groups': None,
 'hash': [],
 'jitter': None,
 'list_modules': False,
 'local_auth': False,
 'local_groups': None,
 'loggedon_users': False,
 'lsa': False,
 'module': None,
 'module_options': [],
 'no_output': False,
 'ntds': None,
 'obfs': False,
 'only_files': False,
 'pass_pol': False,
 'password': ['SuperPass'],
 'pattern': None,
 'port': 445,
 'protocol': 'smb',
 'ps_execute': None,
 'regex': None,
 'rid_brute': None,
 'sam': False,
 'server': 'https',
 'server_host': '0.0.0.0',
 'server_port': None,
 'sessions': False,
 'share': 'C$',
 'shares': True,
 'show_module_options': False,
 'spider': None,
 'spider_folder': '.',
 'target': ['192.168.1.42'],
 'threads': 100,
 'timeout': None,
 'ufail_limit': None,
 'username': ['Administrador'],
 'users': None,
 'verbose': True,
 'wmi': None,
 'wmi_namespace': 'root\\cimv2'}
SMB         192.168.1.42    445    XPSP3PTBR        [*] Windows 5.1 x32 (name:XPSP3PTBR) (domain:XPSP3PTBR) (signing:False) (SMBv1:True)
DEBUG add_credential(credtype=plaintext, domain=XPSP3PTBR, username=Administrador, password=Su, groupid=None, pillaged_from=None) => None
SMB         192.168.1.42    445    XPSP3PTBR        [+] XPSP3PTBR\Administrador:SuperPass (Pwn3d!)
DEBUG Calling shares()
SMB         192.168.1.42    445    XPSP3PTBR        [+] Enumerated shares
SMB         192.168.1.42    445    XPSP3PTBR        Share           Permissions     Remark
SMB         192.168.1.42    445    XPSP3PTBR        -----           -----------     ------
SMB         192.168.1.42    445    XPSP3PTBR        IPC$                            IPC remoto
SMB         192.168.1.42    445    XPSP3PTBR        print$          READ,WRITE      Drivers de impressora
SMB         192.168.1.42    445    XPSP3PTBR        tmp             READ,WRITE      
SMB         192.168.1.42    445    XPSP3PTBR        [-] Error enumerating shares: 'ascii' codec can't encode characters in position 10-11: ordinal not in range(128)

## OS
Kali  2016.1
## Target OS
Windows XP SP2
## Detailed issue explanation
The string from share's description is: 'Administraçao remota' (Brazilian Portuguese).
So looks like a missing unicode conversion in 'ç' char.

**Comment by Urahara** [comment]
@byt3bl33d3r This bug is related to version of python, i get the same errors when i used to work with Python 2.7 its sucks, from python 3+ this type of errors don't occurs anymore. I will search on my home from solution i used to get around of this and then i will post here later.

**Comment by strasharo** [comment]
SAM dump is breaking for me, because one of the users is called InvitĂ©. Running on Python 2.7.15. Is there any workaround for this?

**Comment by nikallass** [comment]
> SAM dump is breaking for me, because one of the users is called InvitĂ©. Running on Python 2.7.15. Is there any workaround for this?

Check this out, baybe it will help
https://github.com/byt3bl33d3r/CrackMapExec/pull/315

**Comment by mpgn** [comment]
Since we switch to Python3 this problem should be solved. Feel free to reopen if you have this error with cme v5 :)
