### ISSUE TITLE
'version too low' SSL error with empire_exec

### ISSUE THREAD

**Issue by tratteur** [byt3bl33d3r/CrackMapExec#212]
Seeing similar issues to the problems with DeathStar and Empire on recent Kali.
Empire is started with the REST api and defaults, all running fine.

CME is the 'stable' version included in Kali (3.1.5)

```
crackmapexec smb 1.2.3.4 -u bob -p 'Password!' -d DOMAIN -M empire_exec -o LISTENER=DeathStar
EMPIRE_EXEC                                    [-] Unable to connect to Empire's RESTful API: HTTPSConnectionPool(host='127.0.0.1', port=1337): Max retries exceeded with url: /api/admin/login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_hello', 'version too low')],)",),))
```

**Comment by tratteur** [comment]
Just double-checked, this issue also affects 4.0.0dev - 'Sercurty' / current git.

**Comment by swarleysez** [comment]
Any update to this?  I'm getting the same issue running stable CME (3.1.5) and Empire 2.2

**Comment by network23** [comment]
Same issue on Kali with the 4.0.0dev version and Empire version 2.2.
It has something to do with SSL version?

**Comment by n8tr0n** [comment]
I just tried with a fresh install of Debian 9. Everything works. Took a few extra steps to get the crypto libraries installed.

**Comment by n8tr0n** [comment]
That was with Deathstar.

**Comment by dinvisible1** [comment]
hmmm, so what happens with kali 2.0 2017? cause both dont work

**Comment by AdrianVollmer** [comment]
May be related to this: https://bugs.python.org/issue31453

**Comment by byt3bl33d3r** [comment]
Just FYI this was a bug with Empire not CME. I submitted a PR to Empire (https://github.com/EmpireProject/Empire/pull/744) which addresses this issue and was merged recently. If you're still seeing the error you probably need to update Empire.
