### ISSUE TITLE
Kerberos support

### ISSUE THREAD

**Issue by byt3bl33d3r** [byt3bl33d3r/CrackMapExec#22]

**Comment by byt3bl33d3r** [comment]
Done in 3a7479d7dd2ca442154c8f15565df6c52727efa4

**Comment by byt3bl33d3r** [comment]
Needs to get re-implemented in v3.0

**Comment by mpgn** [comment]
TODO
- [ ] aeskey
- [ ] dc-ip
- [ ] checkifadmin()
