### ISSUE TITLE
crackmapexec with Empire + Deathstar

### ISSUE THREAD

**Issue by securityhawk** [byt3bl33d3r/CrackMapExec#225]
Hi Guys

Just wondering if anyone could lend a newbie a hand? I have installed Empire and Deathstar - Deathstar is listening fine through Empire.

I have tried Empires in built agent deployment / stagers but they don't seem to work.

I have read that I can use crackmapexec to stage an agent - does anyone have a spare moment to explain how this can be achieved?

Thanks

Phil

**Comment by lsorenson-os** [comment]
You can view the CrackMapExec modules currently avable using the ```--list-modules``` flag. One of them, you will notice, is ```empire_exec```. You will need to modify the Empire REST API credentials in the ```cme.conf``` file, which can be located in a variety of places such as ```{install root}/cme/data/cme.conf```. After creating a listener in Empire, you execute CME with the flag ```-M empire_exec``` and ```-o LISTENER=<listener name>```, where <listener name> is the Name you set for the Empire listener.

**Comment by byt3bl33d3r** [comment]
If you have questions about CME i suggest joining the #crackmapexec slack channel on [bloodhoundhq.slack.com](https://bloodhoundhq.slack.com/) and ask them there. Please only open an issue ticket to report bugs.
