### ISSUE TITLE
crackmapexec.py not giving any outputs after fresh installation

### ISSUE THREAD

**Issue by alisonliu** [byt3bl33d3r/CrackMapExec#227]
## Steps to reproduce

Just followed the instruction guide for Kali 
`apt-get install -y libssl-dev libffi-dev python-dev build-essential`
`pip install --user pipenv`
`git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec`
`cd CrackMapExec && pipenv install`
`pipenv shell`
`python setup.py install`

## CME verbose output (using the --verbose flag)
Nothing...

## OS
Kali Rolling

<img width="759" alt="no_output" src="https://user-images.githubusercontent.com/22718011/34803154-9545cbda-f626-11e7-9943-59432666a7d5.png">

**Comment by leebaird** [comment]
I'm having the same issue.

**Steps to reproduce.**
cd /opt/
apt-get install -y libssl-dev libffi-dev python-dev build-essential
git clone https://github.com/byt3bl33d3r/CrackMapExec
cd CrackMapExec/
python setup.py install
python ./crackmapexec.py
python ./crackmapexec.py -h
python ./crackmapexec.py --help

**OS**
Kali Linux Rolling

**Comment by aj-cgtech** [comment]
On my installation of kali, python setup.py install, installs the executable in /usr/local/bin as cme.

So try "cme" instead of "python ./crackmapexec.py"

**Comment by byt3bl33d3r** [comment]
it's installed as a package, the script is automatically installed in your PATH. You can run CME by running either `cme` or `crackmapexec`. It's *not* a script that you execute in the same directory
