### ISSUE TITLE
Feature Request: cmedb creds show hosts IP where creds came from

### ISSUE THREAD

**Issue by sdcampbell** [byt3bl33d3r/CrackMapExec#229]
First of all, great work and thank you so much for CME!

At the end of an engagement it would be very helpful to be able to see in the cmedb where the creds came from so I can find affected hosts. For example, when reporting where plaintext credentials in memory - Mimikatz, that info doesn't seem to be available in the db, like it is in Empire and Metasploit. 

Thanks again!

**Comment by byt3bl33d3r** [comment]
Hey there, sorry for the late response.

So this is already implemented in CME v4, once you're in database just type `creds <cred_id>` and you should see a `Pillaged From HostID column`. To get the IP of that host all you do is type `hosts <host_id>` here's an example:
![img-2018-03-01-131400](https://user-images.githubusercontent.com/5151193/36867701-2337a262-1d53-11e8-8234-9004cd014630.png)


If you don't see that column, it ptobably means you're using CME < 4.0.

Cheers

**Comment by scampbell-r7** [comment]
No, I wasn't using version 4. I was using the older version available in the Kali repositories. Thanks!
