### ISSUE TITLE
mimikatz output 'None' in user, password and domain

### ISSUE THREAD

**Issue by 9andrea1** [byt3bl33d3r/CrackMapExec#23]
after the last update i got this kind of output:
[+] 192.168.7.13 Found plain text creds! Domain: None Username: None Password: None

The line that print the above string is: 
print_succ('{} Found plain text creds! Domain: {} Username: {} Password: {}'.format(self.client_address[0], yellow(domain), yellow(user), yellow(passw)))

yellow() function has return value missed...
adding the return value in the function has worked for me:

def yellow(text):
    try:
        return colored(text.decode('utf8'), 'yellow', attrs=['bold'])
    except UnicodeDecodeError:
        colored(unicode(text, errors='ignore'), 'yellow', attrs=['bold'])

**Comment by byt3bl33d3r** [comment]
@9andrea1 Oops! thanks for catching this! should be fixed now!
