### ISSUE TITLE
Support of "domain\username" format in bulk input file for the username

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#243]
Hello @byt3bl33d3r,
It's been a long time that I hadn't opened an issue here :-)

I recently performed an assessment in a multi-domain environment and as I had to test several credentials, I couldn't do it easily with CME.

I would have loved that the `-u <FILE>` option would support a file containing for instance:
```
domain1\foo
domain2\bar
domain3\toto
```

Do you think it would be easily implementable ?

Cheers dude !

**Comment by byt3bl33d3r** [comment]
hey @maaaaz ! i don't think this should be a problem. I'll take a look.

**Comment by mpgn** [comment]
Better late than never I guess :)

![image](https://user-images.githubusercontent.com/5891788/80621705-f4a53400-8a47-11ea-8ce7-51963163706c.png)
