### ISSUE TITLE
Empire_Exec Module Rest API

### ISSUE THREAD

**Issue by Jett21** [byt3bl33d3r/CrackMapExec#244]
## Steps to reproduce

1. **i just follwed the owning the network with crapmapexec v4.0 in youtube**
2.

## Command string used
_**cme smb xxx.xxx.xxx.xxx  -u xxxxxx -p 'xxxxxxxx' -M empire_exec -o LISTENER=http**_
## CME verbose output (using the --verbose flag)

**_[-] Unable to connect to Empire's RESTful API: HTTPSConnectionPool(host='127.0.0.1', port=1337): Max retries exceeded with url: /api/admin/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5574d6a390>: Failed to establish a new connection: [Errno 111] Connection refused',))_**

## CME Version (cme --version)

_**CME v 4.0**_

## OS

**_Kali Linux 2018_**

## Target OS

**_Windows 7 and 10_**

## Detailed issue explanation

i followed everything in the owning the network with crapmapexec v4.0 video tutorial in youtube. and everything is good and working except the empire_exec_module. 

ohh and the Empire version is 2.5

thanks

**Comment by byt3bl33d3r** [comment]
You probably didn't start up empire with it's RESTful api. Empire has a `--api` flag which you need to give it at runtime.
