### ISSUE TITLE
Flag to Continue on Success When Password Spraying

### ISSUE THREAD

**Issue by plaverty9-r7** [byt3bl33d3r/CrackMapExec#245]
If I do a password spray with a file of users and a single password against a host, CME stops on the first success. I'd like for it to keep going. Can there be a flag to let it continue? For example, if I give it: 
cme smb 10.1.1.1 -u users.txt -p Spring2018
It will check each user in the users.txt file until one is successful, then the script exits. I would like to have something like a --continue-on-success or similar flag where it will keep going through the entire users.txt file. 

I am currently using: cme -v
4.0.1dev - Bug Pr0n

**Comment by magnusstubman** [comment]
Just read this and thought I might share it: "failing Kerberos pre-authentication does not trigger a Logon failure event (4625)" (unless excplicitly enabled) - https://speakerdeck.com/ropnop/fun-with-ldap-kerberos-and-msrpc-in-ad-environments

e.g. you should always password spray using kerberoes instead :)

**Comment by byt3bl33d3r** [comment]
just merged #248  which should address this.
