### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by codewatchorg** [byt3bl33d3r/CrackMapExec#25]
I haven't tested all functionality, but some minor changes enable this to work with Mimikatz on Windows:

263:        log_name = 'Mimikatz-{}-{}.log'.format(self.client_address[0], datetime.now().strftime("%Y-%m-%d_%H:%M:%S"))
264:+       if sys.platform == 'win32':
265:+            log_name = 'Mimikatz-{}-{}.log'.format(self.client_address[0], datetime.now().strftime("%Y-%+m-%d_%H%M%S"))

And also:
3102:-     if os.geteuid() is not 0:
3102:+    if sys.platform != 'win32':
3103:+        if os.geteuid() is not 0:

**Comment by byt3bl33d3r** [comment]
@codewatchorg Take a look at #7 and #9, since this apparently a wanted feature will see if I can add Windows support in today

**Comment by maaaaz** [comment]
I second that.
Take a look at my [latest post here] (https://github.com/byt3bl33d3r/CrackMapExec/issues/9).

**Comment by byt3bl33d3r** [comment]
@codewatchorg @maaaaz Added windows support in 56fe9aa19aeeafb965d766b8c6441f870341d7b1

**Comment by codewatchorg** [comment]
Awesome, thanks. On my Windows box, using mimikatz still fails as the log file that is generated includes a colon and Windows does not like colons in file names.

**Comment by maaaaz** [comment]
Okay, I'll patch this !

**Comment by maaaaz** [comment]
@codewatchorg, this should be fixed in the latest Windows version. Let me know if not.
Cheers

**Comment by maaaaz** [comment]
@byt3bl33d3r, would you be OK to put a link to crackmapexecwin in the readme as you proposed ?

Thanks.
Cheers
