### ISSUE TITLE
Unconsistent results presentation for spidering

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#26]
Hello @byt3bl33d3r ,

There is a weird result presentation for the spidering module. 
In the following example I have a `credz.txt` file in the `encoding2` folder but it is displayed as `//192.168.11.133/encoding2\*/credz.txt`: why is there the `*` char before ? 
I guess it is related to pattern matching.

```
$ python crackmapexec.py -d adyolo -u user1 -p "yoloswag1!" 192.168.11.133 -s share --spider encoding2 --content --pattern cred

[*] 192.168.11.133:445 is running Windows 6.3 Build 9600 (name:DC01) (domain:adyolo)
[+] 192.168.11.133:445 Login successful adyolo\user1:yoloswag1!
[*] 192.168.11.133:445 DC01 Started spidering
//192.168.11.133/encoding2\*/credz.txt [lastm:'2015-11-01 22:32' size:25]
[*] 192.168.11.133:445 DC01 Done spidering (Completed in 0.0818431377411)
```

**Comment by byt3bl33d3r** [comment]
@maaaaz This is normal, the * is regex needed for impacket API call to spider all the files and directories in the share. Will overhaul this today as per #29

**Comment by byt3bl33d3r** [comment]
@maaaaz commit 05fc05c17897d25a0f54efc9af06cf14ed068b19 fixed this too
