### ISSUE TITLE
Hardcoded "cmd.exe" in CME gets flagged by AV/EDR

### ISSUE THREAD

**Issue by jaredbarez** [byt3bl33d3r/CrackMapExec#262]
Whenever executing remote commands via CME by using atexec/wmiexec/mmcexec my remote session gets flagged by AV/EDR as "Suspicious activity: remotely spawning cmd.exe blah blah ...".

Is there a way to NOT use cmd.exe and fork/execute remote commands as a "standalone process" in user context that was used for remote session ? Why this relying on cmd.exe in order to execute a process ?

FYI I found string of "cmd.exe" as shown below, but don't know if cme generates it dynamicaly elsewhere...
```
CrackMapExec$ grep -i 'cmd.exe' -R *
cme/protocols/smb/wmiexec.py:        self.__shell = 'cmd.exe /Q /c '
cme/protocols/smb/mmcexec.py:        self.__shell = 'c:\\windows\\system32\\cmd.exe'
cme/protocols/smb/atexec.py:      <Command>cmd.exe</Command>
```
CME version is from commit 3984364cfb5080d467f815bd64adfa9f832e0880 (May 30 2018).

**Comment by byt3bl33d3r** [comment]
There really isn't a way around this due to the way CME has been written cmd.exe/powershell.exe will have to be called one way or another. We could possibly use some of the recent discovered LoLbins or WSH shenanigans  to execute commands which is on my feature list, but it would require some pretty major undertaking.

**Comment by sachinkamath** [comment]
@byt3bl33d3r do you still want to see work done on this?

**Comment by byt3bl33d3r** [comment]
@sachinkamath i mean, if you're sending a PR sure :)

**Comment by byt3bl33d3r** [comment]
I'm closing this because i'm personally not interested in playing the cat and mouse game with AV. Feel free to send a PR if you're interested in working on a bypass.
