### ISSUE TITLE
STATUS_OBJECT_NAME_INVALID

### ISSUE THREAD

**Issue by amiine90** [byt3bl33d3r/CrackMapExec#263]
I am trying to download a file from remote computer, but I am getting the error : 
SMB SessionError: STATUS_OBJECT_NAME_INVALID(The object name is invalid.)

Knowing that the file name i'm trying to download has spaces in it.

What is the correct syntax for the command ?

**Comment by byt3bl33d3r** [comment]
You must be using a really old version of CME for there to be a download flag. I do recall there being a bug with how file paths were handled. Closing since it is no longer supported
