### ISSUE TITLE
cme run error

### ISSUE THREAD

**Issue by 276585877** [byt3bl33d3r/CrackMapExec#264]
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty'

**Comment by byt3bl33d3r** [comment]
Closing since you didn't follow the installation instructions on the wiki [here](https://github.com/byt3bl33d3r/CrackMapExec/wiki/Installation)
