### ISSUE TITLE
error: can't copy 'cme/data/cme_powershell_scripts': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by bill-e-ghote** [byt3bl33d3r/CrackMapExec#267]
## Steps to reproduce

1. Follow "bleeding-edge" installation wiki for Arch linux (however, I am running Gentoo + Pentoo, so there's that)
2. 

## CME verbose output (using the --verbose flag)
/home/wdawson/.local/share/virtualenvs/CrackMapExec-YmXCZEOR/lib/python2.7/site-packages/setuptools/dist.py:398: UserWarning: Normalizing '4.0.1dev' to '4.0.1.dev0'
  normalized_version,
running install
running bdist_egg
running egg_info
writing requirements to crackmapexec.egg-info/requires.txt
writing crackmapexec.egg-info/PKG-INFO
writing top-level names to crackmapexec.egg-info/top_level.txt
writing dependency_links to crackmapexec.egg-info/dependency_links.txt
writing entry points to crackmapexec.egg-info/entry_points.txt
reading manifest file 'crackmapexec.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'cme/thirdparty'
no previously-included directories found matching 'cme/thirdparty/impacket/impacket/testcases'
no previously-included directories found matching 'cme/thirdparty/impacket/examples'
no previously-included directories found matching 'cme/thirdparty/pywinrm/winrm/tests'
no previously-included directories found matching 'cme/thirdparty/pywinrm/scripts'
no previously-included directories found matching 'cme/data/powersploit/Tests'
no previously-included directories found matching 'cme/data/powersploit/CodeExecution/Invoke-ReflectivePEInjection_Resources'
no previously-included directories found matching 'cme/data/powersploit/Exfiltration/LogonUser'
no previously-included directories found matching 'cme/data/powersploit/Exfiltration/NTFSParser'
no previously-included directories found matching 'cme/data/powersploit/Recon/Dictionaries'
no previously-included directories found matching 'cme/data/invoke-vnc/vncdll'
no previously-included directories found matching 'cme/data/invoke-vnc/winvnc'
no previously-included directories found matching 'cme/data/invoke-vnc/ReflectiveDLLInjection'
warning: no previously-included files matching '*.py' found under directory 'cme/data/invoke-vnc'
warning: no previously-included files matching '*.bat' found under directory 'cme/data/invoke-vnc'
warning: no previously-included files matching '*.msbuild' found under directory 'cme/data/invoke-vnc'
warning: no previously-included files matching '*.sln' found under directory 'cme/data/invoke-vnc'
warning: no previously-included files matching 'pebytes.ps1' found under directory 'cme/data/invoke-vnc'
no previously-included directories found matching 'cme/data/netripper/DLL'
no previously-included directories found matching 'cme/data/netripper/Metasploit'
no previously-included directories found matching 'cme/data/netripper/NetRipper'
no previously-included directories found matching 'cme/data/netripper/Release'
no previously-included directories found matching 'cme/data/netripper/Win32'
no previously-included directories found matching 'cme/data/netripper/minhook'
no previously-included directories found matching 'cme/data/netripper/x64'
warning: no previously-included files matching '*.pdf' found under directory 'cme/data/netripper'
warning: no previously-included files matching '*.sln' found under directory 'cme/data/netripper'
writing manifest file 'crackmapexec.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
error: can't copy 'cme/data/cme_powershell_scripts': doesn't exist or not a regular file

## Target OS
uname -a:
Linux pentoo 4.18.3-pentoo #1 SMP Wed Aug 22 19:31:36 EDT 2018 x86_64 Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz GenuineIntel GNU/Linux

## Detailed issue explanation
'python build.py build' script fails, whether following Wiki or just running the script in my own environment. Without following Wiki, the result is the same:

$ make CrackMapExec
git clone https://github.com/byt3bl33d3r/CrackMapExec.git
Cloning into 'CrackMapExec'...
remote: Counting objects: 2644, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 2644 (delta 4), reused 0 (delta 0), pack-reused 2632
Receiving objects: 100% (2644/2644), 5.62 MiB | 3.61 MiB/s, done.
Resolving deltas: 100% (1780/1780), done.
$ cd CrackMapExec
$ python2.7 setup.py build
/usr/lib64/python2.7/site-packages/setuptools/dist.py:347: UserWarning: Normalizing '4.0.1dev' to '4.0.1.dev0'
  normalized_version,
running build
running build_py
creating build
creating build/lib
creating build/lib/cme
copying cme/first_run.py -> build/lib/cme
copying cme/cmedb.py -> build/lib/cme
copying cme/__init__.py -> build/lib/cme
copying cme/context.py -> build/lib/cme
copying cme/logger.py -> build/lib/cme
copying cme/crackmapexec.py -> build/lib/cme
copying cme/connection.py -> build/lib/cme
copying cme/cli.py -> build/lib/cme
copying cme/msfrpc.py -> build/lib/cme
creating build/lib/cme/helpers
copying cme/helpers/powershell.py -> build/lib/cme/helpers
copying cme/helpers/misc.py -> build/lib/cme/helpers
copying cme/helpers/__init__.py -> build/lib/cme/helpers
copying cme/helpers/logger.py -> build/lib/cme/helpers
copying cme/helpers/bash.py -> build/lib/cme/helpers
copying cme/helpers/http.py -> build/lib/cme/helpers
creating build/lib/cme/servers
copying cme/servers/__init__.py -> build/lib/cme/servers
copying cme/servers/smb.py -> build/lib/cme/servers
copying cme/servers/http.py -> build/lib/cme/servers
creating build/lib/cme/loaders
copying cme/loaders/module_loader.py -> build/lib/cme/loaders
copying cme/loaders/__init__.py -> build/lib/cme/loaders
copying cme/loaders/protocol_loader.py -> build/lib/cme/loaders
creating build/lib/cme/parsers
copying cme/parsers/nessus.py -> build/lib/cme/parsers
copying cme/parsers/ip.py -> build/lib/cme/parsers
copying cme/parsers/__init__.py -> build/lib/cme/parsers
copying cme/parsers/nmap.py -> build/lib/cme/parsers
creating build/lib/cme/protocols
copying cme/protocols/__init__.py -> build/lib/cme/protocols
copying cme/protocols/mssql.py -> build/lib/cme/protocols
copying cme/protocols/smb.py -> build/lib/cme/protocols
copying cme/protocols/winrm.py -> build/lib/cme/protocols
copying cme/protocols/ssh.py -> build/lib/cme/protocols
copying cme/protocols/http.py -> build/lib/cme/protocols
creating build/lib/cme/protocols/winrm
copying cme/protocols/winrm/db_navigator.py -> build/lib/cme/protocols/winrm
copying cme/protocols/winrm/__init__.py -> build/lib/cme/protocols/winrm
copying cme/protocols/winrm/database.py -> build/lib/cme/protocols/winrm
creating build/lib/cme/protocols/http
copying cme/protocols/http/db_navigator.py -> build/lib/cme/protocols/http
copying cme/protocols/http/__init__.py -> build/lib/cme/protocols/http
copying cme/protocols/http/database.py -> build/lib/cme/protocols/http
creating build/lib/cme/protocols/smb
copying cme/protocols/smb/passpol.py -> build/lib/cme/protocols/smb
copying cme/protocols/smb/db_navigator.py -> build/lib/cme/protocols/smb
copying cme/protocols/smb/__init__.py -> build/lib/cme/protocols/smb
copying cme/protocols/smb/wmiexec.py -> build/lib/cme/protocols/smb
copying cme/protocols/smb/atexec.py -> build/lib/cme/protocols/smb
copying cme/protocols/smb/smbexec.py -> build/lib/cme/protocols/smb
copying cme/protocols/smb/remotefile.py -> build/lib/cme/protocols/smb
copying cme/protocols/smb/smbspider.py -> build/lib/cme/protocols/smb
copying cme/protocols/smb/database.py -> build/lib/cme/protocols/smb
copying cme/protocols/smb/mmcexec.py -> build/lib/cme/protocols/smb
creating build/lib/cme/protocols/ssh
copying cme/protocols/ssh/db_navigator.py -> build/lib/cme/protocols/ssh
copying cme/protocols/ssh/__init__.py -> build/lib/cme/protocols/ssh
copying cme/protocols/ssh/database.py -> build/lib/cme/protocols/ssh
creating build/lib/cme/protocols/mssql
copying cme/protocols/mssql/db_navigator.py -> build/lib/cme/protocols/mssql
copying cme/protocols/mssql/__init__.py -> build/lib/cme/protocols/mssql
copying cme/protocols/mssql/mssqlexec.py -> build/lib/cme/protocols/mssql
copying cme/protocols/mssql/database.py -> build/lib/cme/protocols/mssql
running egg_info
creating crackmapexec.egg-info
writing requirements to crackmapexec.egg-info/requires.txt
writing crackmapexec.egg-info/PKG-INFO
writing top-level names to crackmapexec.egg-info/top_level.txt
writing dependency_links to crackmapexec.egg-info/dependency_links.txt
writing entry points to crackmapexec.egg-info/entry_points.txt
writing manifest file 'crackmapexec.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'cme/thirdparty'
no previously-included directories found matching 'cme/thirdparty/impacket/impacket/testcases'
no previously-included directories found matching 'cme/thirdparty/impacket/examples'
no previously-included directories found matching 'cme/thirdparty/pywinrm/winrm/tests'
no previously-included directories found matching 'cme/thirdparty/pywinrm/scripts'
no previously-included directories found matching 'cme/data/powersploit/Tests'
no previously-included directories found matching 'cme/data/powersploit/CodeExecution/Invoke-ReflectivePEInjection_Resources'
no previously-included directories found matching 'cme/data/powersploit/Exfiltration/LogonUser'
no previously-included directories found matching 'cme/data/powersploit/Exfiltration/NTFSParser'
no previously-included directories found matching 'cme/data/powersploit/Recon/Dictionaries'
no previously-included directories found matching 'cme/data/invoke-vnc/vncdll'
no previously-included directories found matching 'cme/data/invoke-vnc/winvnc'
no previously-included directories found matching 'cme/data/invoke-vnc/ReflectiveDLLInjection'
warning: no previously-included files matching '*.py' found under directory 'cme/data/invoke-vnc'
warning: no previously-included files matching '*.bat' found under directory 'cme/data/invoke-vnc'
warning: no previously-included files matching '*.msbuild' found under directory 'cme/data/invoke-vnc'
warning: no previously-included files matching '*.sln' found under directory 'cme/data/invoke-vnc'
warning: no previously-included files matching 'pebytes.ps1' found under directory 'cme/data/invoke-vnc'
no previously-included directories found matching 'cme/data/netripper/DLL'
no previously-included directories found matching 'cme/data/netripper/Metasploit'
no previously-included directories found matching 'cme/data/netripper/NetRipper'
no previously-included directories found matching 'cme/data/netripper/Release'
no previously-included directories found matching 'cme/data/netripper/Win32'
no previously-included directories found matching 'cme/data/netripper/minhook'
no previously-included directories found matching 'cme/data/netripper/x64'
warning: no previously-included files matching '*.pdf' found under directory 'cme/data/netripper'
warning: no previously-included files matching '*.sln' found under directory 'cme/data/netripper'
writing manifest file 'crackmapexec.egg-info/SOURCES.txt'
creating build/lib/cme/data
copying cme/data/BloodHound-modified.ps1 -> build/lib/cme/data
copying cme/data/cme.conf -> build/lib/cme/data
error: can't copy 'cme/data/cme_powershell_scripts': doesn't exist or not a regular file

**Comment by byt3bl33d3r** [comment]
> `git clone https://github.com/byt3bl33d3r/CrackMapExec.git`

You forgot the `--recursive` flag when cloning the repo which downloads all the submodules CME depends on.
I'll make this a lot more clearer in the wiki as this seems to be a common issue.

**Comment by bill-e-ghote** [comment]
Unfortunately, the issue occurs for me even with --recursive is used.
