### ISSUE TITLE
Feature Req: Pass -x or -X arguments as a file

### ISSUE THREAD

**Issue by BaffledJimmy** [byt3bl33d3r/CrackMapExec#269]
Hello,

Would it be much work for CME to support the input of a file containing commands or PS commands to run upon successful authentication? Similar to how it can take a file for passwords or the -p switch directly.   Currently bash complains about various characters and it needs escaping etc, frequently doesn't work.

Plus this way you could have an SOP load of commands that you run upon machine compromise.

Thanks very much for CME, it helps me get all sorts of root :D

**Comment by byt3bl33d3r** [comment]
Love the idea, shouldn't be that hard to implement. I'll see what I can do.

Cheers

**Comment by mpgn** [comment]
![image](https://user-images.githubusercontent.com/5891788/80418646-0667c980-88d8-11ea-8586-c54cb703b174.png)

**Comment by BaffledJimmy** [comment]
Nice, thank you :)
