### ISSUE TITLE
Content spidering does not work

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#27]
Hello @byt3bl33d3r,

I'm trying to use, unsuccessfully, the content spidering feature.
I do have a `credz.txt` file in the `encoding2` folder in the share named `share`. 
The file tree hence looks like this:
```
C:\SHARE
\---encoding2
    |   credz.txt
```
The `credz.txt` file contains:
```
login:toto
password:titi
```

Trying the following command **does not find the pattern**:
```
$ python crackmapexec_bug.py -d adyolo -u user1 -p "yoloswag1!" 192.168.11.133 -s share --spider encoding2 --content --pattern login
[*] 192.168.11.133:445 is running Windows 6.3 Build 9600 (name:DC01) (domain:adyolo)
[+] 192.168.11.133:445 Login successful adyolo\user1:yoloswag1!
[*] 192.168.11.133:445 DC01 Started spidering
[*] 192.168.11.133:445 DC01 Done spidering (Completed in 0.0693302154541)
```

What am I doing wrong ? :)

Cheers.

**Comment by byt3bl33d3r** [comment]
Will see if i can reproduce. Thanks!

**Comment by byt3bl33d3r** [comment]
@maaaaz should be fixed now
