### ISSUE TITLE
cme: error: unrecognized arguments: --gen-relay-list relaylistOutputFilename.txt

### ISSUE THREAD

**Issue by evilmiracle** [byt3bl33d3r/CrackMapExec#270]
## Steps to reproduce

1. ... newest cme version
2. ... when i exec `cme smb 192.168.1.0/24 --gen-relay-list relaylistOutputFilename.txt`

he show me the error code

`cme: error: unrecognized arguments: --gen-relay-list relaylistOutputFilename.txt`

cme version 3.1.5 - 'Smidge'

verbose 

> DEBUG                                          {'domain': None, 'wdigest': None, 'verbose': True, 'sam': False, 'cred_id': [], 'module_options': [], 'fail_limit': None, 'share': 'C$', 'lusers': False, 'module': None, 'smb_port': 445, 'show_options': False, 'rid_brute': None, 'uac': False, 'ufail_limit': None, 'pass_pol': False, 'regex': None, 'list_modules': False, 'no_output': False, 'pattern': None, 'lsa': False, 'force_ps32': False, 'shares': False, 'content': False, 'server_host': '0.0.0.0', 'wmi': None, 'exclude_dirs': '', 'server_port': None, 'wmi_namespace': '//./root/cimv2', 'gfail_limit': None, 'mssql_query': None, 'username': [], 'hash': [], 'users': False, 'sessions': False, 'exec_method': None, 'spider': None, 'ps_execute': None, 'threads': 100, 'mssql_port': 1433, 'password': [], 'mssql': False, 'mssql_auth': 'windows', 'ntds_pwdLastSet': False, 'execute': None, 'target': ['flag'], 'ntds_history': False, 'disks': False, 'ntds': None, 'server': 'https', 'depth': 10, 'local_auth': False, 'timeout': 20}

os mac book pro

**Comment by awsmhacks** [comment]
I don't believe gen-relay-list was included in version 3.1.5 of cme. You'll have to get on 4.0.1

**Comment by evilmiracle** [comment]
> I don't believe gen-relay-list was included in version 3.1.5 of cme. You'll have to get on 4.0.1

yep, i update my cms in 4.0.1dev

**Comment by byt3bl33d3r** [comment]
Closing since I'm assuming you got it working after you updated.

**Comment by kildonan5** [comment]
for those of you who dont want to upgrade to the dev version, you can use the nmap nse script "smb-security-mode" in the interim

**Comment by infosecconsultant** [comment]
Hello. If you've come here for the same error on OSX that's because you did

`pip install --user crackmapexec
`
Like me. And it installed v 3.1.5
