### ISSUE TITLE
ERROR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by dnkls** [byt3bl33d3r/CrackMapExec#271]
When i use --sam every time see this error

`NONE             [-] RemoteOperations failed: RRP SessionError: code: 0x2 - ERROR_FILE_NOT_FOUND - The system cannot find the file specified.
`

**Comment by byt3bl33d3r** [comment]
Yup, gonna need a lot more info to debug this. Can you please fill out all the information requested in the issue template ?

**Comment by byt3bl33d3r** [comment]
Closing since i don't have enough info to debug this
