### ISSUE TITLE
Logging the share enumeration results in the database

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#277]
Hello there,

Could you add the feature of logging the share enumeration results in the database ? (just like the OS, version etc.) 
Today, attackers and defenders need to manually parse the log file in order to extract the enumeration, that's not really convenient :)

Best regards !

Thomas.

**Comment by DManolis** [comment]
That would save the day for my work, as it looks it is an enhacement...

**Comment by mpgn** [comment]
done
