### ISSUE TITLE
error: can't copy 'cme/data/cme_powershell_scripts': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by blshkv** [byt3bl33d3r/CrackMapExec#282]
Hi, I'm sure this is not a dup of #267 

I'm porting the latest version of tool for Pentoo linux and setuptools fails to build or install it. Here are simplified steps to produce the error:
```
git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec
cd CrackMapExec/
python2 setup.py build
```
the output is below (the second run):
```
/usr/lib64/python2.7/site-packages/setuptools/dist.py:366: UserWarning: Normalizing '4.0.1dev' to '4.0.1.dev0'
  normalized_version,
running build
running build_py
running egg_info
writing requirements to crackmapexec.egg-info/requires.txt
writing crackmapexec.egg-info/PKG-INFO
writing top-level names to crackmapexec.egg-info/top_level.txt
writing dependency_links to crackmapexec.egg-info/dependency_links.txt
writing entry points to crackmapexec.egg-info/entry_points.txt
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'cme/thirdparty/impacket/impacket/testcases'
no previously-included directories found matching 'cme/data/netripper/Release'
no previously-included directories found matching 'cme/data/netripper/Win32'
writing manifest file 'crackmapexec.egg-info/SOURCES.txt'
error: can't copy 'cme/data/cme_powershell_scripts': doesn't exist or not a regular file
```

```
ls -al cme/data/cme_powershell_scripts
total 568
drwxr-xr-x  2 blshkv blshkv   4096 Dec 10 21:14 .
drwxr-xr-x 11 blshkv blshkv   4096 Dec 10 21:11 ..
-rw-r--r--  1 blshkv blshkv   1356 Dec 10 21:14 Get-Screenshot.ps1
-rw-r--r--  1 blshkv blshkv     62 Dec 10 21:11 .git
-rw-r--r--  1 blshkv blshkv 511981 Dec 10 21:14 Invoke-PSInject.ps1
-rw-r--r--  1 blshkv blshkv  37137 Dec 10 21:14 Invoke-RickRoll.ps1
-rw-r--r--  1 blshkv blshkv    925 Dec 10 21:14 Invoke-Thunderstruck.ps1
-rw-r--r--  1 blshkv blshkv    357 Dec 10 21:14 Invoke-VoiceTroll.ps1
-rw-r--r--  1 blshkv blshkv   1884 Dec 10 21:14 Set-Wallpaper.ps1
```

any ideas?

**Comment by blshkv** [comment]
```
dev-python/setuptools-38.6.1
dev-python/setuptools_scm-1.15.6-r
```

**Comment by byt3bl33d3r** [comment]
@blshkv has this been resolved?

**Comment by blshkv** [comment]
no, it is not.
You can check yourself with steps I provided

**Comment by bill-e-ghote** [comment]
I have this same issue when I execute 'python setup.py build' from a fresh git pull instance. I am also running Pentoo overlay to Gentoo. Any progress on the issue on either end?

**Comment by bill-e-ghote** [comment]
If I temporarily move cme_powershell_scripts out of cme/data and try to build again, the same error occurs again for everything in cme/data. So, I moved everything out of that folder. Then, I see this:
error: can't copy 'cme/thirdparty/impacket': doesn't exist or not a regular file

The problem in both cases is that the things under cme/data are indeed not files, but are directories. Why should the build function break on that distinction? Sorry, my python skills are quite weak.

**Comment by bill-e-ghote** [comment]
It's all quite easy to work around with python2, less so with python3. Damned push to python3 is just a PITA.

**Comment by mpgn** [comment]
Closing this bug since no update, if it's still a bug on v5, I will re-open

**Comment by blshkv** [comment]
it was so long ago that I even forgot why I have come up with my workaround. I tried to remove it and can't reproduce the error. May be it is fixed indeed.
