### ISSUE TITLE
please migrate away from pycrypto

### ISSUE THREAD

**Issue by blshkv** [byt3bl33d3r/CrackMapExec#283]
the current requirement is to install pycrypto. This library is old and no longer supported.
Please migrate to pycryptodomex.

As a temporary solution you can keep the required version under ```thirdparty``` directory and make sure it has a priority over systemwide libraries.

**Comment by byt3bl33d3r** [comment]
Already done (sorta), It's a dependency of impacket not CME and they already switched over to pycryptodomex. When the PY3 re-write drops pycrypto will be long gone

**Comment by byt3bl33d3r** [comment]
Forgot about that, will do. Thanks!

**Comment by blshkv** [comment]
FYI, I have removed impacket from the thirdparty directory and tested smb module (it wasn't working with pycryptodome before. Everything seems work fine, thanks for the hint!

**Comment by whoot** [comment]
I can confirm this!
The only parameter working for now is *--shares*. 
Everything else just wont return a result. With *--verbose* I get:

```
crackmapexec 192.168.178.44 -d . -u Test -p SuperSecur3! --sam --verbose
DEBUG                                          {'domain': '.', 'wdigest': None, 'verbose': True, 'sam': True, 'cred_id': [], 'module_options': [], 'fail_limit': None, 'share': 'C$', 'lusers': False, 'module': None, 'smb_port': 445, 'show_options': False, 'rid_brute': None, 'uac': False, 'ufail_limit': None, 'pass_pol': False, 'regex': None, 'list_modules': False, 'no_output': False, 'pattern': None, 'lsa': False, 'force_ps32': False, 'shares': False, 'content': False, 'server_host': '0.0.0.0', 'wmi': None, 'exclude_dirs': '', 'server_port': None, 'wmi_namespace': '//./root/cimv2', 'gfail_limit': None, 'mssql_query': None, 'username': ['Test'], 'hash': [], 'users': False, 'sessions': False, 'exec_method': None, 'spider': None, 'ps_execute': None, 'threads': 100, 'mssql_port': 1433, 'password': ['SuperSecur3!'], 'mssql': False, 'mssql_auth': 'windows', 'ntds_pwdLastSet': False, 'execute': None, 'target': ['192.168.178.44'], 'ntds_history': False, 'disks': False, 'ntds': None, 'server': 'https', 'depth': 10, 'local_auth': False, 'timeout': 20}
CME          192.168.178.44:445 BLABLA         [*] Windows 10.0 Build 16299 (name:BLABLA) (domain:REDACTED)
DEBUG                                          Your pycrypto doesn't support AES.MODE_CCM. Currently only pycrypto experimental supports this mode.
Download it from https://www.dlitz.net/software/pycrypto
DEBUG                                          Your pycrypto doesn't support AES.MODE_CCM. Currently only pycrypto experimental supports this mode.
Download it from https://www.dlitz.net/software/pycrypto
CME          192.168.178.44:445 BLABLA         [+] .\Test:SuperSecur3! 
[*] KTHXBYE!
```

Installed it on Kali Linux via apt-get. Any recommendations for a short-time fix?

**Comment by blshkv** [comment]
@whoot you need to remove bundled impacket  and install the latest (0.9.18 in Pentoo). It does not require pycrypto and the error message will be gone.
However, I'm not sure if cme supports the latest impacket fully, that still need to be tested

**Comment by whoot** [comment]
@blshkv did also an upgrade to impacket 0.9.19dev, but with the same results.. 
And that is no result.
Crackmapexec dont recognize the user as admin and doesnt dump anyting

**Comment by byt3bl33d3r** [comment]
done in 333f1c4e06884e85b2776459963ef85d182aba8e

**Comment by blshkv** [comment]
I hope you have tested the functionality since @whoot reported that some functions return blank results.

**Comment by byt3bl33d3r** [comment]
I tested basic functionality and it all seems to be working. If there's something funky feel free to open an issue to track it
