### ISSUE TITLE
requirements.txt versioning is too strict

### ISSUE THREAD

**Issue by blshkv** [byt3bl33d3r/CrackMapExec#285]
I think the more realistic list of exact versions which is really specified in Pipfile.

Unnecessary strict requirements may cause problem with other tools which require the same package but other version.

Please relax versions and specify the exact version only if it is really required.

**Comment by byt3bl33d3r** [comment]
The requirements.txt file is automatically generated by pipenv when locking dependencies, i don't think there's a way to relax it. I'll take a look in the docs tho

**Comment by blshkv** [comment]
Ok, no problem. After filing the bug, i found that i should look at the list in the setup.py.

**Comment by byt3bl33d3r** [comment]
Closing since this seems to be resolved
