### ISSUE TITLE
LSA Secrets

### ISSUE THREAD

**Issue by bucky67gto** [byt3bl33d3r/CrackMapExec#292]
Able to gather hashed local creds, and also the lsa secrets........but

Not to sound like a noob, but I'm gonna......what can you do with LSA secrets? Can't pass the creds, and from what I have seen they are much harder to decrypt than a sam hash. Am I missing something ridiculously obvious.....thanks in advance. Always trying to learn new things.

**Comment by amarck1** [comment]
There are times where sam files may have no domain hashes but LSA does. The msft cached creds crack out no problem.

**Comment by bucky67gto** [comment]
so the hashes are NTLM hashes in the LSA?

**Comment by amarck1** [comment]
No, microsoft cached creds.
Look up MS-CACHE and MS-CACHE v2

**Comment by bucky67gto** [comment]
Thanks for the help....Always learning....
