### ISSUE TITLE
lunch crackmapexec in backgroung ?

### ISSUE THREAD

**Issue by Maxim-Costa** [byt3bl33d3r/CrackMapExec#293]
hello,
i would lunch crackmapexec with "crackmapexec 127.0.0.1  -u Administrateur -p "..\Dossier all\list_mdp.lst" /?" this command and in background but I do not know how to do it. Someone would have any idea

**Comment by awsmhacks** [comment]
Hi,
There are several ways of backgrounding a process in linux or you could use something like screen or tmux.  Check out these links and it might get you thinking:
https://www.lifewire.com/multitasking-background-foreground-process-2180219
https://linuxize.com/post/how-to-use-linux-screen/

This isnt really an issue with CME and would be better asked somewhere like stackoverflow.

**Comment by byt3bl33d3r** [comment]
This is a bash question, not a cme bug.
