### ISSUE TITLE
cme.helpers.logger Error

### ISSUE THREAD

**Issue by yildirimserkan** [byt3bl33d3r/CrackMapExec#301]
I installed all req but i always got this errors,

sudo ./crackmapexec.py -t 100 192.1.2.50
Traceback (most recent call last):
  File "./crackmapexec.py", line 6, in <module>
    from cme.helpers.logger import highlight
ImportError: No module named logger

Where is the problem ?

**Comment by donjuanme** [comment]
~/CrackMapExec/cme# python3 crackmapexec.py 
Traceback (most recent call last):
  File "crackmapexec.py", line 6, in <module>
    from cme.helpers.logger import highlight
ModuleNotFoundError: No module named 'cme.helpers.logger'; 'cme.helpers' is not a package

**Comment by mpgn** [comment]
Hello,

Use the wiki to install cme

```
git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec
cd CrackMapExec
python3 setup.py install
```
