### ISSUE TITLE
MSSQL connection without SMB?

### ISSUE THREAD

**Issue by stealthsploit** [byt3bl33d3r/CrackMapExec#306]
Hi,

Is it possible to make a direct MSSQL connection to execute queries without SMB access to the host? The --mssql mode stops working if access to 445 is blocked and didn't know if there was something I was missing, as this would rule out any DB work where only the MSSQL port was exposed?

Many thanks in advance.

**Comment by byt3bl33d3r** [comment]
This was a design decision, as making a direct MSSQL connection wouldn't really return any useful info about the host. You can modify the code so that it doesn't make an SMB connection pretty easily. PR's are welcome :)

**Comment by mpgn** [comment]
I look into this, maybe by adding one flag `--no-enumeration` :)

**Comment by mpgn** [comment]
Check the wiki updated https://github.com/byt3bl33d3r/CrackMapExec/wiki/MSSQL-Command-Reference#1-windows-auth
