### ISSUE TITLE
mimikatz

### ISSUE THREAD

**Issue by bucky67gto** [byt3bl33d3r/CrackMapExec#308]
has anyone been able to get mimikatz running on 4.0.1dev?

**Comment by Anton19780301** [comment]
It doesn’t work for me, although I am owned by computers.
I think mimikatz no longer works.

**Comment by bucky67gto** [comment]
Thanks for the response.

**Comment by awsmhacks** [comment]
@bucky67gto maybe try https://github.com/awsmhacks/CrackMapExtreme

**Comment by bucky67gto** [comment]
@awsmhacks - thanks....checked and still no mimikatz.  just keeps trying with no result.  I love some of the other features though...great rewrite/add

**Comment by awsmhacks** [comment]
@bucky67gto  Interesting, i thought i had it working across all windows versions. Do you know if there is other AV running and could you provide the version of windows? or possible the verbose output?

**Comment by dirtdiver512** [comment]
I have been using several version and I have found that I can not seem to get mimi to work on windows 10.  No antvirus.  Defender was picking it up but i have disabled that the best i can for now.  I have even tried to run the PS directl on the target......has version 4 and mimi been tested on windwos 10?

**Comment by mpgn** [comment]
Just tested on Windows server 2016

![image](https://user-images.githubusercontent.com/5891788/79741855-3c1e1880-8302-11ea-8005-b1f93effbbd7.png)
