### ISSUE TITLE
Versioning the project code

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#31]
Hello @byt3bl33d3r,

It would be cool that you version your code and even produce so called "stable" releases.
Cheers.

**Comment by byt3bl33d3r** [comment]
hey man, already been tagging stable releases for a while now. Take a look here https://github.com/byt3bl33d3r/CrackMapExec/releases

**Comment by maaaaz** [comment]
Sorry, my bad :)
I was more looking at the information inside the .py file.

**Comment by byt3bl33d3r** [comment]
I should add a version number in the script now that I think about it ;)
