### ISSUE TITLE
Testing multiple static credentials?

### ISSUE THREAD

**Issue by stealthsploit** [byt3bl33d3r/CrackMapExec#314]
Would it be possible to test multiple sets of static users/hashes from a single file instead of spraying all combinations? 

user1 hash1
user2 hash2

..but not user1 hash2 etc?

Thanks.

**Comment by mpgn** [comment]
Should be possible with bash

```bash
while IFS= read -r user && IFS= read -r hash <&3; do
  cme smb ip -u $user -H $hash 
done <fileA 3<fileB
```
