### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by sbrun** [byt3bl33d3r/CrackMapExec#317]
Hello,
Python 2.x will no longer be supported by their upstream developers in 2020. Thus Debian developers are actively removing Python 2 support in Debian Testing with the goal of getting rid of Python 2 in Debian 11 (bullseye).
Kali is tracking Debian Testing and is thus affected by this. You should consider to switch crackmapexec to Python 3.

FWIW this is tracked in https://gitlab.com/kalilinux/packages/crackmapexec/issues/1 on the Kali side.

**Comment by byt3bl33d3r** [comment]
I am aware, efforts on this have been ongoing for a while I just happened to get side tracked with some other projects of mine. Next month (October 2019) will be the official "Port CME to Python3" Month.

**Comment by mpgn** [comment]
I was ready to do it, but noticed that [pywerview](https://github.com/the-useless-one/pywerview) is not ported to python3 so I don't see how it is possible to port CME to python3 :'(

**Comment by mpgn** [comment]
Turns out I started to migrate the project to python3 https://github.com/mpgn/CrackMapExec/tree/python3

Of course, I migrate the pywerview to python3 too.

Here is a preview for tonight ! 

![image](https://user-images.githubusercontent.com/5891788/68552491-ec185d00-0417-11ea-83b1-f61e4254f0cb.png)

**Comment by mpgn** [comment]
I'm starting the fire https://github.com/byt3bl33d3r/CrackMapExec/pull/323 :)

**Comment by byt3bl33d3r** [comment]
Damn, this is crazy. Thanks for the help!

**Comment by Reelix** [comment]
Tried an install on 3.8 - Failed on https://github.com/dlitz/pycrypto - Which hasn't received a commit in the past 6 years and likely never will :p

**Comment by mpgn** [comment]
Very strange since CME doesn't use pycrypto anymore https://github.com/byt3bl33d3r/CrackMapExec/commit/333f1c4e06884e85b2776459963ef85d182aba8e ...

**Comment by rhertzog** [comment]
Hello, what's the current status for the Python 3 port ? It's getting harder for us (Kali) to keep crackmapexec with Python 2, Debian has already dropped the Python 2 version of impacket.

https://www.dlitz.net/software/pycrypto/ is available for Python 3.

**Comment by mpgn** [comment]
Hi @rhertzog CME is already ported to python3, we are waiting (since 2 month) for the approval of @byt3bl33d3r  to merge into the branch python3 for CME.

The project has also the dependency pywerview (python2 project) https://github.com/the-useless-one/pywerview/pull/34 where I'm also waiting for the PR (but this part is not a blocker since we can use my fork of their repo)

More info: https://github.com/byt3bl33d3r/CrackMapExec/pull/323

**Comment by rhertzog** [comment]
@mpgn Do you consider both of your PR as ready? If yes, we can already package your forks in Kali until we have proper upstream releases.

**Comment by mpgn** [comment]
Hello @rhertzog 

I've contact directly @byt3bl33d3r and he tells me that he has to deal with other issues first. He didn't forget us, he just has more important priorites :)

> Do you consider both of your PR as ready? If yes, we can already package your forks in Kali until we have proper upstream releases.

Not an ideal solution because I'm afraid people will still open issue on this github while the issue maybe related to the python3 CME project.
I've hoped the branch be merged even if some features (not related to python3) are missing (gevent over asyncio, only thirdparty with pip) but unfortunately no merge possible I guess.


I've tested to run my PR on latest Kali using this lines and CME is working fine on my side.

```bash
git clone --recursive https://github.com/mpgn/CrackMapExec && cd CrackMapExec
git checkout python3
git submodule update --recursive
python3 setup.py install
cme
````

**Comment by blshkv** [comment]
Hi @mpgn , thanks a lot for taking the initiative. I'm having a minor issue with python3, clould you have a look at the following please:
```
/usr/bin/python3.6 /var/tmp/portage/net-analyzer/crackmapexec-3.1.5_p20200124/temp/tmpjti65h7a.py
  File "/usr/lib64/python3.6/site-packages/cme/data/invoke-vnc/vncexec.py", line 235
    print 'Ip addr required for reverse connection'
                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Ip addr required for reverse connection')?

  File "/usr/lib64/python3.6/site-packages/cme/data/invoke-vnc/gen_buffer.py", line 15
    print res
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(res)?

removing /var/tmp/portage/net-analyzer/crackmapexec-3.1.5_p20200124/temp/tmpjti65h7a.py
writing byte-compilation script '/var/tmp/portage/net-analyzer/crackmapexec-3.1.5_p20200124/temp/tmpe5n5gbs4.py'
/usr/bin/python3.6 /var/tmp/portage/net-analyzer/crackmapexec-3.1.5_p20200124/temp/tmpe5n5gbs4.py
  File "/usr/lib64/python3.6/site-packages/cme/data/invoke-vnc/vncexec.py", line 235
    print 'Ip addr required for reverse connection'
                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Ip addr required for reverse connection')?

  File "/usr/lib64/python3.6/site-packages/cme/data/invoke-vnc/gen_buffer.py", line 15
    print res
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(res)?

removing /var/tmp/portage/net-analyzer/crackmapexec-3.1.5_p20200124/temp/tmpe5n5gbs4.py
running install_egg_info
Copying crackmapexec.egg-info to /var/tmp/portage/net-analyzer/crackmapexec-3.1.5_p20200124/image/_python3.6/usr/lib64/python3.6/site-packages/crackmapexec-5.0.0.dev0-py3.6.egg-info
running install_scripts
Installing cme script to /var/tmp/portage/net-analyzer/crackmapexec-3.1.5_p20200124/image/_python3.6/usr/lib/python-exec/python3.6
Installing cmedb script to /var/tmp/portage/net-analyzer/crackmapexec-3.1.5_p20200124/image/_python3.6/usr/lib/python-exec/python3.6
Installing crackmapexec script to /var/tmp/portage/net-analyzer/crackmapexec-3.1.5_p20200124/image/_python3.6/usr/lib/python-exec/python3.6
  File "/usr/lib64/python3.6/site-packages/cme/data/invoke-vnc/vncexec.py", line 235
    print 'Ip addr required for reverse connection'
                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Ip addr required for reverse connection')?

  File "/usr/lib64/python3.6/site-packages/cme/data/invoke-vnc/gen_buffer.py", line 15
    print res
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(res)?

 * python3_6: running distutils-r1_run_phase distutils-r1_python_install_all
```

**Comment by blshkv** [comment]
There is also one more issue with slinky.py module. It requires ```pylnk``` package, however it does not support python3.

**Comment by mpgn** [comment]
Hello @blshkv I fix the problem in this commit https://github.com/byt3bl33d3r/CrackMapExec/pull/323/commits/6ad97132af7de3d8da23e47900cac39ceb1f71a0

**Comment by blshkv** [comment]
@mpgn thanks. Can you also fix a bunch of prints which I posted above?

**Comment by mpgn** [comment]
PR submitted to the Invoke-vnc project @blshkv :)

**Comment by blshkv** [comment]
@mpgn I have merged all patches, managed to install, start and tested some basic functionality.
Great job!

**Comment by mpgn** [comment]
Closing this one since the python3 PR is merged 🖌️

**Comment by blshkv** [comment]
sorry, I can't find this commit and the merge pull request is still opened

**Comment by mpgn** [comment]
can you elaborate ?

**Comment by blshkv** [comment]
I have pulled the latest git version and still see the same errors as reported. I can still apply the same patch from the pull request

**Comment by mpgn** [comment]
I see, forgot about this one @blshkv nevertheless, I cannot do much if no one wants to merge my PR . . .

https://github.com/klsecservices/Invoke-Vnc/pull/2

**Comment by mpgn** [comment]
We can use my fork in the meantime :)

**Comment by blshkv** [comment]
Please keep this bug open until someone will find a power to press that damn merge button :-)

**Comment by byt3bl33d3r** [comment]
@blshkv Just for my clarity, are you getting errors when packaging CME cause of the VNC script thing?

**Comment by blshkv** [comment]
@byt3bl33d3r hm... I just realized that you have merged https://github.com/byt3bl33d3r/CrackMapExec/pull/323 pull request yesterday. My apologies, this bug can be closed!

These are remaining external modules:
https://github.com/klsecservices/Invoke-Vnc/pull/2
https://github.com/the-useless-one/pywerview/issues/36

**Comment by mpgn** [comment]
This should do the work :)
