### ISSUE TITLE
No Info Returned

### ISSUE THREAD

**Issue by dirtdiver512** [byt3bl33d3r/CrackMapExec#318]
Getting the below issue where it looks like the I can connect and and authenticate, but dont get a return back.  Also i dont get the pwd thing either....version 3 or 4 does the same thing.  Oddly if i run a pass-pol i get info back:

crackmapexec smb 172.16.1.231 -u user -p pasword --exec-method wmiexec -x 'dir'
CME          x.x.x.x:445 WIN-H8J78OM0BIU [*] Windows 6.1 Build 7601 (name:WIN-H8J78OM0BIU) (domain:WIN-H8J78OM0BIU)
CME          x.x.x.x:445 WIN-H8J78OM0BIU [+] WIN-H8J78OM0BIU\user:password
CME          172.16.1.231:445 WIN-H8J78OM0BIU [+] Enumerating active sessions
[*] KTHXBYE!

but i get nothing back

**Comment by mpgn** [comment]
Try with v5, should work so i'm closing but feel free to re-open :)
