### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by talboris** [byt3bl33d3r/CrackMapExec#322]
## Steps to reproduce
OS: Kali python 2.7
Target OS in the output
tried to reinstall 
have all requirments

crackmapexec smb 10.10.10.100  -u SVC_TGS -p somepasshere -M gpp_password --verbose

DEBUG                                          {'domain': None, 'wdigest': None, 'verbose': True, 'sam': False, 'cred_id': [], 'module_options': [], 'fail_limit': None, 'share': 'C$', 'lusers': False, 'module': 'gpp_password', 'smb_port': 445, 'show_options': False, 'rid_brute': None, 'uac': False, 'ufail_limit': None, 'pass_pol': False, 'regex': None, 'list_modules': False, 'no_output': False, 'pattern': None, 'lsa': False, 'force_ps32': False, 'shares': False, 'content': False, 'server_host': '0.0.0.0', 'wmi': None, 'exclude_dirs': '', 'server_port': None, 'wmi_namespace': '//./root/cimv2', 'gfail_limit': None, 'mssql_query': None, 'username': ['SVC_TGS'], 'hash': [], 'users': False, 'sessions': False, 'exec_method': None, 'spider': None, 'ps_execute': None, 'threads': 100, 'mssql_port': 1433, 'password': ['GPPstillStandingStrong2k18'], 'mssql': False, 'mssql_auth': 'windows', 'ntds_pwdLastSet': False, 'execute': None, 'target': ['smb', '10.10.10.100'], 'ntds_history': False, 'disks': False, 'ntds': None, 'server': 'https', 'depth': 10, 'local_auth': False, 'timeout': 20}
CME          10.10.10.100:445 DC              [*] Windows 6.1 Build 7601 (name:DC) (domain:ACTIVE)
Segmentation fault
 ...

**Comment by barrett092** [comment]
I'm getting this exact error as well - no idea what is causing it.

**Comment by mpgn** [comment]
Hello,

Can you test with v5 ? I don't have this problem on my side

![image](https://user-images.githubusercontent.com/5891788/79740815-90c09400-8300-11ea-98d2-aa2119a4e1f1.png)

**Comment by byt3bl33d3r** [comment]
Closing since this hasn't had any activity for a while.
