### ISSUE TITLE
Error when running PowerShell commands on certian machines 

### ISSUE THREAD

**Issue by a-satori** [byt3bl33d3r/CrackMapExec#328]
## Steps to reproduce

1. Running a PowerShell command on both Windows 7 and Windows 10

## Command string used

crackmapexec smb 192.168.1.25 -u admin -H <hash omitted> --exec-method wmiexec -X 'echo PowerShell test'

## CME verbose output (using the --verbose flag)

DEBUG                                          {'domain': None, 'wdigest': None, 'verbose': True, 'sam': False, 'cred_id': [], 'module_options': [], 'fail_limit': None, 'share': 'C$', 'lusers': False, 'module': None, 'smb_port': 445, 'show_options': False, 'rid_brute': None, 'uac': False, 'ufail_limit': None, 'pass_pol': False, 'regex': None, 'list_modules': False, 'no_output': False, 'pattern': None, 'lsa': False, 'force_ps32': False, 'shares': False, 'content': False, 'server_host': '0.0.0.0', 'wmi': None, 'exclude_dirs': '', 'server_port': None, 'wmi_namespace': '//./root/cimv2', 'gfail_limit': None, 'mssql_query': None, 'username': ['admin'], 'hash': ['<hash omitted>'], 'users': False, 'sessions': False, 'exec_method': 'wmiexec', 'spider': None, 'ps_execute': 'echo PowerShell test', 'threads': 100, 'mssql_port': 1433, 'password': [], 'mssql': False, 'mssql_auth': 'windows', 'ntds_pwdLastSet': False, 'execute': None, 'target': ['192.168.1.25'], 'ntds_history': False, 'disks': False, 'ntds': None, 'server': 'https', 'depth': 10, 'local_auth': False, 'timeout': 20}
CME          192.168.1.25:445 LIB-01   [*] Windows 6.1 Build 7601 (name:LIB-01) (domain:WORKGROUP)
CME          192.168.1.25:445 LIB-01   [+] WORKGROUP\admin <hash omitted> (Pwn3d!)
DEBUG                                          Unincoded command:
[Net.ServicePointManager]::ServerCertificateValidationCallback = {$true};
try{ 
[Ref].Assembly.GetType('System.Management.Automation.AmsiUtils').GetField('amsiInitFailed', 'NonPublic,Static').SetValue($null, $true)
}catch{}
echo PowerShell test

DEBUG                                          Target system is 192.168.1.25 and isFDQN is False
DEBUG                                          StringBinding: \\\\LIB-01[\\PIPE\\atsvc]
DEBUG                                          StringBinding: LIB-01[49154]
DEBUG                                          StringBinding: \\\\LIB-01[\\PIPE\\srvsvc]
DEBUG                                          StringBinding: \\\\LIB-01[\\PIPE\\browser]
DEBUG                                          StringBinding chosen: None
DEBUG                                          Error executing command via wmiexec, traceback:
DEBUG                                          Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cme/connection.py", line 446, in execute
    exec_method = WMIEXEC(self.host, self.username, self.password, self.domain, self.conn, self.hash, self.args.share)
  File "/usr/lib/python2.7/dist-packages/cme/execmethods/wmiexec.py", line 40, in __init__
    iWbemServices= iWbemLevel1Login.NTLMLogin('//./root/cimv2', NULL, NULL)
  File "build/bdist.linux-armv7l/egg/impacket/dcerpc/v5/dcom/wmi.py", line 3162, in NTLMLogin
    resp = self.request(request, iid = self._iid, uuid = self.get_iPid())
  File "build/bdist.linux-armv7l/egg/impacket/dcerpc/v5/dcomrt.py", line 1308, in request
    self.connect(iid)
  File "build/bdist.linux-armv7l/egg/impacket/dcerpc/v5/dcomrt.py", line 1268, in connect
    raise Exception('Can\'t find a valid stringBinding to connect')
Exception: Can't find a valid stringBinding to connect

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/lib/python2.7/dist-packages/cme/connection.py", line 173, in __init__
    getattr(self, k)()
  File "/usr/lib/python2.7/dist-packages/cme/connection.py", line 39, in _decorator
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cme/connection.py", line 494, in ps_execute
    return self.execute(create_ps_command(payload), get_output, methods)
  File "/usr/lib/python2.7/dist-packages/cme/connection.py", line 39, in _decorator
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cme/connection.py", line 478, in execute
    output = u'{}'.format(exec_method.execute(payload, get_output).strip().decode('utf-8'))
UnboundLocalError: local variable 'exec_method' referenced before assignment
2019-12-23T19:27:10Z <Greenlet at 0x75561e88: Connection(Namespace(content=False, cred_id=[], depth=10, dis, <cme.database.CMEDatabase instance at 0x753fb788>, '192.168.1.25', None, None)> failed with UnboundLocalError

[*] KTHXBYE!

## CME Version (cme --version)

both 3.1.5 - 'Smidge' and 4.0.1dev - Bug Pr0n

## OS

kali-rolling 2019.4 on a Raspberry Pi 3

## Target OS

Both Windows 7 and Windows 10 produce the same issue

## Detailed issue explanation
For some reason when attempting to run any PowerShell commands I've found that both Windows 7 and Windows 10 machines give this output. I've tried running the command on a Windows Server 2003 machine on the same network and it executed fine. I can't seem to determine the problem. Does anyone here have any ideas?

**Comment by mpgn** [comment]
Hello, can you test on v5 of CME ?

**Comment by byt3bl33d3r** [comment]
Closing since v5 was released. Please use the binaries and try again.
