### ISSUE TITLE
spidering for specific content saved within a file

### ISSUE THREAD

**Issue by abid28june** [byt3bl33d3r/CrackMapExec#330]
i would appreciate if you can add the feature related to the content enumeration (save within file)  like a file has some multiple secret code stored in a file and through CME we can look into it, currently it only support to discover the files not the data stored in such files.

**Comment by mpgn** [comment]
For now, use the module `spider_plus` https://github.com/byt3bl33d3r/CrackMapExec/commit/584c926af7bcb0963090c72a984ed4eeefa6c81b
