### ISSUE TITLE
having problem on kali 2020.1

### ISSUE THREAD

**Issue by sickwell** [byt3bl33d3r/CrackMapExec#334]
## Steps to reproduce
root@kali:/mnt/hgfs/oscp/Seclists/Passwords# uname -a
Linux kali 5.4.0-kali3-amd64 #1 SMP Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux
root@kali:/mnt/hgfs/oscp/Seclists/Passwords# uname -r
5.4.0-kali3-amd64
root@kali:/mnt/hgfs/oscp/Seclists/Passwords# cat /etc/issue
Kali GNU/Linux Rolling \n \l

## Issue:
root@kali:/opt/CrackMapExec# crackmapexec 
Traceback (most recent call last):
  File "/usr/local/bin/crackmapexec", line 11, in <module>
    load_entry_point('crackmapexec==4.0.1.dev0', 'console_scripts', 'crackmapexec')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty'
root@kali:/opt/CrackMapExec#

**Comment by sickwell** [comment]
Update from my side: apt-get install crackmapexec solve issue instead of installation from github

**Comment by Stefan-mcp** [comment]
for others - check the wiki, install page - theres some dependencies
also you need to git clone --recursive urlToCrackMeGit as theres other repositories embedded

**Comment by Stefan-mcp** [comment]
ps - there some broken scripts in the kali repo version sadly - including the mimikatz.py with typo on line 183 (rresponse = response). might be best to do it the git clone --recursive way to get current everything

**Comment by Stefan-mcp** [comment]
wow - fast fix mpgn. unfortunatly theres a small bunch comp issues that i later found, not just that one. mainly casting around the data module if remember correctly. i rolled back to a kali repo version atm and hand fixed them after grafting in the current mimikatz.py - i'll push the changes up in the next few days if you dont beat me to it.

also, theres a missing script in this current version - thats what lead to my roll back -- it the sh associated with the mimipenguin module - theres other errors in that module too (path issues), i found the script missing once id sorted the py path issue out, but didnt have time to mess further - dunno if you want to take a peek at that too :)

**Comment by mpgn** [comment]
@Stefan-mcp push on pull request on this repo https://github.com/mpgn/CrackMapExec/tree/python3 if you want them referenced in the following pull request https://github.com/byt3bl33d3r/CrackMapExec/pull/323

**Comment by byt3bl33d3r** [comment]
This seems like a packaging issue, you should file a bug in the Kali bug tracker. Also use the binaries under the action tab.
