### ISSUE TITLE
Fails to connect to IPv6 addresses

### ISSUE THREAD

**Issue by bert128** [byt3bl33d3r/CrackMapExec#339]
## Steps to reproduce

1. Attempt to run cme against an IPv6 address

## Command string used
crackmapexec --verbose smb fe80::c5d4:cb67:91ab:e7ca%eth0

## CME verbose output (using the --verbose flag)
...
DEBUG Error resolving hostname fe80::c5d4:cb67:91ab:e7ca%eth0: [Errno -9] Address family for hostname not supported

## CME Version (cme --version)
4.0.1dev - Bug Pr0n

## OS
Linux

## Detailed issue explanation
When given an address to connect to, CME uses the function gethostbyname() to resolve the address, this is a legacy function that does not support IPv6 and is called from line 36 of cme/connection.py.

A fix for this is to use gethost_addrinfo instead of the obsolete gethostbyname(), attached is a quick and dirty patch which accomplishes this.

```diff
--- cme/connection.py	2018-12-04 12:14:40.000000000 +0800
+++ /tmp/connection.py	2020-04-15 14:29:33.000000000 +0800
@@ -1,5 +1,6 @@
 import logging
 # from traceback import format_exc
+import socket
 from gevent.lock import BoundedSemaphore
 from gevent.socket import gethostbyname
 from functools import wraps
@@ -11,6 +12,19 @@
 user_failed_logins = {}
 
 
+def gethost_addrinfo(hostname):
+    try:
+        for res in socket.getaddrinfo(hostname, None, socket.AF_INET6,
+                socket.SOCK_DGRAM, socket.IPPROTO_IP, socket.AI_CANONNAME):
+            af, socktype, proto, canonname, sa = res
+    except socket.gaierror:
+        for res in socket.getaddrinfo(hostname, None, socket.AF_INET,
+                socket.SOCK_DGRAM, socket.IPPROTO_IP, socket.AI_CANONNAME):
+            af, socktype, proto, canonname, sa = res
+
+    return sa[0]
+
+
 def requires_admin(func):
     def _decorator(self, *args, **kwargs):
         if self.admin_privs is False: return
@@ -33,7 +47,7 @@
         self.local_ip = None
 
         try:
-            self.host = gethostbyname(self.hostname)
+            self.host = gethost_addrinfo(self.hostname)
         except Exception as e:
             logging.debug('Error resolving hostname {}: {}'.format(self.hostname, e))
             return
```

[cme-ipv6.txt](https://github.com/byt3bl33d3r/CrackMapExec/files/4479479/cme-ipv6.txt)

**Comment by Insideus** [comment]
Possible solution using ssh tunnel

ssh user@localhost -L 445:[IPV6]:445

crackmapexec  smb localhost
