### ISSUE TITLE
Unable to checkout pywerview

### ISSUE THREAD

**Issue by dr4mohamed** [byt3bl33d3r/CrackMapExec#342]
## Steps to reproduce

1. git submodule update --recursive
fatal: reference is not a tree: acd8db86c6189c8006b9795e15614479665136c2
Unable to checkout 'acd8db86c6189c8006b9795e15614479665136c2' in submodule path 'cme/thirdparty/pywerview'

## CME Version (cme --version)
last version
## OS
centos 7 
## Detailed issue explanation
Unable to checkout 'acd8db86c6189c8006b9795e15614479665136c2' in submodule path 'cme/thirdparty/pywerview'
error with module pywerview

**Comment by mpgn** [comment]
Hello,

New version of CME is out, can you try to clone again ?

```
apt-get install -y libssl-dev libffi-dev python-dev build-essential
git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec
cd CrackMapExec
python3 setup.py install
```

**Comment by byt3bl33d3r** [comment]
Use the binaries under the action tab. Should resolve this.
