### ISSUE TITLE
gpp_password and gpp_autologin throw tracebacks when attempting to decrypt creds

### ISSUE THREAD

**Issue by byt3bl33d3r** [byt3bl33d3r/CrackMapExec#350]
Just ran into this on a gig.

To reproduce just run the modules on a DC:
`cme smb 192.168.0.1 -u admin -p admin -m gpp_password/gpp_autologin`

Its a bytes/str conversion issue, probably some remaining cruft from the python3 port.

**Comment by mpgn** [comment]
Okay I fix the problem but I need to dig a little bit more because I had to patch impacket lib

![image](https://user-images.githubusercontent.com/5891788/79972684-a1a30e00-8496-11ea-9f16-3c115afbebe2.png)

**Comment by mpgn** [comment]
This commit does not solve the first problem but other error when impakcet is patched

**Comment by mpgn** [comment]
Okay problem solved I think without touching impacket :) 

@byt3bl33d3r can you confirm ?

**Comment by byt3bl33d3r** [comment]
Awesome! Thanks again! I’ll try it out in a sec
