### ISSUE TITLE
File containing targets not working

### ISSUE THREAD

**Issue by domwhewell** [byt3bl33d3r/CrackMapExec#352]
**Describe the bug**
Running crackmapexec smb against a file containing IP's line by line results in no output

**To Reproduce**
1. Create a file with ips line by line
pico file.txt
10.0.0.10
10.0.0.10
10.0.0.201
10.0.0.195

2. Run crackmapexec --verbose smb file.txt
DEBUG Passed args:
{'clear_obfscripts': False,
 'content': False,
 'continue_on_success': False,
 'cred_id': [],
 'darrell': False,
 'depth': None,
 'disks': False,
 'domain': None,
 'exclude_dirs': '',
 'exec_method': None,
 'execute': None,
 'fail_limit': None,
 'force_ps32': False,
 'gen_relay_list': None,
 'gfail_limit': None,
 'groups': None,
 'hash': [],
 'jitter': None,
 'list_modules': False,
 'local_auth': False,
 'local_groups': None,
 'loggedon_users': False,
 'lsa': False,
 'module': None,
 'module_options': [],
 'no_output': False,
 'ntds': None,
 'obfs': False,
 'only_files': False,
 'pass_pol': False,
 'password': [],
 'pattern': None,
 'port': 445,
 'protocol': 'smb',
 'ps_execute': None,
 'regex': None,
 'rid_brute': None,
 'sam': False,
 'server': 'https',
 'server_host': '0.0.0.0',
 'server_port': None,
 'sessions': False,
 'share': 'C$',
 'shares': False,
 'show_module_options': False,
 'spider': None,
 'spider_folder': '.',
 'target': ['file.txt'],
 'threads': 100,
 'timeout': None,
 'ufail_limit': None,
 'username': [],
 'users': None,
 'verbose': True,
 'wmi': None,
 'wmi_namespace': 'root\\cimv2'}
DEBUG Error resolving hostname 10.0.0.10
: an integer is required (got type bytes)
DEBUG Error resolving hostname 10.0.0.224
: an integer is required (got type bytes)
DEBUG Error resolving hostname 10.0.0.10
: an integer is required (got type bytes)
DEBUG Error resolving hostname 10.0.0.201
: an integer is required (got type bytes)
DEBUG Error resolving hostname 10.0.0.195
: an integer is required (got type bytes)

**Expected behavior**
crack map to return similar to the output below for each host
SMB         10.0.0.10   445    TEST         [*] Windows Server 2016 Standard 14393 x64 (name:TEST) (domain:TEST) (signing:False) (SMBv1:True)

**Crackmapexec info**
 - OS: Kali
 - Version of CME: 5.0.1dev

**Comment by mpgn** [comment]
Hello,

Is this a request for a new feature or a bug ?

According to the documentation this option doesn't exist https://github.com/byt3bl33d3r/CrackMapExec/wiki/SMB-Command-Reference

**Comment by domwhewell** [comment]
Sorry Bug

It has worked in the past version 4.0.1dev
root@kali:# crackmapexec smb file.txt
SMB 10.0.0.10 445 TEST [*] Windows Server 2016 Standard 14393 x64 (name:TEST1) (domain:TEST) (signing:False) (SMBv1:True)
SMB 10.0.0.224 445 TEST [*] Windows Server 2016 Standard 14393 x64 (name:TEST2) (domain:TEST) (signing:False) (SMBv1:True)
SMB 10.0.0.10 445 TEST [*] Windows Server 2016 Standard 14393 x64 (name:TEST3) (domain:TEST) (signing:False) (SMBv1:True)
SMB 10.0.0.201 445 TEST [*] Windows Server 2016 Standard 14393 x64 (name:TEST4) (domain:TEST) (signing:False) (SMBv1:True)
SMB 10.0.0.195 445 TEST [*] Windows Server 2016 Standard 14393 x64 (name:TEST4) (domain:TEST) (signing:False) (SMBv1:True)

Is this doc not valid anymore? https://github.com/byt3bl33d3r/CrackMapExec/wiki/Target-Formats

**Comment by mpgn** [comment]
My bad I miss read, I will investigate the bug thanks for the report, yes the doc is still valid :)

**Comment by mpgn** [comment]
![image](https://user-images.githubusercontent.com/5891788/80488221-4a051680-895e-11ea-839e-bfdbf7e1741a.png)

**Comment by mpgn** [comment]
![image](https://user-images.githubusercontent.com/5891788/80488538-c861b880-895e-11ea-9bed-75806cdbc61e.png)

**Comment by mpgn** [comment]
Feel free to re-open if you still have the issue !
