### ISSUE TITLE
Update RID-Hijacking 

### ISSUE THREAD

**Issue by blshkv** [byt3bl33d3r/CrackMapExec#353]
https://github.com/byt3bl33d3r/CrackMapExec/tree/master/cme/data
The current version is linked on  RID-Hijacking @ d044de2738d7eb6bcfab80eea1a74a1e5e756c8a
However, it were some changes in the latest, and this bug https://github.com/r4wd3r/RID-Hijacking/issues/2 should be fixed.

Could you update to the latest?

**Comment by mpgn** [comment]
Should be good, I update to latest commit on master

**Comment by blshkv** [comment]
sorry, the latest commit broke something,
https://github.com/byt3bl33d3r/CrackMapExec/issues/354
