### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/crackmapexec-5.0.1.dev0-py2.7.egg/cme/thirdparty'

### ISSUE THREAD

**Issue by samuelkneppel** [byt3bl33d3r/CrackMapExec#360]
**Describe the bug**
I receive the following error when I run `crackmapexec`:
```
(CrackMapExec) root@kali:/opt/CrackMapExec# crackmapexec 
Traceback (most recent call last):
  File "/usr/local/bin/crackmapexec", line 11, in <module>
    load_entry_point('crackmapexec==5.0.1.dev0', 'console_scripts', 'crackmapexec')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-5.0.1.dev0-py2.7.egg/cme/__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/crackmapexec-5.0.1.dev0-py2.7.egg/cme/thirdparty'
```

**To Reproduce**
1. run `crackmapexec` from Terminal

**Expected behavior**
No errors

**Screenshots**

**Crackmapexec info**
 - OS: Linux kali 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux
 - Version of CME: pulled via `git clone`; I believe 5.0.1dev
 - Installed from apt or using latest release ? Latest

**Additional context**
I had to run the install commands with `sudo` since I have a local user on Kali.

**Comment by mpgn** [comment]
You didn't even take the time to read the wiki ... If you can't read the wiki there is a binary for you
https://github.com/byt3bl33d3r/CrackMapExec/issues/355#issuecomment-621382915

**Comment by samuelkneppel** [comment]
> You didn't even take the time to read the wiki ... If you can't read the wiki there is a binary for you
> [#355 (comment)](https://github.com/byt3bl33d3r/CrackMapExec/issues/355#issuecomment-621382915)

Thanks, I misread the wiki the first time apparently and missed the first portion that mentioned the binaries. I downloaded one and it is working. Thanks for your help!
