### ISSUE TITLE
LSASSY module show message when no credential found

### ISSUE THREAD

**Issue by mpgn** [byt3bl33d3r/CrackMapExec#368]
![image](https://user-images.githubusercontent.com/5891788/80992277-90b0b000-8e39-11ea-8a75-33625edd124e.png)

A bit confusing when no credentials are found, we don't know if the module is launched or not, maybe a message like "No credentials found is better" @Hackndo ?

**Comment by mpgn** [comment]
![image](https://user-images.githubusercontent.com/5891788/80993877-20575e00-8e3c-11ea-9e95-98e7711e6ba9.png)

**Comment by Hackndo** [comment]
Didn't see your commit. I think it shouldn't be highlighted as it's not something we're looking for
https://github.com/byt3bl33d3r/CrackMapExec/pull/369
