### ISSUE TITLE
Binary File Not Working Upon Making it Executable

### ISSUE THREAD

**Issue by jsarkisian** [byt3bl33d3r/CrackMapExec#371]
**When downloading the latest Ubuntu binary, chmod-ing, and running, I get the following:**

`File "./cme", line 2
SyntaxError: Non-UTF-8 code starting with '\xbb' in file ./cme on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

**Expected behavior:**

CME runs as expected

**Running on:**

RPi 4
Linux Kali 4.19.93-Re4son-v8l+ #1 SMP PREEMPT Tue Jan 7 22:53:24 UTC 2020 aarch64 GNU/Linux

**Comment by mpgn** [comment]
This one https://github.com/byt3bl33d3r/CrackMapExec/releases/tag/v5.0.1dev ?

**Comment by jsarkisian** [comment]
https://github.com/byt3bl33d3r/CrackMapExec/actions/runs/95564438

I am apparently looking in the wrong place?

**Comment by mpgn** [comment]
No it's ok, when you unzip the archive, can you just try `python3 cme` ?

**Comment by jsarkisian** [comment]
All set! That worked... thinking I had some weird file transfer corruption or something. Thanks!
