### ISSUE TITLE
Can't install CrackMapExec v5.0.2dev

### ISSUE THREAD

**Issue by vezjak** [byt3bl33d3r/CrackMapExec#377]
**Describe the bug**
Can't install CrackMapExec on Linux Kali. Error: 
`Installed /usr/local/lib/python3.8/dist-packages/crackmapexec-5.0.2.dev0-py3.8.egg
Processing dependencies for crackmapexec==5.0.2.dev0
error: asn1crypto 0.24.0 is installed but asn1crypto>=1.3.0 is required by {'minikerberos'}
`

**To Reproduce**
Run commands:
`#~ apt-get install -y libssl-dev libffi-dev python-dev build-essential
#~ git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec
#~ cd CrackMapExec
#~ python3 setup.py install`

**Expected behavior**
Successfully installed tool.

**Crackmapexec info**
 - OS: Kali
 - Installed by instructions from https://github.com/byt3bl33d3r/CrackMapExec/wiki/Installation

**Comment by mpgn** [comment]
Much better, I will investigate :)

**Comment by mpgn** [comment]
Hello @vezjak can you try to upgrade `asn1crypto` ?

`pip3 install asn1crypto --upgrade --user`

**Comment by mpgn** [comment]
People confirm me this issue comes from Impacket, update to 0.21

**Comment by yellowawuku** [comment]
First make sure you have pip3 installed
sudo apt update
sudo apt install python3-pip

then;
pip3 install asn1crypto==1.3.0
pip3 install asn1crypto --upgrade --user

followed by
pip3 install prompt-toolkit==2.0.9

Hope it was helpfull :), mine worked tho.

**Comment by mohit614** [comment]
Sharing my experience in case that helps

for me error was this:

> Installed /usr/local/lib/python3.7/dist-packages/crackmapexec-5.1.0.dev0-py3.7.egg
> Processing dependencies for crackmapexec==5.1.0.dev0
> error: asn1crypto 0.24.0 is installed but asn1crypto>=1.3.0 is required by {'minikerberos'}

 I resolved by installing that asn1crypto directly in that directory itself

> $ sudo pip install asn1crypto==1.3.0 -t /usr/local/lib/python3.7/dist-packages/

**Comment by CalfCrusher** [comment]
Same problem on Python 3.9. None of solutions suggested worked for me.

**Comment by 6062055** [comment]
Same here, having the same problem with CME.  Anyone know what might be the reason for this, or how to start troubleshooting this?
![image](https://user-images.githubusercontent.com/32880555/132252832-9374f257-f3d5-47fd-b2c2-64dd926b56f7.png)

**Comment by alan6t9** [comment]
sucks

**Comment by keldnorman** [comment]
AGREE IT SUCKS - why the F cant people make script kiddy friendly hacker tools - we spend all our time compiling and fixing stupid python missing something errors.. ;)
