### ISSUE TITLE
CME changes domain\ suffix to None\

### ISSUE THREAD

**Issue by sxplitfirex** [byt3bl33d3r/CrackMapExec#379]
**Describe the bug**
CME changes domain suffix to None\ when used with winrm
if used with smb it works perfect

**To Reproduce**
crackmapexec winrm <ip> -u user -p password

**Expected behavior**
automatically find the domain name and append it to the user

**Screenshots**
```
root@kali:~/Desktop/CTF# crackmapexec winrm targets -u user.txt -p "P@ssw0rd"
WINRM       10.10.1.10   5985   NONE             [-] None\testuser:P@ssw0rd "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
```

**Crackmapexec info**
 - OS: kali
 - Version of CME 5.0.0dev
 - Installed from apt

**Comment by mpgn** [comment]
Hello @sxplitfirex does your target is linked to a domain ?

**Comment by mpgn** [comment]
Closing since no update

**Comment by sxplitfirex** [comment]
> Closing since no update

Sorry for not seeing this earlier.
Yes, the target is domain joined, and the issue only happens with WINRM, the other protocols work fine.
