### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by maycon** [byt3bl33d3r/CrackMapExec#38]
I really like this tool, but I'm having some problems with encoding.

I'm trying to run it against a host with words like "Administração", "Usuário" so on.

```
root@host:~/tools/CrackMapExec# git pull
Already up-to-date.

root@host:~/tools/CrackMapExec# ./crackmapexec.py -t 20 -u **USER** -p **PASS** **HOST** --sam
[*] **HOST**:445 is running Windows 5.1 (name:**NAME**) (domain:**DOMAIN**)
[+] **HOST**:445 Login successful **CREDS**
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "./crackmapexec.py", line 3072, in connect
    sam_dump.dump(smb)
  File "./crackmapexec.py", line 1709, in dump
    bootKey = self.__remoteOps.getBootKey()
  File "./crackmapexec.py", line 933, in getBootKey
    self.__bootKey += bootKey[transforms[i]]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
<Greenlet at 0xa356cac: connect('**HOST**')> failed with UnicodeDecodeError

root@host:~/tools/CrackMapExec#
```

**Comment by byt3bl33d3r** [comment]
@maycon Hi, This is a bug in the impacket library will pass this along to the dev. Thanks

**Comment by byt3bl33d3r** [comment]
Pinging @asolino, looks like a unicode bug in secretsdump.py here https://github.com/CoreSecurity/impacket/blob/master/examples/secretsdump.py#L1967.

**Comment by asolino** [comment]
@byt3bl33d3r 
Hmm.. I can't spot it.. can you? 
Btw, there are two `getBootKey` methods. One is [RemoteOperations.getBootKey()](https://github.com/CoreSecurity/impacket/blob/master/examples/secretsdump.py#L589) and the other one [DumpSecrets.getBootKey()](https://github.com/CoreSecurity/impacket/blob/master/examples/secretsdump.py#L1967). This last one is used if you're reading the registry hives locally (as explained [here](https://github.com/CoreSecurity/impacket/blob/master/examples/secretsdump.py#L1968)).

I think you pointed out the wrong one.

**Comment by byt3bl33d3r** [comment]
@asolino oops , meant to point [RemoteOperations.getBootKey()](https://github.com/CoreSecurity/impacket/blob/master/examples/secretsdump.py#L589)

**Comment by asolino** [comment]
I can't get to spot an encoding error there.. do you?

@maycon can you tell us:
1. Operating System (version and language) you're launching `crackmapexec.py` from?
2. Operating System (version and language) of the target system?

**Comment by byt3bl33d3r** [comment]
the exact line where the exception occurs is here https://github.com/CoreSecurity/impacket/blob/master/examples/secretsdump.py#L606

**Comment by asolino** [comment]
@byt3bl33d3r yeah I saw that. But still don't understand why that would trigger an encoding error. Can you reproduce this issue?

@maycon any chance you add a 
```
print repr(bootKey) 
```
before this `for` loop in `crackmapexec.py` at line 932?

and send us the output.

**Comment by byt3bl33d3r** [comment]
@asolino holdon, think this might be my fault, will push a fix in a sec to see if it helps

**Comment by asolino** [comment]
@byt3bl33d3r what do you think is it?

**Comment by byt3bl33d3r** [comment]
@maycon Do a git pull and see if that helps.

@asolino just guessing, but I added 
```python
from __future__ import unicode_literals
```
so all strings are now unicode by default in CrackMapExec, there are a lot of variables initialized with an empty string like ```bootKey = ''``` which are now unicode strings so when it hits line 933 it might be having issues when appending to the string e.g.``` self.__bootKey += bootKey[transforms[i]]```

**Comment by asolino** [comment]
@byt3bl33d3r ohhh.. that is quite a change mate!. That could be it indeed.

**Comment by byt3bl33d3r** [comment]
yeah looking back it wasn't a smart idea, was just fed up with dealing with unicode issues.

**Comment by asolino** [comment]
@byt3bl33d3r I feel your pain.. Unicode ain't easy.

**Comment by maaaaz** [comment]
@byt3bl33d3r, unicode pains will never end :(

**Comment by byt3bl33d3r** [comment]
@maycon the new version should resolve at least some issues related to unicode
