### ISSUE TITLE
Module helpers  cannot import name 'highlight'

### ISSUE THREAD

**Issue by x1n5h3n** [byt3bl33d3r/CrackMapExec#382]
**Describe the bug**
Module helpers  cannot import name 'highlight'

**To Reproduce**
1. git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec
2. cd CrackMapExec
3. sudo pip3 install -r requirements.txt
4. sudo python3 setup.py install
5. sudo crackmapexec -h

**Expected behavior**
Print help

**Screenshots**
None

**Crackmapexec info**
 - OS: Debian GNU/Linux bullseye/sid x86_64
 - Version of CME: master
- Python: 3.8.3rc1

**Additional context**
None

**Comment by mpgn** [comment]
Strange, cannot reproduce the bug

**Comment by x1n5h3n** [comment]
With the same version of python ?

**Comment by mpgn** [comment]
yes python3.8

**Comment by x1n5h3n** [comment]
I do not know thanks to what witchcraft, I no longer have the error.
Thanks @mpgn for your replies.
