### ISSUE TITLE
CME Binary : /usr/bin/env: invalid option -- 'S'

### ISSUE THREAD

**Issue by fbarre96** [byt3bl33d3r/CrackMapExec#390]
**Describe the bug**
I downloaded latest cme binary [in actions tab](https://github.com/byt3bl33d3r/CrackMapExec/actions/runs/99968531), unzipped it and executed it on an ubuntu 18.04. It outputs
` /usr/bin/env: invalid option -- 'S'`
 in the terminal

**To Reproduce**
1. Go to `https://github.com/byt3bl33d3r/CrackMapExec/actions/runs/99968531`
2. Download
3. Unzip
4. Execute cme

**Expected behavior**
Normal output of options similar to an help output

**Screenshots**
![image](https://user-images.githubusercontent.com/16072608/84409634-f8fb6a00-ac0d-11ea-9779-0e61b71d50a5.png)

**Crackmapexec info**
 - OS: Linux Mint 19.2 Tina,             Kernel: Linux 4.15.0-54-generic
 - Version of CME : v5-dev
 - Installed from latest release

**Comment by mpgn** [comment]
Try `python3 ./cme`
