### ISSUE TITLE
No Module named 'gevent.__hub_local'

### ISSUE THREAD

**Issue by ankushgoel27** [byt3bl33d3r/CrackMapExec#397]
**Describe the bug**
I downloaded the binary from the actions tab and tried running the binary on my kali Linux machine. Seeting this error.

![image](https://user-images.githubusercontent.com/10580970/86091659-e6b47380-bac9-11ea-9fb0-f5b0fbee966a.png)

**To Reproduce**
1. Download the latest cme-ubuntu binary from the actions tab
2. unzip the .zip file
3. change permissions to execute the binary.
4. ./cme

**Expected behavior**
show help message.

**Screenshots**
![image](https://user-images.githubusercontent.com/10580970/86091744-0ba8e680-baca-11ea-8aef-b284cd492f67.png)

**Crackmapexec info**
 - OS: Linux linux 5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-2kali1 (2020-06-10) x86_64 GNU/Linux
 - Version of CME: latest build from actions tab
 - Installed from apt or using latest release ? latest release

**Additional context**

**Comment by mpgn** [comment]
Hello, try with python3.7

**Comment by mpgn** [comment]
Hello, shoud be fixed with this commit https://github.com/byt3bl33d3r/CrackMapExec/commit/94074edd4438d7f089dd7c88dc8aa4c2a3720f4f

**Comment by braimee** [comment]
Hello, I can start a new issue, but @ankushgoel27 I'm wondering what was the specific fix for you?  I've downloaded this version (https://github.com/byt3bl33d3r/CrackMapExec/releases/download/v5.1.0dev/cme-ubuntu-latest.1.zip), unzipped it, run it and get a similar error.  The last line is:

````
ModuleNotFoundError: No module named 'gevent.__hub__local'
````

**Comment by mpgn** [comment]
> Hello, try with python3.7

⬆️⬆️⬆️

**Comment by ankushgoel27** [comment]
i just downloaded the latest version and it worked for me.
