### ISSUE TITLE
CrackMapExec throws an error when spidering shares with unicode filenames in it

### ISSUE THREAD

**Issue by jaredbarez** [byt3bl33d3r/CrackMapExec#4]
Just to be clear, in this case the share filename is in plain ascii and some of the files contained inside the share have unicode filenames:

![untitled](https://cloud.githubusercontent.com/assets/13761356/9377524/287492ce-471a-11e5-90f8-7e4a57424eb8.png)

**Comment by byt3bl33d3r** [comment]
@jaredbarez this should be fixed now! if not just comment below and I'll re-open the issue. thanks!

**Comment by jaredbarez** [comment]
It works now. Tnx!
