### ISSUE TITLE
cannot install cme from terminal (bash)

### ISSUE THREAD

**Issue by arielklein02** [byt3bl33d3r/CrackMapExec#402]
**Describe the bug**
I see a lot of tutorials getting CME from the apt command,
but even after I update the database, steel it wouldn't find CME.

I don't have the requierments to compile the source code to make an executable,
so in that regard I am stack, please help, thank you.

**Comment by mpgn** [comment]
Plenty solutions can be found on the documentation

https://mpgn.gitbook.io/crackmapexec/getting-started/installation
