### ISSUE TITLE
ImportError: cannot import name 'highlight' from 'helpers'

### ISSUE THREAD

**Issue by 3isenHeiM** [byt3bl33d3r/CrackMapExec#404]
**Describe the bug**
ImportError: cannot import name 'highlight' from 'helpers'

**To Reproduce**
1. Clone the repo
2. cd into it
3. Install it using pipenv as recommended by the wiki : `pipenv install`
4. Enter the pipenv : `pipenv shell`
5. Try to launch CME : `cme --help`

**Expected behavior**
CME should start and display the help

**Crackmapexec info**
 - OS: Ubuntu 20.04
 - Version of CME latest
 - Installed from apt or using latest release ? With latest release and cloned the repo. 

**Additional context**
Here is the traceback of the error : 
```
Traceback (most recent call last):
  File "/home/x/.local/bin/cme", line 5, in <module>
    from cme.crackmapexec import main
  File "/home/x/.local/lib/python3.8/site-packages/cme/crackmapexec.py", line 10, in <module>
    from cme.connector import connector
  File "/home/x/.local/lib/python3.8/site-packages/cme/connector.py", line 6, in <module>
    from cme.connection import Connection
  File "/home/x/.local/lib/python3.8/site-packages/cme/connection.py", line 3, in <module>
    from helpers import highlight
ImportError: cannot import name 'highlight' from 'helpers' (/home/x/.local/lib/python3.8/site-packages/helpers/__init__.py)
````

Python helpers version (from pip): `helpers-0.2.0`

**Comment by 3isenHeiM** [comment]
Added screenshot for reference.

![Screenshot from 2020-07-20 14-33-58](https://user-images.githubusercontent.com/26417172/87938228-85633d00-ca96-11ea-9ed5-57f9ae2b5626.png)

**Comment by m4m00th** [comment]
The same problem
- Version of CME latest
- Arch Linux x86_64 Kernel:  5.7.10-arch1-1
- via pipenv
- Python 3.8.3

**Comment by mpgn** [comment]
Sorry guys, but I cannot reproduce the error.

Also, you don't need to use pipenv for installing cme maybe that the issue.

**Comment by 3isenHeiM** [comment]
Excuse me, but quoting the installation manual : 

> It is highly reccomended to use pipenv to install CME so it's dependencies don't create conflicts with your system packages."

IMHO this is a lack of coherence. Can you reproduce the bug by installing CME inside a pipenv ?
Indeed we don't want to break other dependencies so a pipenv is mandatory.

**Comment by mpgn** [comment]
I fix the doc, should be good now 👍

**Comment by nightfuryGitHub** [comment]
same problem
