### ISSUE TITLE
Add ability to run against a colon separated file with username and password/ntlm hash pairs.

### ISSUE THREAD

**Issue by Maleick** [byt3bl33d3r/CrackMapExec#410]
## Feature Request
I would greatly appreciate the ability to provide CME a file with either:

- username:password
- username:HASH

## Detailed issue explanation
Currently, I have to run CME anywhere from ten to thirty times during the course of a penetration test and maintain separate files to verify the level of access obtained. 

I have attempted to solve this with a for loop in bash but my skills are apparently lacking.

Thank you!

**Comment by mpgn** [comment]
Simple, just put all the username in one file and all the password in another file and then

`#~ cme smb 192.168.1.101 -u user.txt -p password.txt --no-bruteforce --continue-on-succes`

https://mpgn.gitbook.io/crackmapexec/smb-protocol/password-spraying#checking-one-login-equal-one-password-using-wordlist

**Comment by Maleick** [comment]
Great. Thank you, I will give that a whirl. --no-bruteforce appears to give me what I am looking for.

**Comment by mpgn** [comment]
It's a new option from the v5 :+1:
