### ISSUE TITLE
Improve results presentation for lusers and sessions modules

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#42]
Hello @byt3bl33d3r,

It could be a nice thing to better output results for the `--lusers` and `--sessions` modules as it is not tabbed:
`print "{} {}".format(fname, yellow(luser[fname]))``
 which gives that:
```
[+] 192.168.11.136:445 DC01 Logged on users:
wkui1_logon_domain ADYOLO
wkui1_oth_domains
wkui1_username Administrator
wkui1_logon_server DC01
wkui1_logon_domain ADYOLO
wkui1_oth_domains
wkui1_username DC01$
wkui1_logon_server
wkui1_logon_domain ADYOLO
wkui1_oth_domains
wkui1_username DC01$
wkui1_logon_server
wkui1_logon_domain ADYOLO
wkui1_oth_domains
wkui1_username DC01$
wkui1_logon_server
```

Something like the share presentation, with fixed-size format could be great:
`print_att('{:>15} {:>15}'.format('SHARE', 'Permissions'))`

Cheers.

**Comment by byt3bl33d3r** [comment]
@maaaaz this has been addressed in v2.0

**Comment by byt3bl33d3r** [comment]
@maaaaz check out the new version :D

**Comment by maaaaz** [comment]
For sure, can't wait to :)
