### ISSUE TITLE
 No module named via_app_data.via_app_data

### ISSUE THREAD

**Issue by gearcapitan** [byt3bl33d3r/CrackMapExec#423]
poetry install                     
/root/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)

Python 2.7 will no longer be supported in the next feature release of Poetry (1.2).
You should consider updating your Python version to a supported one.

Note that you will still be able to manage Python 2.7 projects by using the env command.
See https://python-poetry.org/docs/managing-environments/ for more information.

The currently activated Python version 2.7.18 is not supported by the project (^3.7.0).
Trying to find and use a compatible version. 
Using python3 (3.8.6)
Creating virtualenv crackmapexec-8OyHi-4P-py3.8 in /root/.cache/pypoetry/virtualenvs

ImportError

No module named via_app_data.via_app_data

![imagen](https://user-images.githubusercontent.com/13740942/97042290-690fea00-1536-11eb-969e-745aa3cbd307.png)

**Comment by byt3bl33d3r** [comment]
This is definitely an issue with your Python environment, i'd suggest reinstalling python and making sure to follow the instructions on install Poetry to the letter.

Thanks
