### ISSUE TITLE
Kali Linux ARM 

### ISSUE THREAD

**Issue by bkeath** [byt3bl33d3r/CrackMapExec#424]
**Describe the bug**
Installing and trying to run CrackMapExec on Kali Linux on Raspberry Pi now fails.
crackmapexec
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject

**To Reproduce**
1. Install Kali Linx on Rapsberry Pi 4
2. apt install crackmapexec
3. Error binary incompatibility

**Expected behavior**

**Screenshots**

**Crackmapexec info**
 - OS: [e.g. Kali]
 - Version of CME [e.g. v5.0.2]
 - Installed from apt or using latest release ? Please try with latest release before openning an issue

**Additional context**

**Comment by mpgn** [comment]
Hello,

We don't support the installation using apt please use the following link

https://mpgn.gitbook.io/crackmapexec/getting-started/installation/installation-on-unix

**Comment by bkeath** [comment]
Thank you! Works using official install with pipx!
