### ISSUE TITLE
Windows Binary Error

### ISSUE THREAD

**Issue by Bl4d3666** [byt3bl33d3r/CrackMapExec#426]
**Describe the bug**
I am getting the following error when i try to run the windows binary. I have also copy the powersploit modules and still had the same issue. 
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Admin\.shiv\cme_51b7721208fc3d0af7e301aa9a56e1da0a38e9ec5bc08bfe8cc9ba14853ac5d1.tmp\site-packages\cme\data\powersploit\CodeExecution\Invoke-ReflectivePEInjection_Resources\DemoDLL_RemoteProcess\DemoDLL_RemoteProcess\DemoDLL_RemoteProcess.vcxproj.filters'

**To Reproduce**
python cme

**Screenshots**

**Crackmapexec info**
 - OS: Windows 10
 - Version of CME 5.1.1dev

**Comment by mpgn** [comment]
Hello, I just found a solution

exec this command in windows: `REG ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem" /v LongPathsEnabled /t REG_DWORD /d 1 /f`

![image](https://user-images.githubusercontent.com/5891788/101684477-c6201a80-3a66-11eb-819e-bbd053e41bd5.png)


Then exec the binary.

**Comment by mpgn** [comment]
Closing since no update. Feel free to reopen.

**Comment by Hackndo** [comment]
Unfortunately, this doesn't work on Windows Server 2012r2 (https://social.technet.microsoft.com/Forums/en-US/c647ddbb-ab02-4368-b73c-38bc7d5de26b/how-to-enable-paths-longer-than-260-characters-in-windows-2012-r2?forum=winserverfiles)

**Comment by ebfe90** [comment]
I think in Windows CME needs to append the prefix "\\?\" to avoid these problems.
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Comment by mpgn** [comment]
@ebfe90 good idea, I need to test this !

**Comment by mpgn** [comment]
not elegant solution

https://github.com/byt3bl33d3r/CrackMapExec/blob/master/build_collector.py#L45
