### ISSUE TITLE
Content Searching Errors When Enumerating Shares

### ISSUE THREAD

**Issue by jsarkisian** [byt3bl33d3r/CrackMapExec#430]
**Describe the bug**

When using the --content flag, the tool errors out and throws Python exceptions.

**To Reproduce**

`cme smb <IP> -u <uname> -p <pass> --spider <share> --pattern <pattern> --content`

**Expected behavior**

It searches through file contents without errors and finds what exists based on the command

**Screenshots**

![CME Errors](https://user-images.githubusercontent.com/46200265/98740671-71ab5180-2379-11eb-9e78-71682bf3cb13.png)

**Crackmapexec info**

 - OS: Kali
 - Version of CME = 5.1.1dev
 - Installed from apt or using latest release?

Installed via pipx instructions on install wiki

**Comment by thiagogilis** [comment]
I found a solution, run your command with "--continue-on-success" at the end.
Example: crackmapexec smb -u users.txt -p passwords.txt --shares 11.11.11.111 --continue-on-success

**Comment by mpgn** [comment]
Done
