### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by 0xpr0N3rd** [byt3bl33d3r/CrackMapExec#431]
Hello there, hope you are doing well.

I was trying to use CME for the first time and I'm getting the error below:

`[*] Generating SSL certificate
Segmentation fault`

So far I tried the solutions that you've recommended [here](https://github.com/byt3bl33d3r/CrackMapExec/issues/122), including reinstalling OpenSSL (3.0.0-alpha-8). 

When I try to execute the code that you give in below:

`openssl req -new -x509 -keyout ~/.cme/cme.pem -out ~/.cme/cme.pem -days 365 -nodes -subj "/C=US"`

I'm getting `req: Use -help for summary.`

I'm currently on `5.8.0-kali3-amd64 #1 SMP Debian 5.8.14-1kali1 (2020-10-13)`, can you help me out?

**Comment by 0xpr0N3rd** [comment]
Hello? @byt3bl33d3r

**Comment by mpgn** [comment]
https://github.com/byt3bl33d3r/CrackMapExec/issues/122#issuecomment-237045007

**Comment by mpgn** [comment]
Just tested today, make sure you update to latest version 5.1.3

![image](https://user-images.githubusercontent.com/5891788/99881782-18b2a780-2c1c-11eb-8bae-a6e9637954f8.png)
