### ISSUE TITLE
Failed loading module at /usr/lib/python3/dist-packages/cme/modules/slinky.py: No module named 'pylnk3'

### ISSUE THREAD

**Issue by InfoSecMalang** [byt3bl33d3r/CrackMapExec#436]
##  Command string used
crackmapexec smb 192.168.0.17 -u USER -p PASS -M Get-ComputerDetails
crackmapexec smb 192.168.0.17 -u USER -p PASS -M enum_chrome
crackmapexec smb 192.168.0.17 -u USER -p PASS -M lsassy

## CME Version (cme --version)
5.1.3dev

## OS
Kali

## Target OS
Windows 7

## Detailed issue explanation
For most smb modules it display error
`[-] Failed loading module at /usr/lib/python3/dist-packages/cme/modules/slinky.py: No module named 'pylnk3'`

where as i have pylnk3 installed for both python2 and python3.

I have python3 as my default python.

![image](https://user-images.githubusercontent.com/6963584/100491907-8451b480-30f5-11eb-8e3d-0451a5266ac2.png)

Thanks!

**Comment by bucky67gto** [comment]
I see you closed it, what was the fix?

**Comment by bucky67gto** [comment]
nevermind

pip install --upgrade pylnk3
