### ISSUE TITLE
Scanning a Responder SMB Server breaks cmedb hosts functionality.

### ISSUE THREAD

**Issue by sebrink** [byt3bl33d3r/CrackMapExec#439]
**Describe the bug**
CME is unable to list the hosts table when it has scanned Responder, due to the strange response Responder gives.

**To Reproduce**
1. Run Responder in one window.
2. Run `cme smb $ResponderIP`
3. Go into cmedb and switch to the smb protocol.
4. Run `export hosts tmp`, this will work.
5. Run the `hosts` command, this will fail.

**Expected behavior**
The database will display all hosts within the database.

**Screenshots**
![Screen Shot 2020-12-10 at 7 57 45 AM](https://user-images.githubusercontent.com/29733832/101789401-e4b5fe00-3ac6-11eb-9713-985fd7e96aae.png)

**Crackmapexec info**
 - OS: Kali
 - Version of CME v5.1.4dev
 - Installed from apt in Kali repos.

**Additional context**
I would assume this has something to do with the null bytes that are sent back to CME in Responder's SMB hostname, if you look in the database in sqlite3, it only shows the name as `W`

Content of the computers table in cmedb
```
~/.cme/workspaces/default$ sqlite3 smb.db
SQLite version 3.32.3 2020-06-18 14:00:33
Enter ".help" for usage hints.
sqlite> .tables
admin_relations     group_relations     loggedin_relations
computers           groups              users
sqlite> select * from computers;
1|10.0.2.15|SMB12|SMB12|W|
```

**Comment by mpgn** [comment]
Nice catch !

**Comment by mpgn** [comment]
Done
