### ISSUE TITLE
cme not reading files passed as -H

### ISSUE THREAD

**Issue by arty-hlr** [byt3bl33d3r/CrackMapExec#440]
**Describe the bug**
Crackmapexec is passing `_io.TextIOWrapper` instead of `string` to `os.path.exists(ntlm_hash)`.

**To Reproduce**
```
ls -l
total 16
-rw-r--r-- 1 florian florian 7392 Dec 11 17:52 hashes.txt
-rw-r--r-- 1 florian florian 4105 Dec 11 17:51 users.txt
```

```
cme smb -u users.txt -H hashes.txt 172.16.2.102
ProxyChains-3.1 (http://proxychains.sf.net)
Traceback (most recent call last):
  File "/home/florian/.local/bin/cme", line 8, in <module>
    sys.exit(main())
  File "/home/florian/.local/pipx/venvs/crackmapexec/lib/python3.8/site-packages/cme/crackmapexec.py", line 83, in main
    if os.path.exists(ntlm_hash):
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not _io.TextIOWrapper
```

**Expected behavior**
Crackmapexec should read the contents of hashes.txt

**Crackmapexec info**
 - OS: Linux parrot 5.8.0-1parrot1-amd64 #1 SMP Debian 5.8.7-1parrot1 (2020-09-14) x86_64 GNU/Linux
 - Version of CME:  5.1.1dev
 - Installed from apt or using latest release ? Installed from pipx

**Comment by mpgn** [comment]
Try with full path of the file.

**Comment by mpgn** [comment]
Now you know :) 

`cme <proto> <ip> -<options>`

**Comment by arty-hlr** [comment]
Sorry, how is this fixed? At least change the help message to reflect your last message, my command was straight out of it with the positional parameter of the target at the end, and didn't work, does that seem like normal behavior to you?
