### ISSUE TITLE
SyntaxWarning error messages.

### ISSUE THREAD

**Issue by sakas23** [byt3bl33d3r/CrackMapExec#443]
Hello community,

I need some help with some errors i faced while trying to use crackmapexec.

Below i a screenshot.
![crackmaperror](https://user-images.githubusercontent.com/57067833/102691678-e7c39380-4216-11eb-91fd-eb731fd18c95.png)

Thanks in advance.

**Comment by mpgn** [comment]
It's linked to your impacket version, check if you are using the version v.0.9.22 otherwise you need to update it.
Nevertheless, these warnings will only show up one time so it's not a big deal 👍

**Comment by sakas23** [comment]
> 
> 
> It's linked to your impacket version, check if you are using the version v.0.9.22 otherwise you need to update it.
> Nevertheless, these warnings will only show up one time so it's not a big deal 👍

Hello mpgn,

Thank you for your time and reply.

I just want to remove them, as i am in a learning process and i would like to do as much as possible to become familiar with many things.

How can i update it?

**Comment by tirkarthi** [comment]
Fixed in https://github.com/SecureAuthCorp/impacket/commit/ef67d7aff09ac646479f477da3c24d2463cb6b72
