### ISSUE TITLE
Kerberos ticket loading support on Windows

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#45]
Hello @byt3bl33d3r,

As I'm going through the new features you added and how could they be used from Windows hosts, I would like to know if you wanted to add a Windows support for the kerberos ticket loading (`--kerb` and `-k`).
The thing is you actually rely on impacket's implementation which loads [`$KRB5CCNAME` env variable](https://github.com/CoreSecurity/impacket/blob/b9b85004e17819fdf302e1177a46c791f09c5c81/impacket/krb5/ccache.py#L503) to find tickets, which is obviously related to the Unix world.

So my point is to **allow a user who whould have grabbed tickets with mimikatz** to be able to replay them through crackmapexecwin. [That link](http://carnal0wnage.attackresearch.com/2015/09/ways-to-load-kerberos-tickets.html) gives the modus operandi: 
* The attacker should first convert it with kirbikator 
* The attacker should then use a Unix/linux client to load it: **this is the step I want to avoid as I'd like to  load it from Windows.**

By quickly looking at [impacket code](https://github.com/CoreSecurity/impacket/blob/b9b85004e17819fdf302e1177a46c791f09c5c81/impacket/krb5/ccache.py#L503), it could be possible to achieve this by calling `CCache.loadFile()` with **a custom Windows path (user specified)**.
What do you think about ?

I'm aware that this might rather be an impacket issue, so I'll also post it on [their github section](https://github.com/CoreSecurity/impacket/issues/113)

Cheers.

**Comment by byt3bl33d3r** [comment]
Closing since I've decided I'm not going to be supporting windows for a multitude of reasons
