### ISSUE TITLE
Improve output

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#47]
Hello @byt3bl33d3r,

For the results presentation, could you insert a empty line between hosts in order to make it clearer ?

Cheers.

**Comment by byt3bl33d3r** [comment]
@maaaaz I'm going to have to overhaul how things get printed to stdout anyway, don't know if just a newline is the best way to go though

**Comment by byt3bl33d3r** [comment]
Reminder for myself: add the targets hostname to the line where the IP is printed

**Comment by byt3bl33d3r** [comment]
Think I came up with a better option for displaying output:
```(date)(time)(ip)(hostname) [*] status line```
