### ISSUE TITLE
Error starting SMB server on port 445: the port is already in use On multiple targets

### ISSUE THREAD

**Issue by shoxxdj** [byt3bl33d3r/CrackMapExec#472]
Hey ! 

I am trying to create my first ever module. 
Inspired by the wireless one, I would like to perform a simple Powershell command and deal with the output in py. 
Up to this it works, however I have some trouble when trying to use my module on multiple targets.
The following error occurs : 
`Error starting SMB server on port 445: the port is already in use`

I guess that the SMB connection is not closed as it should be. Is it my job to close it ? If true, how ? :) 
My module looks like : 
```
class CMEModule:
def options(self, context, module_options):
        '''
        ''' 
def on_login(self, context, connection):
  command = 'powershell.exe -c "dosomething" '
  p = connection.execute(command, True)
  context.log.info(p)
```
( on_login is the only method I use ) 

Thanks for help ! 
Version: 5.1.6dev

**Comment by mpgn** [comment]
If this is SMB protocol you need to use on_admin_login to exec command

**Comment by mpgn** [comment]
closing since not activity
