### ISSUE TITLE
Missing hidden import for impacket.ldap in the spec file

### ISSUE THREAD

**Issue by Qazeer** [byt3bl33d3r/CrackMapExec#475]
The `PythonInstaller` spec file `crackmapexec.spec` is missing an hidden import for `impacket.ldap`.

Compiling a Windows standalone version of `cme` using the current spec file result in the following error:

![image](https://user-images.githubusercontent.com/5614972/125165165-18105680-e196-11eb-9359-14d7c7281c39.png)

After adding `impacket.ldap.ldap` in the spec file hidden imports, the standalone build works properly:
![image](https://user-images.githubusercontent.com/5614972/125165481-67a35200-e197-11eb-9d05-5da417461ca7.png)

Quick fix not worthy of a PR imo but I can do one if needed.

**Comment by mpgn** [comment]
Can you submit a PR ? :)

**Comment by Qazeer** [comment]
Yes, will do!

I have also noticed that adding the following custom `PyInstaller` hook for lsassy fixes the error `The 'lsassy' distribution was not found and is required by the application` (referenced here: #456) whenever building standalone binaries:

```
# -*- coding:utf-8 -*-

from PyInstaller.utils.hooks import collect_all
datas, binaries, hiddenimports = collect_all("lsassy")
```

The `hookspath` argument in the `PyInstaller` spec file should point to the folder containing the hook file. I have scripted that part [here](https://github.com/Qazeer/OffensivePythonPipeline/blob/main/build_scripts/build_windows_crackmapexec.ps1). 

If the fix seems ok to you, any preference on how to implement it (a new file in the main folder / a dedicated folder)?

**Comment by mpgn** [comment]
Hello @Qazeer you have time to submit a PR ? Otherwise I will do it in the following days :)
