### ISSUE TITLE
Windows CME not recognizing Domain Admins properly?

### ISSUE THREAD

**Issue by braimee** [byt3bl33d3r/CrackMapExec#480]
## Steps to reproduce

1. Install Python 3.8
2. Download CME Windows binary
3. Promote general user to DA.
4. Run CME against the DC using general user creds - when I do that, CME only recognizes the account as valid but NOT `Pwn3d!`

## Command string used
`python cme smb IP.OF.DOMAIN.CONTROLLER -u myuser -p mypass`

## CME Version (cme --version)
5.1.1dev

## OS
Windows 10 with latest updates

## Target OS
Server 2019 domain controller

## Detailed issue explanation
I've only been using the Windows binary for a bit but think I found an issue with CME reporting Domain Admins correctly.  If I run cme with the domain Administrator account and valid password, it does indicate `Pwn3d!`, but if I promote a general user to DA, CME seems to only recognize it as a regular account.

Here's me putting `student15` in the Domain Admins group:

![image](https://user-images.githubusercontent.com/17596787/129068641-5bcb68fa-de63-4f33-8e43-dd5e9496d8d1.png)

And then validating the creds are good with CME.  Note that the domain Administrator account shows `Pwn3d` but not `student15`:

![image](https://user-images.githubusercontent.com/17596787/129068905-758ddfa4-f871-4e8a-b837-740996fa59cf.png)

Am I missing something obvious?

**Comment by mpgn** [comment]
I've try multiple scenario but cannot reproduce this bug, can you check it again ?

**Comment by braimee** [comment]
hahhaah I love the label you gave this issue.  Yeah I'm just rebuilding the lab this week and will give it another go and report back.

**Comment by braimee** [comment]
I can't recreate at this time, will close out, thanks.
