### ISSUE TITLE
Installing Crackmapexec corrupts OS

### ISSUE THREAD

**Issue by I7Z3R0** [byt3bl33d3r/CrackMapExec#481]
## Steps to reproduce

1. Tried to install crackmapexec in ubuntu via the apt repository
2. . After the installation of cme and crackmapexec the operating system corrupts and gives me an error "Failed to start load Apparmor profiles".

## Command string used -- sudo apt install cme and 
![CME_error](https://user-images.githubusercontent.com/75982271/129457011-512fe2ef-1849-4888-bd11-1bd55ff54ce0.png)
sudo apt install crackmapexec

## Detailed issue explanation:

I am using ubuntu for learning pentest. I tried to install crackmapexec and cme vial the apt repository which was successful with few warning when i tried to initiate the crackmapexec command. After sometime I got the authentication error due to which i restarted the guest and after which i am getting an error as "Failed to start load Apparmor profiles". I am not sure if i am doing anything wrong.

**Comment by mpgn** [comment]
Apparmor has nothing to do with cme, you must have done something else ;)

**Comment by I7Z3R0** [comment]
Nope i restored the previous snapshot and did install sudo apt install but the OS failed all the times...
