### ISSUE TITLE
CrackMapExec Ignores --local-auth Switch

### ISSUE THREAD

**Issue by Theory5** [byt3bl33d3r/CrackMapExec#490]
Crackmapexec ignores the local auth switch on my Kali instance (5.0.2dev). Doesn't matter where I put it, it attempts to use the domain for any authentication. 

Only when I used the -d switch with . will it perform local auth.

What do you need from me in order to investigate this? Thanks!

**Comment by mpgn** [comment]
Hello,

Try with lastest version :)
