### ISSUE TITLE
Add the latest version of LSASSY to CME

### ISSUE THREAD

**Issue by nullenc0de** [byt3bl33d3r/CrackMapExec#503]
This is more of an enhancement. The latest version of LSASSY automatically bypass LSASS protections. Currently, CME does not do this with the current LSASSY module. I know it's possible to import it yourself. But thought it would be helpful to add this "out of the box" feature.

**Comment by garilla2** [comment]
ERROR: Cannot install -r requirements-dev.txt (line 30) and pypykatz==0.4.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pypykatz==0.4.3
    lsassy 3.0.0 depends on pypykatz>=0.4.8

**Comment by mpgn** [comment]
no info, closing
