### ISSUE TITLE
Failure to parse CIDR notation as range

### ISSUE THREAD

**Issue by capnkrunchy** [byt3bl33d3r/CrackMapExec#508]
**Describe the bug**
CME 5.1.7dev attempts to resolve a CIDR range (ex. 192.168.0.0/24) as a hostname and fails to perform any action. The issue is not present in 5.1.1dev.

**To Reproduce**
1. `cme --verbose smb 192.168.0.0/24`
2. See error `DEBUG Error resolving hostname 192.168.0.0/24: [Errno -2] Name or service not known`

**Expected behavior**
CME should parse the CIDR notation as a range and enumerate SMB hosts within the range.

**Screenshots**
![image](https://user-images.githubusercontent.com/47148444/142024117-06435b1f-fda6-4be1-b007-376aa22f1705.png)

**Crackmapexec info**
 - OS: Kali 
 - Version: 5.1.7dev
 - Using latest release from pip.

**Additional context**
Ranges in dash notation (192.168.0.0-255) work as expected.

**Comment by mpgn** [comment]
Fixed! :)

`pip3 install --upgrade crackmapexec`
