### ISSUE TITLE
problem install

### ISSUE THREAD

**Issue by tfmarques23** [byt3bl33d3r/CrackMapExec#511]
**Describe the bug**
error installing 

"  Because crackmapexec depends on lsassy (>=3.0.0) which doesn't match any versions, version solving failed."

**To Reproduce**
1. install requeriments
2. install poetry (pip3 install poetry)
Poetry version 1.1.12
python3 --version (Python 3.9.9)
lsassy --version (lsassy (version 3.0.3))

**Screenshots**
![image](https://user-images.githubusercontent.com/92591638/144616929-6f025f39-a382-48a9-87d3-a50bbfddd613.png)

**Comment by tfmarques23** [comment]
![image](https://user-images.githubusercontent.com/92591638/144618798-12d3cc03-f61e-4da8-98a5-87ec46f5d92d.png)
can you upgrade for new version of pypykatz?

**Comment by kavishkagihan** [comment]
I am having the same issue.

**Comment by SRZEUS1990** [comment]
The following steps worked for me on Ubuntu 29.04 LTS but Cannot install in Kali manually then again the tool comes pre-installed with newer Kali

```
❯❯❯ sudo apt install -y libssl-dev libffi-dev python-dev-is-python3 build-essential
❯❯❯ cd CrackMapExec
❯❯❯ pip3 install -r requirements-dev.txt
❯❯❯ cd cme
❯❯❯ ./crackmapexec.py -h 
```

**Comment by mpgn** [comment]
@tfmarques23 can you try `poetry install` and `poetry update` after clonning ?

**Comment by mpgn** [comment]
no update, closing
