### ISSUE TITLE
  Do you support Apple system user installation?

### ISSUE THREAD

**Issue by Mulburryrelic63** [byt3bl33d3r/CrackMapExec#515]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crackmapexec info**
 - OS: [e.g. Kali]
 - Version of CME [e.g. v5.0.2]
 - Installed from apt or using latest release ? Please try with latest release before openning an issue

**Additional context**

**Comment by mpgn** [comment]
Should work yep
