### ISSUE TITLE
WinRm uses port 445 to map systems

### ISSUE THREAD

**Issue by Tomerkat** [byt3bl33d3r/CrackMapExec#517]
**Describe the bug**
`crackmapexec winrm <ip>`  uses port 445 (SMB) to get host data.

**To Reproduce**
`crackmapexec winrm <ip>`

**Expected behavior**
The WinRm module should only use WinRM ports (5985,5986).

**Screenshots**
![Screenshot 2022-01-16 122411](https://user-images.githubusercontent.com/41906630/149656113-2e48b9e0-41df-4995-af0b-35704cd7074c.png)

**Crackmapexec info**
 - OS: Kali 2021.4
 - CME Version 5.1.7dev
 - Installed from apt

**Comment by mpgn** [comment]
Hello,

Check this https://mpgn.gitbook.io/crackmapexec/winrm-protocol/authentication
