### ISSUE TITLE
create a donation banner of the first run

### ISSUE THREAD

**Issue by blshkv** [byt3bl33d3r/CrackMapExec#520]
Hi there, thanks for the wonderful project!

As we all know, not many companies are donating to opensource projects and that might kill then eventually.
You can come up with a sponsorware version which is one way, but some pentesters might never read a website (https://mpgn.gitbook.io/crackmapexec/news-2022/major-release-for-crackmapexec) and just use a pre-installed version with their favourite Linux distribution.

So I suggest creating a nice banner which would be displayed on the first run and user would need to type something long like:
```Yes, I'm aware```

**Comment by mpgn** [comment]
Hi,
I've added a link to porchetta.industries in the banner https://github.com/byt3bl33d3r/CrackMapExec/commit/63db136f2be8385644d2f79206e2c7ccb5938f55
