### ISSUE TITLE
BloodHound Error!

### ISSUE THREAD

**Issue by k4n4n** [byt3bl33d3r/CrackMapExec#521]
**Describe the bug**
I have installed version 5.2.2 of CME, but when executing the smb modules for detection of vulnerabilities like zerologon, petitpotam... crackmapexec it fails and it seems to be an error in the BloodHound component

**To Reproduce**
1. Go to 'Terminal in Kali Linux'
2. Click on 'crackmapexec smb IP address -u 'Username' -p 'Password' -M module'
3. Scroll down to 'results in terminal'

**Expected behavior**
I am checking the use of the modules on an active directory vulnerable to all possible security flaws in a local environment, the modules should work correctly.

**Screenshots**
![CME](https://user-images.githubusercontent.com/43685859/150199283-2a4d9d34-9602-4289-ae09-4d521e06fcfd.png)

**Crackmapexec info**
 - OS: [Kali Linux last release]
 - Version of CME [e.g. v5.2.2]
 - Installed from Python Package (https://mpgn.gitbook.io/crackmapexec/getting-started/installation/installation-on-unix).

**Additional context**
All dependencies are correctly installed

**Comment by mpgn** [comment]
Duplicate of #519
