### ISSUE TITLE
Unable to run handlekatz or nanodump

### ISSUE THREAD

**Issue by braimee** [byt3bl33d3r/CrackMapExec#522]
## Steps to reproduce

1. Download standalone CME binary from Github
2. Run `cme smb VICTIM -u user -p pass -M nanodump` or `-M handlekatz`

## Command string used
Run `cme smb VICTIM -u user -p pass -M nanodump` or `-M handlekatz`

## CME Version (cme --version)
5.2.2

## OS
Kali - latest

## Target OS
Windows 10 build 17134

## Detailed issue explanation
When i run either of these modules, I get an error saying `/tmp/shared/nano.exe` or `/tmp/shared/handlekatz.exe` doesn't exist.

I deleted the `cme.conf` file per [this thread](https://github.com/byt3bl33d3r/CrackMapExec/issues/519) and thought I was in the clear but apparently not.

**Comment by braimee** [comment]
Ooops, I think I missed the obvious here in that the handlekatz and nano executables need to be built and put on the Kali box manually.  I'll verify later this week and update/close as appropriate.

**Comment by coffeegist** [comment]
Just create the /tmp/shared folder before running CME and you'll be good. It has an embedded version

**Comment by braimee** [comment]
Thank you @coffeegist that worked a treat!

**Comment by shaaati** [comment]
Shouldn't CME maybe check for existence of the path and create it, instead of failing? Since the embedded exe is written to the disk anyway there shouldn't be a problem in creating the path first if it doesn't exist.
