### ISSUE TITLE
Feature request: Don't show supplied credentials in the cme output

### ISSUE THREAD

**Issue by edermi** [byt3bl33d3r/CrackMapExec#523]
## Steps to reproduce

Use CrackMapExec to perform any authenticated action.

## Command string used

Not relevant.

## CME verbose output (using the --verbose flag)

Not relevant

## CME Version (cme --version)

5.2.2dev

## OS

Kali latest

## Target OS

Windows

## Detailed issue explanation

The log line printed on each authentication attempt contains full credentials of the user. This is cumbersome to censor for inclusion in reports. It would be nice, if the output of CrackMapExec would not show sensitive information that has been provided in the command line.

**Comment by mpgn** [comment]
Good idea ! I will do it :)
