### ISSUE TITLE
Unexpected error with Neo4J

### ISSUE THREAD

**Issue by snovvcrash** [byt3bl33d3r/CrackMapExec#529]
**Describe the bug**
When BloodHound is set to `True` in cme.conf, there's an unidentified error with Neo4J while using any valid creds (and any protocol).

**To Reproduce**
`cme smb <ANY_HOST> -u <ANY_USER> -p <ANY_PASSWD>`

**Expected behavior**
Credentials should be marked as owned in BloodHound.

**Screenshots**
![Screenshots](https://user-images.githubusercontent.com/23141800/152038592-8e3095eb-0742-4446-914d-fc5606ae6d40.png)

**Crackmapexec info**
 - OS: Kali 2021.4
 - Version of CME: 5.2.3
 - Installed via pipx using latest release

**Comment by mpgn** [comment]
Hello,

Can you run with flag --verbose ?

cme --verbose smb ...

**Comment by snovvcrash** [comment]
Hi @mpgn!

Thanks for the feedback.

I suppose, this is the part of `--verbose` that refers to Neo4j:

![1](https://user-images.githubusercontent.com/23141800/152165848-37313d0d-a224-4a49-98da-995e9c995c8c.png)

**Comment by mpgn** [comment]
Indeed ! That because the user is not found on your neo4j database  :)

Can you double check the user exist, the one you blured on screenshot.

**Comment by snovvcrash** [comment]
Yep, that's right - I was trying to reproduce it with a computer account (my bad)...

But anyways, when I'm trying to set a domain admin **user** account as owned, there's no error message but the account is not set as owned in the DB either.

I found a reason for it: [here](https://github.com/byt3bl33d3r/CrackMapExec/blob/83cb8ef8527d7715b2679e4e6f47d5d794fa1700/cme/helpers/bloodhound.py#L23) the condition checks whether `c.owned` is `False` but in my case this `owned` property is **null** for every collected account.

So if I replace `False` with `None` it works as expected!

**Comment by mpgn** [comment]
We could also add the owned on computer accounts 😀

**Comment by snovvcrash** [comment]
> We could also add the owned on computer accounts 😀

You mean with bh_owned.py module or by modifying the bloodhound.py helper? 🤔

I also think of editing the IF condition mentioned above to support null-valued owned property. What’s your thoughts on it?

**Comment by Cyb3rC3lt** [comment]
Apologies I know this was closed but I am getting a similar issue and the user does exist in Neo4J as shown, any ideas?

![image](https://user-images.githubusercontent.com/33097451/190355044-95de1224-5c86-4da7-a592-f3afdd468cfa.png)

![image](https://user-images.githubusercontent.com/33097451/190355207-513ed260-618d-408e-87e8-1cdba6c37ab9.png)
