### ISSUE TITLE
configparser.NoSectionError: No section: 'BloodHound'

### ISSUE THREAD

**Issue by aimanpoji** [byt3bl33d3r/CrackMapExec#543]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/34196370/155836788-590e98d6-541e-4394-9465-84e5e6dbdef0.png">

anyone know how to fix this error?

**Comment by mpgn** [comment]
#519

**Comment by aimanpoji** [comment]
> #519

thanks!
