### ISSUE TITLE
STATUS_LOGON_FAILURE true cred

### ISSUE THREAD

**Issue by anasbousselham** [byt3bl33d3r/CrackMapExec#544]
Hi,
Trying to connect to my target with a true creds `crackmapexec smb 192.168.1.10 -u 'user1' -p 'pass123'` and I'm getting STATUS_LOGON_FAILURE.
However with smbclient `smbclient -L  192.168.1.10  -U "user1%pass123" ` with the same creds it works fine. I'm confused..

**Comment by mpgn** [comment]
use the flag `--local-auth`

**Comment by mpgn** [comment]
no answer, closing
