### ISSUE TITLE
AttributeError: 'SMB' object has no attribute '_Connection'

### ISSUE THREAD

**Issue by Marcuccio** [byt3bl33d3r/CrackMapExec#551]
**Describe the bug**
Using SMB protocoll throws an unhandled exception 

**To Reproduce**
crackmapexec smb ../scope/private-ip.txt -u [REDACTED] -p '[REDACTED]' -d [REDACTED].local --shares

**Expected behavior**
It should not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/9968234/157653073-2c2e3974-0004-40dd-971b-578fb7e24eee.png)

**Crackmapexec info**
 - OS: Kali
 - Version of CME v5.2.2
 - Installed from apt or using latest release ? YES

**Comment by Gianfrancoalongi** [comment]
My pull request fixes this and two other crashes #560 (no _Connection crash, NetBIOSTimeout crash, UnsupportedFeature-crash)
