### ISSUE TITLE
Maximum length and server response error using various modules

### ISSUE THREAD

**Issue by Francisco4fonso** [byt3bl33d3r/CrackMapExec#554]
Hello all,

 When I run modules that require a big base64 encoded Powershell command line I usually get the following error:

![image](https://user-images.githubusercontent.com/39593756/159021789-01a77146-24fb-4b8a-b8eb-e27fb591405a.png)

 Sometimes with some modules it gets past this error and with some other modules I've never seen it get past it.

 In the occasions that the error mentioned above does not occur the powershell will execute and attempt to fetch a .ps1 script from a web server hosted by CME himself. But when the windows target makes the request to CME a python error is raised.
 This error can also be reproduced with a wget execution on my kali machine.
 
![image](https://user-images.githubusercontent.com/39593756/159024060-4757432d-5520-466f-924f-94e739477038.png)

Tested against: Microsoft Windows 7 Enterprise with firewall and windows defender both disabled
Tested the following modules using SMB only:
enum_chrome
get_keystrokes (server error)
get_netdomaincontroller (length error)
get_netrdpsession (length error)
get_timedscreenshot (server error)

 Can anyone provide insight on this issue ?

**Comment by Bobby87654** [comment]
Is there a solution to this problem?

**Comment by Francisco4fonso** [comment]
Not that I know of

**Comment by mpgn** [comment]
modules removed
