### ISSUE TITLE
CrackMapExec does not handle non-ascii characters properly

### ISSUE THREAD

**Issue by executionByFork** [byt3bl33d3r/CrackMapExec#562]
**Describe the bug**
crackmapexec smb with the --gen-relay-list flag crashes against a host with non-ascii characters in the name

**To Reproduce**
1. Start up a Responder instance
2. `crackmapexec smb <ResponderIP> --gen-relay-list smb_relay_list`
3. Scream at the horrific sight of an uncaught stacktrace
![cme_nonascii_error](https://user-images.githubusercontent.com/20407804/162045139-cc0ef07c-23f2-4147-855f-c873a7b925c5.png)

**Expected behavior**
crackmapexec should not stacktrace. It prevents writing to the relay list file.

**Crackmapexec info**
 - OS: Kali
 - Version 5.2.2
 - Installed from apt

**Additional context**
This seems to be the same issue as #449 and #439 just in another part of the code.
Considering the aforementioned issues have been patched and resolved, this probably a wider spread issue that may exist in other parts of the tool as well.

**Comment by mpgn** [comment]
Fixed by #560
