### ISSUE TITLE
Valid credentials coming up as Invalid for SMB

### ISSUE THREAD

**Issue by 0xGreen** [byt3bl33d3r/CrackMapExec#583]
**Describe the bug**
Doing a Vulnhub box (https://www.vulnhub.com/entry/digitalworldlocal-bravery,281/) and crackmapexec showing the valid combination as invalid, however patator and smbmap works absolutely find.

**To Reproduce**
1. Simply download the vm from vulnhub and try running the tool
2. Screenshot attached as well

**Expected behavior**
Should show as valid credential

**Crackmapexec info**
 - OS: Kali 
 - Version of CME: 5.2.2 (The Dark Knight)
 - Installed from apt or using latest release ? Installed from apt. (Tried the latest release as well, same behaviour)

**Additional context**
1. Victim operating system is Centos.

![cme](https://user-images.githubusercontent.com/6963584/174418270-010901e7-480c-42e6-8943-86f63a3d731a.png)

**Comment by mpgn** [comment]
Can you try with option `--local-auth` at the end of the command ?

**Comment by 0xGreen** [comment]
Hey, Thank you!! Yes it did work with --local-auth. Bad on my part, i should have tried that, but i like always i forgot that option :)

**Comment by mpgn** [comment]
No problem :)
