### ISSUE TITLE
 Installing aardwolf (0.0.8): Failed on MACOS

### ISSUE THREAD

**Issue by metasecdev** [byt3bl33d3r/CrackMapExec#585]
# sudo poetry install                                                                
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

 Installing aardwolf (0.0.8): Failed

  RuntimeError

  Unable to find installation candidates for aardwolf (0.0.8)

  at ~/opt/anaconda3/lib/python3.8/site-packages/poetry/installation/chooser.py:72 in choose_for
       68│
       69│             links.append(link)
       70│
       71│         if not links:
    →72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│
       76│         # Get the best link

**Comment by mpgn** [comment]
Yep this is a well known issue, their is not aardwolf package for mac yet https://pypi.org/project/aardwolf/#files

**Comment by lesydimitri** [comment]
https://github.com/skelsec/aardwolf/issues/2

@skelsec just released a source distribution, so installing under macOS through pip is now possible 😎

**Comment by mpgn** [comment]
`pip download --no-binary aardwolf aardwolf`
