### ISSUE TITLE
No module named cme

### ISSUE THREAD

**Issue by jrod1481** [byt3bl33d3r/CrackMapExec#588]
Hello,

I am trying to install crackmapexec to RHEL 8, which I'm realizing is a bit of a pain. I end up with this error output:

Traceback (most recent call last):
  File "./crackmapexec.py", line 3, in <module>
    from cme.logger import setup_logger, setup_debug_logger, CMEAdapter
ModuleNotFoundError: No module named 'cme'
[scanner@e4gp1lnfpsapp01 cme]$ sudo python3 crackmapexec.py 
Traceback (most recent call last):
  File "crackmapexec.py", line 3, in <module>
    from cme.logger import setup_logger, setup_debug_logger, CMEAdapter
ModuleNotFoundError: No module named 'cme'

I have pip3 installed cme and yet am not able to use crackmapexec. Is there something that I am missing here?

Thank you

**Comment by mpgn** [comment]
Hello,

Try with poetry, the docker image etc there are plenty other way to run cme :)
