### ISSUE TITLE
SyntaxWarning

### ISSUE THREAD

**Issue by klint-k** [byt3bl33d3r/CrackMapExec#594]
**Describe the bug**
crackmapexec         
[*] First time use detected
[*] Creating home directory structure
[*] Creating default workspace
[*] Initializing LDAP protocol database
[*] Initializing WINRM protocol database
[*] Initializing SMB protocol database
[*] Initializing SSH protocol database
[*] Initializing MSSQL protocol database
[*] Copying default configuration file
[*] Generating SSL certificate
/usr/lib/python3/dist-packages/pywerview/requester.py:144: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if result['type'] is not 'searchResEntry':
usage: crackmapexec [-h] [-t THREADS] [--timeout TIMEOUT] [--jitter INTERVAL] [--darrell] [--verbose]
                    {ldap,winrm,smb,ssh,mssql} ...

**To Reproduce**
the first time running    not sudo

**Expected behavior**
will it cause me more errors?

**Crackmapexec info**
 - OS: kali
 - Version of CME:   Version : 5.2.2

**Comment by mpgn** [comment]
It's just a warning, no problemo :)
