### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by byt3bl33d3r** [byt3bl33d3r/CrackMapExec#60]
So everyone can add their own attacks! Not really sure how to implement this currently

**Comment by maaaaz** [comment]
Following the current **"All-in-Powershell"** trend, the plugin module could be something allowing the user to **serve a powershell script** of his own and execute it (functions or the whole script) remotely and automatically.

**Comment by acaetano** [comment]
Maybe you could use the same idea implemented by MWR's drozer: [loader.py](https://github.com/mwrlabs/drozer/blob/develop/src/drozer/modules/loader.py)

**Comment by byt3bl33d3r** [comment]
Done in v3.0
