### ISSUE TITLE
Ability to serve powershell scripts from a third-party webserver

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#65]
Hello @byt3bl33d3r,

As an **enhancement** to the current mechanism to serve the different powershell scripts to targets, I thought that I would be cool to give users the ability to **specify a third-party webserver** instead of the current local webserver.
So far I never needed that feature but it might be **needed one day in networks having strong segmentation**, something where you the egress flow from the target to you is not allowed.

Happy new year and cheers !

**Comment by byt3bl33d3r** [comment]
I really don't see a use case scenario for this, however i have some features in mind that might help deal with network segmentation ;) 
Cheers
