### ISSUE TITLE
Improve usage documentation with examples 

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#68]
Hello @byt3bl33d3r,

I thought it could be handy to document accepted formats and/or example for most of available options.

For instance, it is not obvious which is the correct format for the PtH `-H` option: for CrackMapExec it is `lmhash:nthash` (it may varies for other common tools). The colon is important and shouldn't be forgotten even if the user only has a lmhash or nthash. 
In that case I propose to go:
* from this
"`  -H HASH               NTLM hash(es) or file containing NTLM hashes`"
* to that
"`  -H HASH               NTLM hash(es) or file containing NTLM hashes (-H <lmhash>:<nthash>)`"

Same approach for common option such as `-k`.
Cheers

**Comment by byt3bl33d3r** [comment]
@maaaaz think the format is explicit enough in the wiki, let me know otherwise
