### ISSUE TITLE
Nmap-like support for inline target definition

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#71]
@byt3bl33d3r,

CME already supports CIDR but it would be good to implement the same support as Nmap for multiple targets definition:
```
Nmap 7.01 ( https://nmap.org )
Usage: nmap [Scan Type(s)] [Options] {target specification}
TARGET SPECIFICATION:
  Can pass hostnames, IP addresses, networks, etc.
  Ex: scanme.nmap.org, microsoft.com/24, 192.168.0.1; 10.0.0-255.1-254
```
Like this would be allowed 
```
$ python crackmapexec.py 192.168.11.144/24 192.11.123.45 blablahostname
```
So you basically have to iterate through sys.argv parameters that are not options.

Cheers.

**Comment by byt3bl33d3r** [comment]
heya @maaaaz so this is sorta already supported, you can feed CME a comma seperated list of targets like this 
```
python crackmapexec.py 192.168.0.1,10.0.0.1-28,192.168.2.0/24
```

**Comment by byt3bl33d3r** [comment]
Thinking about this more it might be more efficient code wise to use the nmap style instead of a comma separated list of values. Will look into this, thanks again!

**Comment by maaaaz** [comment]
Sure, adding the fact that everyone already knows that syntax.
