### ISSUE TITLE
Race conditions and deadlocks for log files when launching at least 2 instances of  CME

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#73]
The title says it all :), I'm talking about that line:
```
fileHandler = logging.FileHandler('./logs/{}_{}.log'.format(target.replace('/', '_'), datetime.now().strftime('%Y-%m-%d')))
```
Don't you want to ensure **uniqueness for file logs** ?

Plus, don't you want to check for **dir existence** before opening files ?
```
with open('hosted/'+ self.path[1:], 'rb') as script:
```
```
log_name = 'Mimikatz-{}-{}.log'.format(self.client_address[0], datetime.now().strftime("%Y-%m-%d_%H%M%S"))
        with open('logs/' + log_name, 'w') as creds:
```
Plus, don't you want to add a small check for **forbidden chars** in filenames ? One day, `client_address[0]` will contain an IPv6 string :p

Cheers !

**Comment by byt3bl33d3r** [comment]
@maaaaz By default console output is not logged in v3.0, they'll probably be a config file to enable it. Closing in the meantime.
