### ISSUE TITLE
Password list bug

### ISSUE THREAD

**Issue by vysec** [byt3bl33d3r/CrackMapExec#77]
When I try to brute using a password list, it no longer works.

It used to work just fine. Now it just exits and does not even attempt to bruteforce.

-- Edit: rolled back to older version, works fine. Therefore it must be a new change that broke it.

**Comment by byt3bl33d3r** [comment]
@vysec can you give me a little bit more information? Can you paste the full command string you used and the output ?

**Comment by byt3bl33d3r** [comment]
@vysec Also , FYI, the ```-u``` and ```-p``` flags now only support arguments separated by a space.
(e.g. ```-u user1 user2 -p pass1 pass2```)

**Comment by vysec** [comment]
So pretty much

python crackmapexec.py 172.16.10.10 - u John - p /usr/share/wordlists/rockyou.txt

excuse the spaces. 

basically this works on an older version I have but not the latest

**Comment by byt3bl33d3r** [comment]
@vysec yup my bad, reproduced it and working on a fix

**Comment by vysec** [comment]
Yay thanks for all the hard work. Sorry I couldn't help any more.

**Comment by vysec** [comment]
Looking at some latest commits, has this been resolved? Worth closing if so :D

**Comment by vysec** [comment]
Tested today, issue still exists.

**Comment by byt3bl33d3r** [comment]
@vysec Should be fixed in v3.0
