### ISSUE TITLE
Add Pentoo to supported list

### ISSUE THREAD

**Issue by blshkv** [byt3bl33d3r/CrackMapExec#78]
Hi, I have recently added CrackMapExec to Pentoo.  The latest version was pushed yesterday: https://github.com/pentoo/pentoo-overlay/commit/f73afc8589033d98341d82e0b6e5577fca71dd1a

Unlike Kali, our system is more flexible and up-to-date so there is no need in virtual environment.
Our users can simply install it using a standard command:
```emerge crackmapexec"

Please update README file.

**Comment by byt3bl33d3r** [comment]
@blshkv That's awesome! thanks for the heads up! will do!

**Comment by blshkv** [comment]
You haven't updated the README.md file. I can't re-open the bug so please dont forget.
