### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by macubergeek** [byt3bl33d3r/CrackMapExec#8]
I ran pip install --upgrade -r requirements.txt on Kali2
it seemed to complete successfully but when I run:
python crackmapexec.py
I get error:
Traceback (most recent call last):
  File "crackmapexec.py", line 16, in <module>
    from impacket.dcerpc.v5 import transport, scmr, samr, drsuapi, rrp, tsch, srvs, wkst, epm
ImportError: cannot import name drsuapi

When I try and install drsuapi
I'm told:
Requirement already satisfied (use --upgrade to upgrade): impacket in /usr/lib/python2.7/dist-packages

**Comment by byt3bl33d3r** [comment]
@macubergeek hi,
your impacket install from kali's repos is conflicting with the newer one that is needed. Try using a virtualenv or removing impacket with ```apt-get``` and the re-installing

**Comment by byt3bl33d3r** [comment]
also see #1
