### ISSUE TITLE
more tut

### ISSUE THREAD

**Issue by famous0123** [byt3bl33d3r/CrackMapExec#81]
Hello sir i really appreciate....what you have done so far......please i want to understand this tools better....is that befor i scan with the tools i must have one VPS/RDP user and pass....then a will able to use the tools or all work like scanning and brutus thanks......need more tut on it and Gcat God bless

Best regards

**Comment by byt3bl33d3r** [comment]
No clue what you said, in regards to tutorials tho I'm going to be writing a series of blog posts
