### ISSUE TITLE
error

### ISSUE THREAD

**Issue by famous0123** [byt3bl33d3r/CrackMapExec#82]
(CME)┌─[✗]─[root@parrot]─[/usr/share/virtualenvwrapper/CrackMapExec]
└──╼ #python crackmapexec.py -t 100 172.16.112.1
(CME)┌─[✗]─[root@parrot]─[/usr/share/virtualenvwrapper/CrackMapExec]
└──╼ #
what can i do ....it not running thanks

**Comment by byt3bl33d3r** [comment]
Install pyOpenSSL, Impacket currently fails silently if that dep is not installed
