### ISSUE TITLE
Installation error in kali rolling using virtualenvwrapper

### ISSUE THREAD

**Issue by lizardpunk** [byt3bl33d3r/CrackMapExec#84]
error: command 'i586-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
Failed to build cryptography
Installing collected packages: greenlet, gevent, netaddr, pycrypto, pyasn1, termcolor, colorama, six, idna, enum34, ipaddress, pycparser, cffi, cryptography, pyOpenSSL, impacket
  Running setup.py install for cryptography ... error
    Complete output from command /root/.virtualenvs/CME/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rDFzR7/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ypPotG-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.virtualenvs/CME/include/site/python2.7/cryptography:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-i686-2.7
    creating build/lib.linux-i686-2.7/cryptography
    copying src/cryptography/__about__.py -> build/lib.linux-i686-2.7/cryptography
    copying src/cryptography/fernet.py -> build/lib.linux-i686-2.7/cryptography
    copying src/cryptography/utils.py -> build/lib.linux-i686-2.7/cryptography
    copying src/cryptography/exceptions.py -> build/lib.linux-i686-2.7/cryptography
    copying src/cryptography/__init__.py -> build/lib.linux-i686-2.7/cryptography
    creating build/lib.linux-i686-2.7/cryptography/x509
    copying src/cryptography/x509/base.py -> build/lib.linux-i686-2.7/cryptography/x509
    copying src/cryptography/x509/general_name.py -> build/lib.linux-i686-2.7/cryptography/x509
    copying src/cryptography/x509/oid.py -> build/lib.linux-i686-2.7/cryptography/x509
    copying src/cryptography/x509/__init__.py -> build/lib.linux-i686-2.7/cryptography/x509
    copying src/cryptography/x509/name.py -> build/lib.linux-i686-2.7/cryptography/x509
    copying src/cryptography/x509/extensions.py -> build/lib.linux-i686-2.7/cryptography/x509
    creating build/lib.linux-i686-2.7/cryptography/hazmat
    copying src/cryptography/hazmat/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat
    creating build/lib.linux-i686-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/serialization.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives
    creating build/lib.linux-i686-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/multibackend.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends
    creating build/lib.linux-i686-2.7/cryptography/hazmat/bindings
    copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat/bindings
    creating build/lib.linux-i686-2.7/cryptography/hazmat/primitives/interfaces
    copying src/cryptography/hazmat/primitives/interfaces/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/interfaces
    creating build/lib.linux-i686-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/kdf
    creating build/lib.linux-i686-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/asymmetric
    creating build/lib.linux-i686-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/ciphers
    creating build/lib.linux-i686-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat/primitives/twofactor
    creating build/lib.linux-i686-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/hashes.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/backend.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/ciphers.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/hmac.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/commoncrypto
    creating build/lib.linux-i686-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-i686-2.7/cryptography/hazmat/backends/openssl
    creating build/lib.linux-i686-2.7/cryptography/hazmat/bindings/commoncrypto
    copying src/cryptography/hazmat/bindings/commoncrypto/binding.py -> build/lib.linux-i686-2.7/cryptography/hazmat/bindings/commoncrypto
    copying src/cryptography/hazmat/bindings/commoncrypto/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat/bindings/commoncrypto
    creating build/lib.linux-i686-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-i686-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-i686-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-i686-2.7/cryptography/hazmat/bindings/openssl
    running egg_info
    writing requirements to src/cryptography.egg-info/requires.txt
    writing src/cryptography.egg-info/PKG-INFO
    writing top-level names to src/cryptography.egg-info/top_level.txt
    writing dependency_links to src/cryptography.egg-info/dependency_links.txt
    writing entry points to src/cryptography.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-i686-2.7/_padding.c'
    creating build/temp.linux-i686-2.7
    generating cffi module 'build/temp.linux-i686-2.7/_constant_time.c'
    generating cffi module 'build/temp.linux-i686-2.7/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-i686-2.7/build
    creating build/temp.linux-i686-2.7/build/temp.linux-i686-2.7
    i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-i686-2.7/_openssl.c -o build/temp.linux-i686-2.7/build/temp.linux-i686-2.7/_openssl.o
    build/temp.linux-i686-2.7/_openssl.c:431:25: fatal error: openssl/aes.h: No such file or directory
    compilation terminated.
    error: command 'i586-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/root/.virtualenvs/CME/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rDFzR7/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ypPotG-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.virtualenvs/CME/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-rDFzR7/cryptography

**Comment by ropnop** [comment]
had a similar issue. it appears the latest version of Kali doesn't come with OpenSSL headers. Try running `apt-get install libssl-dev` and then re-running pip. PyCrypto should install correctly then. I was gonna actually open a separate issue cuz it gave me such a headache. The install instructions should probably be updated to state that libssl-dev is a requirement.

**Comment by byt3bl33d3r** [comment]
@lizardpunk @ropnop Just updated the install intructions! thanks!
