### ISSUE TITLE
Bug using the --mimikatz flag

### ISSUE THREAD

**Issue by neofito** [byt3bl33d3r/CrackMapExec#85]
Using the --mimikatz flag the credentials are correctly dumped but I have to manually interrupt the connection (Ctrl+C).

I recently experienced the same issue using pth-winexe and Invoke-Mimikatz and finally it was corrected creating a wmi process closing inmediately the connection after that. The credentials were copied to my purposely created share time after the connection allowing me to successfully dump the credentials for a lot of windows boxes.

I hope this could help (and I apologize for my poor english)

**Comment by byt3bl33d3r** [comment]
@neofito This is intended behavior. Currently connections aren't being tracked by the web server, thats why you have to manually Ctrl-C. I may implement auto connection tracking in a future update, although that would complicate things code wise.
