### ISSUE TITLE
one bug in kali2

### ISSUE THREAD

**Issue by scuhurricane** [byt3bl33d3r/CrackMapExec#87]
When I  use this tool in kali2 which is 2016.01 version, I find one bug: when I set username and password in command line, it works right.  but when I put username and password in files, it can not find the right result.  I just put the only one right username and password in file.

in kali1.09, I don't find this problem. This tool works beautifully.
I test in 2016.03.15 with the newest version CrackMapExec.

Thank you for this great tool.

**Comment by byt3bl33d3r** [comment]
@scuhurricane could you please pastebin an example of the files you're using ? thanks!

**Comment by byt3bl33d3r** [comment]
@scuhurricane whatever it was, it should be fixed in v3.0
