### ISSUE TITLE
Enable RDP  

### ISSUE THREAD

**Issue by DoZ10** [byt3bl33d3r/CrackMapExec#88]
@byt3bl33d3r ,

Hi there, 

it would be really nice and useful to implement --enable-rdp and --disable-rdp options.
Enabling RDP requires at least registry key change and firewall rule addition.

Enable RDP: HKLMSYSTEM\CurrentControlSet\Control\Terminal Server\fDenyTSConnections -> set to 0 
Enable firewall: netsh advfirewall firewall add rule name="Open Port 3389" dir=in action=allow protocol=TCP localport=3389

**Comment by byt3bl33d3r** [comment]
@DoZ10 Added in https://github.com/byt3bl33d3r/CrackMapExec/commit/3e27f30cb1bc11f8dec0161cdb450aa1264b0015. Thanks
