### ISSUE TITLE
Error on usage.

### ISSUE THREAD

**Issue by vysec** [byt3bl33d3r/CrackMapExec#91]
root@thanatos-k:/usr/share/CrackMapExec# python crackmapexec.py 192.168.179.3 -u vysec
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/share/CrackMapExec/core/connector.py", line 49, in connector
    db.add_host(remote_ip, servername, domain, serveros)
  File "/usr/share/CrackMapExec/core/database.py", line 12, in add_host
    cur.execute('SELECT * FROM hosts WHERE ip LIKE ?', [ip])
OperationalError: no such table: hosts
<Greenlet at 0x7f56302e4410: connector('192.168.179.3', Namespace(command=None, cred_id=None, depth=10, di, <core.database.CMEDatabase instance at 0x7f5630314, None, None, None)> failed with OperationalError

Steps:
1) git clone <REPO>
2) pip install -r requirements.txt
3) crackmapexec.py 192.168.179.3 -u vysec

**Comment by vysec** [comment]
Fixed. Closed

**Comment by byt3bl33d3r** [comment]
@vysec i messed up the error handling when the database isnt created prior to running the script for the first time, just pushed a fix in a1c41d97c96278eb3e7e28fb82073d1b9acb72dc

**Comment by vysec** [comment]
I figured it worked fine if I followed instructions properly :)
