### ISSUE TITLE
Encoding bug when getting the results of a windows command

### ISSUE THREAD

**Issue by ArnCo** [byt3bl33d3r/CrackMapExec#92]
Hi,

I'm trying to execute the follwing command on a french version of Windows 12 :
`sudo crackmapexec -uxxxx -pyyyy 10.0.0.1 -x 'net user'`

Unfortunately, one of the users has some special character in its name, resulting in the following stacktrace:

```
ERROR:root:'ascii' codec can't decode byte 0x82 in position 55: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/share/crackmapexec/core/greenlets.py", line 242, in main_greenlet
    ntlm_hash)
  File "/usr/share/crackmapexec/core/executor.py", line 30, in __init__
    wmi_exec.run(host, connection)
  File "/usr/share/crackmapexec/core/scripts/wmiexec.py", line 82, in run
    dcom.disconnect()
  File "/usr/lib/python2.7/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1070, in disconnect
    del(INTERFACE.CONNECTIONS[self.__target][currentThread().getName()])
KeyError: 'DummyThread-1'
<Greenlet at 0x7f14a8a01b90: main_greenlet('10.0.0.1')> failed with KeyError
```
I think that it happens when the script tries to print the output of the command in the shell.

Keep up the great work, this tool is awesome =) !

**Comment by byt3bl33d3r** [comment]
can you give me the output of the same command with the --verbose flag? Thanks

**Comment by byt3bl33d3r** [comment]
Ignore that, referenced the wrong issue number

**Comment by byt3bl33d3r** [comment]
This should be fixed in https://github.com/byt3bl33d3r/CrackMapExec/commit/d256444cb5fa7e7d27b41f7026649e0819d6816e
