### ISSUE TITLE
Mimikatz support

### ISSUE THREAD

**Issue by 0xsauby** [byt3bl33d3r/CrackMapExec#94]
Have you dropped the mimikatz (--mimikatz) support recently?

**Comment by byt3bl33d3r** [comment]
@0xsauby All powershell related functionality has been ported to payload modules. See the wiki here https://github.com/byt3bl33d3r/CrackMapExec/wiki/Using-Payload-Modules

**Comment by 0xsauby** [comment]
Ah, gotcha. Thanks.
