### ISSUE TITLE
make it distro friendly

### ISSUE THREAD

**Issue by blshkv** [byt3bl33d3r/CrackMapExec#95]
Currently, you seems expect a user to extract the software to a random place and write all output (logs/database) to that location. However, things go bad if it is installed in a system location (/usr/lib64 or anywhere else). The software should not modify any system files directly (under /usr).

Please create a config file which would allow me to configure where the output should be.
I suggest to make it ~./crackmapexec or ~./local/crackmapexec by default.

**Comment by blshkv** [comment]
on a similar note, you shouldn't use relative paths. For example, the following fails if it's called from /usr/bin/crackmapexec: ```sqlite3.connect('data/cme.db'```

**Comment by byt3bl33d3r** [comment]
@blshkv Just pushed v3.1 as of commit ca9e272f26c747bff6b16b01fca55f990eb1619a, CME is now portable and able to be packaged on pypi. Additionally it can be run from any directory and stores logs and its database in ~/.cme. \o/

**Comment by blshkv** [comment]
almost there. I'm getting few errors:
```
byte-compiling /var/tmp/portage/net-analyzer/crackmapexec-3.1/image//_python2.7/usr/lib64/python2.7/site-packages/cme/cmeserver.py to cmeserver.pyc
  File "/usr/lib64/python2.7/site-packages/cme/cmeserver.py", line 4
    <<<<<<< HEAD:cme/cmeserver.py
     ^
SyntaxError: invalid syntax
```

```
/usr/bin/python2.7 -OO /var/tmp/portage/net-analyzer/crackmapexec-3.1/temp/tmpFsPymp.py
  File "/usr/lib64/python2.7/site-packages/cme/cmeserver.py", line 4
    <<<<<<< HEAD:cme/cmeserver.py
     ^
SyntaxError: invalid syntax

```

**Comment by byt3bl33d3r** [comment]
that was me being dumb, do a git pull and you should be good

**Comment by blshkv** [comment]
https://github.com/byt3bl33d3r/CrackMapExec/commit/1e281bd638a27e9da024a31a3cabb87ef9f7202b
ok

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/commit/69c843287c47168d8c53f6c9df9d07fd10784cf4 
pushed to Pentoo
