### ISSUE TITLE
Download Files from SMB Share

### ISSUE THREAD

**Issue by jabra-** [byt3bl33d3r/CrackMapExec#96]
It would be nice if CME could download files from the fileshare, either specific files the user wanted, all the files in a folder or the files that were found by the spider.

**Comment by byt3bl33d3r** [comment]
@jabra- the reason why i took it out of v3.0 is because you can just use smbclient to do this... is there any reason that I'm missing why CME should have this ?

**Comment by bucky67gto** [comment]
can you use the hash instead of the password for smbclient?  If not, it would be great as I can spider the files using the -H flag, but can not download with it.
