### ISSUE TITLE
The service module disappeared in v3.0, why ?

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#98]
Hello @byt3bl33d3r,

The title says it all :)

Cheers!

**Comment by byt3bl33d3r** [comment]
For multiple reasons:
* It's not opsec safe at all (e.g. binaries are dropped to disk, system configurations are changed)
* I've never actually found any use for it during a pentest
* If you need that functionality you can use Impacket's script

**Comment by maaaaz** [comment]
that's clear, thanks :)
